export type BaseballPlayer = {
  name: string;
  team: string;
  backNumber: `${number}`;
  position: string;
  hand: "RHP" | "LHP" | "RHH" | "LHH" | "SHH";
  birth: string;
};

export const KBO_ROSTERS: BaseballPlayer[] = [
  {
    name: "최지강",
    team: "두산 베어스",
    backNumber: "42",
    position: "RP",
    hand: "RHP",
    birth: "Jul 23 2001",
  },
  {
    name: "최종인",
    team: "두산 베어스",
    backNumber: "40",
    position: "RP",
    hand: "RHP",
    birth: "May 1 2001",
  },
  {
    name: "최준호",
    team: "두산 베어스",
    backNumber: "41",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jun 3 2004",
  },
  {
    name: "최민석",
    team: "두산 베어스",
    backNumber: "68",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jul 2 2006",
  },
  {
    name: "최승용",
    team: "두산 베어스",
    backNumber: "28",
    position: "SP",
    hand: "LHP",
    birth: "May 11 2001",
  },
  {
    name: "최원준",
    team: "두산 베어스",
    backNumber: "61",
    position: "SP",
    hand: "RHP",
    birth: "Dec 21 1994",
  },
  {
    name: "곽빈",
    team: "두산 베어스",
    backNumber: "47",
    position: "SP/RP",
    hand: "RHP",
    birth: "May 28 1999",
  },
  {
    name: "홍건희",
    team: "두산 베어스",
    backNumber: "17",
    position: "RP",
    hand: "RHP",
    birth: "Sep 29 1992",
  },
  {
    name: "홍민규",
    team: "두산 베어스",
    backNumber: "67",
    position: "SP/RP",
    hand: "RHP",
    birth: "Sep 11 2006",
  },
  {
    name: "황희천",
    team: "두산 베어스",
    backNumber: "58",
    position: "RP",
    hand: "LHP",
    birth: "Nov 6 2006",
  },
  {
    name: "콜 어빈",
    team: "두산 베어스",
    backNumber: "57",
    position: "SP",
    hand: "LHP",
    birth: "Jan 31 1994",
  },
  {
    name: "제환유",
    team: "두산 베어스",
    backNumber: "93",
    position: "RP",
    hand: "RHP",
    birth: "Sep 30 2000",
  },
  {
    name: "정은재",
    team: "두산 베어스",
    backNumber: "102",
    position: "RP",
    hand: "RHP",
    birth: "Dec 31 1991",
  },
  {
    name: "김호준",
    team: "두산 베어스",
    backNumber: "56",
    position: "RP",
    hand: "LHP",
    birth: "May 17 1998",
  },
  {
    name: "김정우",
    team: "두산 베어스",
    backNumber: "30",
    position: "RP",
    hand: "RHP",
    birth: "May 15 1999",
  },
  {
    name: "김민규",
    team: "두산 베어스",
    backNumber: "19",
    position: "RP",
    hand: "RHP",
    birth: "May 7 1999",
  },
  {
    name: "김무빈",
    team: "두산 베어스",
    backNumber: "64",
    position: "RP",
    hand: "LHP",
    birth: "Apr 11 2005",
  },
  {
    name: "김명신",
    team: "두산 베어스",
    backNumber: "46",
    position: "RP",
    hand: "RHP",
    birth: "Nov 29 1993",
  },
  {
    name: "김택연",
    team: "두산 베어스",
    backNumber: "63",
    position: "CP",
    hand: "RHP",
    birth: "Jun 3 2005",
  },
  {
    name: "김유성",
    team: "두산 베어스",
    backNumber: "20",
    position: "SP",
    hand: "RHP",
    birth: "Jan 1 2002",
  },
  {
    name: "고효준",
    team: "두산 베어스",
    backNumber: "35",
    position: "RP",
    hand: "LHP",
    birth: "Feb 8 1983",
  },
  {
    name: "권휘",
    team: "두산 베어스",
    backNumber: "18",
    position: "RP",
    hand: "RHP",
    birth: "Dec 7 2000",
  },
  {
    name: "이병헌",
    team: "두산 베어스",
    backNumber: "29",
    position: "RP",
    hand: "LHP",
    birth: "Jun 4 2003",
  },
  {
    name: "이교훈",
    team: "두산 베어스",
    backNumber: "7",
    position: "RP",
    hand: "LHP",
    birth: "May 29 2000",
  },
  {
    name: "이승진",
    team: "두산 베어스",
    backNumber: "55",
    position: "RP",
    hand: "RHP",
    birth: "Jan 7 1995",
  },
  {
    name: "이영하",
    team: "두산 베어스",
    backNumber: "50",
    position: "RP",
    hand: "RHP",
    birth: "Nov 1 1997",
  },
  {
    name: "잭 로그",
    team: "두산 베어스",
    backNumber: "39",
    position: "SP",
    hand: "LHP",
    birth: "Apr 23 1996",
  },
  {
    name: "박치국",
    team: "두산 베어스",
    backNumber: "1",
    position: "RP",
    hand: "RHP",
    birth: "Mar 10 1998",
  },
  {
    name: "박지호",
    team: "두산 베어스",
    backNumber: "4",
    position: "RP",
    hand: "LHP",
    birth: "Jul 2 2003",
  },
  {
    name: "박정수",
    team: "두산 베어스",
    backNumber: "12",
    position: "RP",
    hand: "RHP",
    birth: "Jan 29 1996",
  },
  {
    name: "박신지",
    team: "두산 베어스",
    backNumber: "49",
    position: "RP",
    hand: "RHP",
    birth: "Jul 16 1999",
  },
  {
    name: "양재훈",
    team: "두산 베어스",
    backNumber: "92",
    position: "RP",
    hand: "RHP",
    birth: "May 1 2003",
  },
  {
    name: "윤태호",
    team: "두산 베어스",
    backNumber: "65",
    position: "RP",
    hand: "RHP",
    birth: "Oct 10 2003",
  },
  {
    name: "장승현",
    team: "두산 베어스",
    backNumber: "22",
    position: "C",
    hand: "RHH",
    birth: "Mar 7 1994",
  },
  {
    name: "김기연",
    team: "두산 베어스",
    backNumber: "45",
    position: "C",
    hand: "RHH",
    birth: "Sep 7 1997",
  },
  {
    name: "박민준",
    team: "두산 베어스",
    backNumber: "26",
    position: "C",
    hand: "RHH",
    birth: "Oct 21 2002",
  },
  {
    name: "류현준",
    team: "두산 베어스",
    backNumber: "11",
    position: "C",
    hand: "RHH",
    birth: "Mar 25 2005",
  },
  {
    name: "양의지",
    team: "두산 베어스",
    backNumber: "25",
    position: "C",
    hand: "RHH",
    birth: "Jun 5 1987",
  },
  {
    name: "임종성",
    team: "두산 베어스",
    backNumber: "3",
    position: "IF",
    hand: "RHH",
    birth: "Mar 3 2005",
  },
  {
    name: "강승호",
    team: "두산 베어스",
    backNumber: "23",
    position: "2B",
    hand: "RHH",
    birth: "Feb 9 1994",
  },
  {
    name: "김동준",
    team: "두산 베어스",
    backNumber: "48",
    position: "IF",
    hand: "LHH",
    birth: "Sep 4 2002",
  },
  {
    name: "김준상",
    team: "두산 베어스",
    backNumber: "94",
    position: "IF",
    hand: "LHH",
    birth: "Aug 2 2004",
  },
  {
    name: "김민혁",
    team: "두산 베어스",
    backNumber: "10",
    position: "IF",
    hand: "RHH",
    birth: "May 3 1996",
  },
  {
    name: "이선우",
    team: "두산 베어스",
    backNumber: "24",
    position: "IF",
    hand: "LHH",
    birth: "Apr 4 2006",
  },
  {
    name: "이유찬",
    team: "두산 베어스",
    backNumber: "13",
    position: "2B",
    hand: "RHH",
    birth: "Aug 5 1998",
  },
  {
    name: "오명진",
    team: "두산 베어스",
    backNumber: "6",
    position: "2B",
    hand: "LHH",
    birth: "Sep 4 2001",
  },
  {
    name: "박계범",
    team: "두산 베어스",
    backNumber: "14",
    position: "2B",
    hand: "RHH",
    birth: "Jan 11 1996",
  },
  {
    name: "박지훈",
    team: "두산 베어스",
    backNumber: "37",
    position: "IF",
    hand: "RHH",
    birth: "Sep 7 2000",
  },
  {
    name: "박준순",
    team: "두산 베어스",
    backNumber: "52",
    position: "IF",
    hand: "RHH",
    birth: "Jul 13 2006",
  },
  {
    name: "박준영",
    team: "두산 베어스",
    backNumber: "16",
    position: "SS",
    hand: "RHH",
    birth: "Aug 5 1997",
  },
  {
    name: "양석환",
    team: "두산 베어스",
    backNumber: "53",
    position: "1B",
    hand: "RHH",
    birth: "Jul 15 1991",
  },
  {
    name: "여통건",
    team: "두산 베어스",
    backNumber: "5",
    position: "2B",
    hand: "RHH",
    birth: "Aug 4 2005",
  },
  {
    name: "제이크 케이브",
    team: "두산 베어스",
    backNumber: "8",
    position: "RF",
    hand: "LHH",
    birth: "Dec 4 1992",
  },
  {
    name: "추재현",
    team: "두산 베어스",
    backNumber: "36",
    position: "OF",
    hand: "LHH",
    birth: "Feb 22 1999",
  },
  {
    name: "전다민",
    team: "두산 베어스",
    backNumber: "9",
    position: "OF",
    hand: "LHH",
    birth: "Aug 21 2001",
  },
  {
    name: "조수행",
    team: "두산 베어스",
    backNumber: "51",
    position: "RF",
    hand: "LHH",
    birth: "Aug 30 1993",
  },
  {
    name: "정수빈",
    team: "두산 베어스",
    backNumber: "31",
    position: "CF",
    hand: "LHH",
    birth: "Oct 7 1990",
  },
  {
    name: "강현구",
    team: "두산 베어스",
    backNumber: "60",
    position: "OF",
    hand: "RHH",
    birth: "Jun 16 2002",
  },
  {
    name: "김대한",
    team: "두산 베어스",
    backNumber: "27",
    position: "LF",
    hand: "RHH",
    birth: "Dec 6 2000",
  },
  {
    name: "김인태",
    team: "두산 베어스",
    backNumber: "33",
    position: "LF",
    hand: "LHH",
    birth: "Jul 3 1994",
  },
  {
    name: "김재환",
    team: "두산 베어스",
    backNumber: "32",
    position: "LF",
    hand: "LHH",
    birth: "Sep 22 1988",
  },
  {
    name: "김민석",
    team: "두산 베어스",
    backNumber: "2",
    position: "LF",
    hand: "LHH",
    birth: "May 9 2004",
  },
  {
    name: "배동현",
    team: "한화 이글스",
    backNumber: "61",
    position: "RP",
    hand: "RHP",
    birth: "Mar 16 1998",
  },
  {
    name: "배민서",
    team: "한화 이글스",
    backNumber: "45",
    position: "RP",
    hand: "RHP",
    birth: "Nov 18 1999",
  },
  {
    name: "조동욱",
    team: "한화 이글스",
    backNumber: "68",
    position: "SP/RP",
    hand: "LHP",
    birth: "Nov 2 2004",
  },
  {
    name: "권민규",
    team: "한화 이글스",
    backNumber: "64",
    position: "RP",
    hand: "LHP",
    birth: "May 13 2006",
  },
  {
    name: "한승혁",
    team: "한화 이글스",
    backNumber: "26",
    position: "RP",
    hand: "RHP",
    birth: "Jan 3 1993",
  },
  {
    name: "황준서",
    team: "한화 이글스",
    backNumber: "29",
    position: "SP/RP",
    hand: "LHP",
    birth: "Aug 22 2005",
  },
  {
    name: "장지현",
    team: "한화 이글스",
    backNumber: "40",
    position: "RP",
    hand: "RHP",
    birth: "May 25 2000",
  },
  {
    name: "장민재",
    team: "한화 이글스",
    backNumber: "36",
    position: "RP",
    hand: "RHP",
    birth: "Mar 19 1990",
  },
  {
    name: "장시환",
    team: "한화 이글스",
    backNumber: "28",
    position: "RP",
    hand: "RHP",
    birth: "Nov 1 1987",
  },
  {
    name: "정우주",
    team: "한화 이글스",
    backNumber: "43",
    position: "RP",
    hand: "RHP",
    birth: "Nov 7 2006",
  },
  {
    name: "주현상",
    team: "한화 이글스",
    backNumber: "66",
    position: "RP",
    hand: "RHP",
    birth: "Aug 10 1992",
  },
  {
    name: "김범수",
    team: "한화 이글스",
    backNumber: "47",
    position: "RP",
    hand: "LHP",
    birth: "Oct 3 1995",
  },
  {
    name: "김도빈",
    team: "한화 이글스",
    backNumber: "62",
    position: "RP",
    hand: "RHP",
    birth: "Jan 5 2001",
  },
  {
    name: "김종수",
    team: "한화 이글스",
    backNumber: "38",
    position: "RP",
    hand: "RHP",
    birth: "Jun 3 1994",
  },
  {
    name: "김기중",
    team: "한화 이글스",
    backNumber: "15",
    position: "RP",
    hand: "LHP",
    birth: "Nov 16 2002",
  },
  {
    name: "김규연",
    team: "한화 이글스",
    backNumber: "60",
    position: "RP",
    hand: "RHP",
    birth: "Aug 23 2002",
  },
  {
    name: "김민우",
    team: "한화 이글스",
    backNumber: "53",
    position: "RP",
    hand: "RHP",
    birth: "Jul 25 1995",
  },
  {
    name: "김서현",
    team: "한화 이글스",
    backNumber: "44",
    position: "CP",
    hand: "RHP",
    birth: "May 31 2004",
  },
  {
    name: "김승일",
    team: "한화 이글스",
    backNumber: "14",
    position: "RP",
    hand: "RHP",
    birth: "Jul 7 2001",
  },
  {
    name: "이민우",
    team: "한화 이글스",
    backNumber: "27",
    position: "RP",
    hand: "RHP",
    birth: "Feb 9 1993",
  },
  {
    name: "이상규",
    team: "한화 이글스",
    backNumber: "18",
    position: "RP",
    hand: "RHP",
    birth: "Oct 20 1996",
  },
  {
    name: "이태양",
    team: "한화 이글스",
    backNumber: "46",
    position: "RP",
    hand: "RHP",
    birth: "Jul 3 1990",
  },
  {
    name: "문동주",
    team: "한화 이글스",
    backNumber: "1",
    position: "SP",
    hand: "RHP",
    birth: "Dec 23 2003",
  },
  {
    name: "박상원",
    team: "한화 이글스",
    backNumber: "58",
    position: "RP",
    hand: "RHP",
    birth: "Sep 9 1994",
  },
  {
    name: "코디 폰세",
    team: "한화 이글스",
    backNumber: "30",
    position: "SP",
    hand: "RHP",
    birth: "Apr 25 1994",
  },
  {
    name: "류현진",
    team: "한화 이글스",
    backNumber: "99",
    position: "SP",
    hand: "LHP",
    birth: "Mar 25 1987",
  },
  {
    name: "성지현",
    team: "한화 이글스",
    backNumber: "57",
    position: "RP",
    hand: "LHP",
    birth: "Jan 29 2000",
  },
  {
    name: "엄상백",
    team: "한화 이글스",
    backNumber: "11",
    position: "SP",
    hand: "RHP",
    birth: "Oct 4 1996",
  },
  {
    name: "라이언 와이스",
    team: "한화 이글스",
    backNumber: "55",
    position: "SP",
    hand: "RHP",
    birth: "Dec 10 1996",
  },
  {
    name: "원종혁",
    team: "한화 이글스",
    backNumber: "48",
    position: "RP",
    hand: "RHP",
    birth: "Aug 27 2005",
  },
  {
    name: "윤대경",
    team: "한화 이글스",
    backNumber: "5",
    position: "RP",
    hand: "RHP",
    birth: "Apr 9 1994",
  },
  {
    name: "장기훈",
    team: "한화 이글스",
    backNumber: "32",
    position: "C",
    hand: "LHH",
    birth: "Jun 28 2002",
  },
  {
    name: "최재훈",
    team: "한화 이글스",
    backNumber: "13",
    position: "C",
    hand: "RHH",
    birth: "Aug 27 1989",
  },
  {
    name: "한지용",
    team: "한화 이글스",
    backNumber: "67",
    position: "C",
    hand: "RHH",
    birth: "Apr 10 2006",
  },
  {
    name: "허인서",
    team: "한화 이글스",
    backNumber: "59",
    position: "C",
    hand: "RHH",
    birth: "Jul 11 2003",
  },
  {
    name: "이재원",
    team: "한화 이글스",
    backNumber: "20",
    position: "C",
    hand: "RHH",
    birth: "Feb 24 1988",
  },
  {
    name: "박상운",
    team: "한화 이글스",
    backNumber: "42",
    position: "C",
    hand: "RHH",
    birth: "Mar 3 1997",
  },
  {
    name: "안치홍",
    team: "한화 이글스",
    backNumber: "3",
    position: "2B",
    hand: "RHH",
    birth: "Jul 2 1990",
  },
  {
    name: "배승수",
    team: "한화 이글스",
    backNumber: "98",
    position: "IF",
    hand: "RHH",
    birth: "May 15 2006",
  },
  {
    name: "채은성",
    team: "한화 이글스",
    backNumber: "22",
    position: "1B",
    hand: "RHH",
    birth: "Feb 6 1990",
  },
  {
    name: "하주석",
    team: "한화 이글스",
    backNumber: "16",
    position: "SS",
    hand: "LHH",
    birth: "Feb 25 1994",
  },
  {
    name: "황영묵",
    team: "한화 이글스",
    backNumber: "95",
    position: "2B",
    hand: "LHH",
    birth: "Oct 16 1999",
  },
  {
    name: "정민규",
    team: "한화 이글스",
    backNumber: "65",
    position: "IF",
    hand: "RHH",
    birth: "Jan 10 2003",
  },
  {
    name: "김인환",
    team: "한화 이글스",
    backNumber: "37",
    position: "LF",
    hand: "LHH",
    birth: "Jan 28 1994",
  },
  {
    name: "권광민",
    team: "한화 이글스",
    backNumber: "17",
    position: "LF",
    hand: "LHH",
    birth: "Dec 12 1997",
  },
  {
    name: "이도윤",
    team: "한화 이글스",
    backNumber: "7",
    position: "2B",
    hand: "LHH",
    birth: "Oct 7 1996",
  },
  {
    name: "이승현",
    team: "한화 이글스",
    backNumber: "60",
    position: "IF",
    hand: "LHH",
    birth: "Jul 23 2002",
  },
  {
    name: "문현빈",
    team: "한화 이글스",
    backNumber: "51",
    position: "3B",
    hand: "LHH",
    birth: "Apr 20 2004",
  },
  {
    name: "노시환",
    team: "한화 이글스",
    backNumber: "8",
    position: "3B",
    hand: "RHH",
    birth: "Dec 3 2000",
  },
  {
    name: "심우준",
    team: "한화 이글스",
    backNumber: "2",
    position: "SS",
    hand: "RHH",
    birth: "Apr 28 1995",
  },
  {
    name: "최인호",
    team: "한화 이글스",
    backNumber: "41",
    position: "RF",
    hand: "LHH",
    birth: "Jan 30 2000",
  },
  {
    name: "최준서",
    team: "한화 이글스",
    backNumber: "94",
    position: "OF",
    hand: "LHH",
    birth: "Jun 29 2000",
  },
  {
    name: "에스테반 플로리얼",
    team: "한화 이글스",
    backNumber: "34",
    position: "OF",
    hand: "LHH",
    birth: "Nov 25 1997",
  },
  {
    name: "김태연",
    team: "한화 이글스",
    backNumber: "25",
    position: "RF",
    hand: "RHH",
    birth: "Jun 10 1997",
  },
  {
    name: "이진영",
    team: "한화 이글스",
    backNumber: "10",
    position: "CF",
    hand: "RHH",
    birth: "Jul 21 1997",
  },
  {
    name: "이민재",
    team: "한화 이글스",
    backNumber: "57",
    position: "OF",
    hand: "LHH",
    birth: "Mar 7 2004",
  },
  {
    name: "이상혁",
    team: "한화 이글스",
    backNumber: "9",
    position: "OF",
    hand: "LHH",
    birth: "Sep 14 2001",
  },
  {
    name: "이원석",
    team: "한화 이글스",
    backNumber: "50",
    position: "LF",
    hand: "RHH",
    birth: "Mar 31 1999",
  },
  {
    name: "리베라토 루이스",
    team: "한화 이글스",
    backNumber: "0",
    position: "OF",
    hand: "LHH",
    birth: "Dec 18 1995",
  },
  {
    name: "임종찬",
    team: "한화 이글스",
    backNumber: "24",
    position: "RF",
    hand: "LHH",
    birth: "Sep 28 2001",
  },
  {
    name: "유로결",
    team: "한화 이글스",
    backNumber: "33",
    position: "RF",
    hand: "RHH",
    birth: "May 30 2000",
  },
  {
    name: "조상우",
    team: "KIA 타이거즈",
    backNumber: "11",
    position: "RP",
    hand: "RHP",
    birth: "Sep 4 1994",
  },
  {
    name: "최지민",
    team: "KIA 타이거즈",
    backNumber: "39",
    position: "RP",
    hand: "LHP",
    birth: "Sep 10 2003",
  },
  {
    name: "홍원빈",
    team: "KIA 타이거즈",
    backNumber: "30",
    position: "RP",
    hand: "RHP",
    birth: "Oct 16 2000",
  },
  {
    name: "황동하",
    team: "KIA 타이거즈",
    backNumber: "41",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jul 30 2002",
  },
  {
    name: "임기영",
    team: "KIA 타이거즈",
    backNumber: "17",
    position: "RP",
    hand: "RHP",
    birth: "Apr 16 1993",
  },
  {
    name: "장재혁",
    team: "KIA 타이거즈",
    backNumber: "38",
    position: "RP",
    hand: "RHP",
    birth: "Aug 2 2001",
  },
  {
    name: "전상현",
    team: "KIA 타이거즈",
    backNumber: "51",
    position: "RP",
    hand: "RHP",
    birth: "Apr 18 1996",
  },
  {
    name: "정해영",
    team: "KIA 타이거즈",
    backNumber: "62",
    position: "CP",
    hand: "RHP",
    birth: "Aug 23 2001",
  },
  {
    name: "김대유",
    team: "KIA 타이거즈",
    backNumber: "69",
    position: "RP",
    hand: "LHP",
    birth: "May 8 1991",
  },
  {
    name: "김도현",
    team: "KIA 타이거즈",
    backNumber: "60",
    position: "SP",
    hand: "RHP",
    birth: "Sep 15 2000",
  },
  {
    name: "김현수",
    team: "KIA 타이거즈",
    backNumber: "32",
    position: "RP",
    hand: "RHP",
    birth: "Jul 10 2000",
  },
  {
    name: "김정엽",
    team: "KIA 타이거즈",
    backNumber: "46",
    position: "RP",
    hand: "RHP",
    birth: "Apr 18 2006",
  },
  {
    name: "김건국",
    team: "KIA 타이거즈",
    backNumber: "43",
    position: "RP",
    hand: "RHP",
    birth: "Feb 2 1988",
  },
  {
    name: "김기훈",
    team: "KIA 타이거즈",
    backNumber: "53",
    position: "RP",
    hand: "LHP",
    birth: "Jan 3 2000",
  },
  {
    name: "김민재",
    team: "KIA 타이거즈",
    backNumber: "30",
    position: "RP",
    hand: "RHP",
    birth: "Jul 8 2003",
  },
  {
    name: "김민주",
    team: "KIA 타이거즈",
    backNumber: "49",
    position: "RP",
    hand: "RHP",
    birth: "Sep 8 2002",
  },
  {
    name: "김사윤",
    team: "KIA 타이거즈",
    backNumber: "21",
    position: "RP",
    hand: "LHP",
    birth: "Jun 8 1994",
  },
  {
    name: "김승현",
    team: "KIA 타이거즈",
    backNumber: "24",
    position: "RP",
    hand: "RHP",
    birth: "Jul 9 1992",
  },
  {
    name: "김태형",
    team: "KIA 타이거즈",
    backNumber: "10",
    position: "RP",
    hand: "RHP",
    birth: "Dec 15 2006",
  },
  {
    name: "곽도규",
    team: "KIA 타이거즈",
    backNumber: "0",
    position: "RP",
    hand: "LHP",
    birth: "Apr 12 2004",
  },
  {
    name: "이의리",
    team: "KIA 타이거즈",
    backNumber: "48",
    position: "RP",
    hand: "LHP",
    birth: "Jun 16 2002",
  },
  {
    name: "이호민",
    team: "KIA 타이거즈",
    backNumber: "63",
    position: "RP",
    hand: "RHP",
    birth: "Aug 26 2006",
  },
  {
    name: "이형범",
    team: "KIA 타이거즈",
    backNumber: "28",
    position: "RP",
    hand: "RHP",
    birth: "Feb 27 1994",
  },
  {
    name: "이준영",
    team: "KIA 타이거즈",
    backNumber: "20",
    position: "RP",
    hand: "LHP",
    birth: "Aug 10 1992",
  },
  {
    name: "제임스 네일",
    team: "KIA 타이거즈",
    backNumber: "40",
    position: "SP",
    hand: "RHP",
    birth: "Feb 8 1993",
  },
  {
    name: "아담 올러",
    team: "KIA 타이거즈",
    backNumber: "33",
    position: "SP",
    hand: "RHP",
    birth: "Oct 17 1994",
  },
  {
    name: "박준표",
    team: "KIA 타이거즈",
    backNumber: "31",
    position: "RP",
    hand: "RHP",
    birth: "Jun 26 1992",
  },
  {
    name: "성영탁",
    team: "KIA 타이거즈",
    backNumber: "65",
    position: "RP",
    hand: "RHP",
    birth: "Jul 28 2004",
  },
  {
    name: "양현종",
    team: "KIA 타이거즈",
    backNumber: "54",
    position: "SP",
    hand: "LHP",
    birth: "Mar 1 1988",
  },
  {
    name: "양수호",
    team: "KIA 타이거즈",
    backNumber: "59",
    position: "RP",
    hand: "RHP",
    birth: "Sep 9 2006",
  },
  {
    name: "유승철",
    team: "KIA 타이거즈",
    backNumber: "50",
    position: "RP",
    hand: "RHP",
    birth: "Mar 2 1998",
  },
  {
    name: "윤중현",
    team: "KIA 타이거즈",
    backNumber: "19",
    position: "RP",
    hand: "RHP",
    birth: "Apr 25 1995",
  },
  {
    name: "윤영철",
    team: "KIA 타이거즈",
    backNumber: "13",
    position: "SP",
    hand: "LHP",
    birth: "Apr 20 2004",
  },
  {
    name: "유지성",
    team: "KIA 타이거즈",
    backNumber: "4",
    position: "RP",
    hand: "LHP",
    birth: "Nov 15 2000",
  },
  {
    name: "한준수",
    team: "KIA 타이거즈",
    backNumber: "55",
    position: "C",
    hand: "LHH",
    birth: "Feb 13 1999",
  },
  {
    name: "한승택",
    team: "KIA 타이거즈",
    backNumber: "26",
    position: "C",
    hand: "RHH",
    birth: "Jun 21 1994",
  },
  {
    name: "주효상",
    team: "KIA 타이거즈",
    backNumber: "22",
    position: "C",
    hand: "LHH",
    birth: "Nov 11 1997",
  },
  {
    name: "김태곤",
    team: "KIA 타이거즈",
    backNumber: "42",
    position: "C",
    hand: "RHH",
    birth: "Dec 30 1989",
  },
  {
    name: "이상준",
    team: "KIA 타이거즈",
    backNumber: "44",
    position: "C",
    hand: "RHH",
    birth: "Dec 13 2005",
  },
  {
    name: "변우혁",
    team: "KIA 타이거즈",
    backNumber: "29",
    position: "1B",
    hand: "RHH",
    birth: "Mar 18 2000",
  },
  {
    name: "최정용",
    team: "KIA 타이거즈",
    backNumber: "23",
    position: "2B",
    hand: "LHH",
    birth: "Oct 24 1996",
  },
  {
    name: "홍종표",
    team: "KIA 타이거즈",
    backNumber: "6",
    position: "2B",
    hand: "LHH",
    birth: "May 2 2000",
  },
  {
    name: "황대인",
    team: "KIA 타이거즈",
    backNumber: "52",
    position: "IF",
    hand: "RHH",
    birth: "Feb 10 1996",
  },
  {
    name: "정해원",
    team: "KIA 타이거즈",
    backNumber: "64",
    position: "IF",
    hand: "RHH",
    birth: "May 21 2004",
  },
  {
    name: "김도영",
    team: "KIA 타이거즈",
    backNumber: "5",
    position: "3B",
    hand: "RHH",
    birth: "Oct 2 2003",
  },
  {
    name: "김두현",
    team: "KIA 타이거즈",
    backNumber: "2",
    position: "IF",
    hand: "RHH",
    birth: "Apr 25 2003",
  },
  {
    name: "김규성",
    team: "KIA 타이거즈",
    backNumber: "14",
    position: "SS",
    hand: "LHH",
    birth: "Mar 8 1997",
  },
  {
    name: "김선빈",
    team: "KIA 타이거즈",
    backNumber: "3",
    position: "2B",
    hand: "RHH",
    birth: "Dec 18 1989",
  },
  {
    name: "오선우",
    team: "KIA 타이거즈",
    backNumber: "56",
    position: "IF",
    hand: "LHH",
    birth: "Dec 13 1996",
  },
  {
    name: "박찬호",
    team: "KIA 타이거즈",
    backNumber: "1",
    position: "SS",
    hand: "RHH",
    birth: "Jun 5 1995",
  },
  {
    name: "박민",
    team: "KIA 타이거즈",
    backNumber: "2",
    position: "IF",
    hand: "RHH",
    birth: "Jun 5 2001",
  },
  {
    name: "서건창",
    team: "KIA 타이거즈",
    backNumber: "58",
    position: "2B",
    hand: "LHH",
    birth: "Aug 22 1989",
  },
  {
    name: "패트릭 위즈덤",
    team: "KIA 타이거즈",
    backNumber: "45",
    position: "IF",
    hand: "RHH",
    birth: "Aug 27 1991",
  },
  {
    name: "윤도현",
    team: "KIA 타이거즈",
    backNumber: "9",
    position: "2B",
    hand: "RHH",
    birth: "May 7 2003",
  },
  {
    name: "최형우",
    team: "KIA 타이거즈",
    backNumber: "34",
    position: "LF",
    hand: "LHH",
    birth: "Dec 16 1983",
  },
  {
    name: "최원준",
    team: "KIA 타이거즈",
    backNumber: "16",
    position: "RF",
    hand: "LHH",
    birth: "Mar 23 1997",
  },
  {
    name: "김호령",
    team: "KIA 타이거즈",
    backNumber: "27",
    position: "CF",
    hand: "RHH",
    birth: "Apr 30 1992",
  },
  {
    name: "김석환",
    team: "KIA 타이거즈",
    backNumber: "35",
    position: "OF",
    hand: "LHH",
    birth: "Feb 28 1999",
  },
  {
    name: "고종욱",
    team: "KIA 타이거즈",
    backNumber: "57",
    position: "OF",
    hand: "LHH",
    birth: "Jan 11 1989",
  },
  {
    name: "이창진",
    team: "KIA 타이거즈",
    backNumber: "8",
    position: "OF",
    hand: "RHH",
    birth: "Mar 4 1991",
  },
  {
    name: "이우성",
    team: "KIA 타이거즈",
    backNumber: "25",
    position: "LF",
    hand: "RHH",
    birth: "Jul 17 1994",
  },
  {
    name: "나성범",
    team: "KIA 타이거즈",
    backNumber: "47",
    position: "RF",
    hand: "LHH",
    birth: "Oct 3 1989",
  },
  {
    name: "박재현",
    team: "KIA 타이거즈",
    backNumber: "36",
    position: "OF",
    hand: "LHH",
    birth: "Dec 8 2006",
  },
  {
    name: "박정우",
    team: "KIA 타이거즈",
    backNumber: "15",
    position: "LF",
    hand: "LHH",
    birth: "Feb 1 1998",
  },
  {
    name: "라울 알칸타라",
    team: "키움 히어로즈",
    backNumber: "54",
    position: "SP/RP",
    hand: "RHP",
    birth: "Dec 4 1992",
  },
  {
    name: "조영건",
    team: "키움 히어로즈",
    backNumber: "20",
    position: "SP",
    hand: "RHP",
    birth: "Feb 4 1999",
  },
  {
    name: "정세영",
    team: "키움 히어로즈",
    backNumber: "77",
    position: "RP",
    hand: "LHP",
    birth: "Sep 23 2006",
  },
  {
    name: "하영민",
    team: "키움 히어로즈",
    backNumber: "50",
    position: "SP",
    hand: "RHP",
    birth: "May 7 1995",
  },
  {
    name: "장필준",
    team: "키움 히어로즈",
    backNumber: "18",
    position: "RP",
    hand: "RHP",
    birth: "Apr 8 1988",
  },
  {
    name: "전준우",
    team: "키움 히어로즈",
    backNumber: "62",
    position: "SP/RP",
    hand: "RHP",
    birth: "May 7 2005",
  },
  {
    name: "주승우",
    team: "키움 히어로즈",
    backNumber: "30",
    position: "CP",
    hand: "RHP",
    birth: "Jan 30 2000",
  },
  {
    name: "정현우",
    team: "키움 히어로즈",
    backNumber: "13",
    position: "SP/RP",
    hand: "LHP",
    birth: "Apr 13 2006",
  },
  {
    name: "김동규",
    team: "키움 히어로즈",
    backNumber: "99",
    position: "RP",
    hand: "RHP",
    birth: "Jul 9 2004",
  },
  {
    name: "김인범",
    team: "키움 히어로즈",
    backNumber: "67",
    position: "RP",
    hand: "RHP",
    birth: "Jan 12 2000",
  },
  {
    name: "김서준",
    team: "키움 히어로즈",
    backNumber: "59",
    position: "RP",
    hand: "RHP",
    birth: "Dec 22 2006",
  },
  {
    name: "김선기",
    team: "키움 히어로즈",
    backNumber: "49",
    position: "SP",
    hand: "RHP",
    birth: "Sep 1 1991",
  },
  {
    name: "김성민",
    team: "키움 히어로즈",
    backNumber: "8",
    position: "RP",
    hand: "LHP",
    birth: "Apr 26 1994",
  },
  {
    name: "김연주",
    team: "키움 히어로즈",
    backNumber: "68",
    position: "SP/RP",
    hand: "RHP",
    birth: "Feb 27 2004",
  },
  {
    name: "김윤하",
    team: "키움 히어로즈",
    backNumber: "19",
    position: "SP",
    hand: "RHP",
    birth: "Mar 7 2005",
  },
  {
    name: "이종민",
    team: "키움 히어로즈",
    backNumber: "45",
    position: "RP",
    hand: "LHP",
    birth: "Jun 4 2001",
  },
  {
    name: "이준우",
    team: "키움 히어로즈",
    backNumber: "21",
    position: "RP",
    hand: "RHP",
    birth: "Mar 2 2001",
  },
  {
    name: "이강준",
    team: "키움 히어로즈",
    backNumber: "11",
    position: "RP",
    hand: "RHP",
    birth: "Dec 14 2001",
  },
  {
    name: "임진욱",
    team: "키움 히어로즈",
    backNumber: "82",
    position: "RP",
    hand: "RHP",
    birth: "Apr 23 2006",
  },
  {
    name: "오석주",
    team: "키움 히어로즈",
    backNumber: "31",
    position: "RP",
    hand: "RHP",
    birth: "Apr 14 1998",
  },
  {
    name: "박범준",
    team: "키움 히어로즈",
    backNumber: "45",
    position: "RP",
    hand: "RHP",
    birth: "May 28 2004",
  },
  {
    name: "박정훈",
    team: "키움 히어로즈",
    backNumber: "94",
    position: "RP",
    hand: "LHP",
    birth: "Mar 23 2006",
  },
  {
    name: "박주성",
    team: "키움 히어로즈",
    backNumber: "0",
    position: "RP",
    hand: "RHP",
    birth: "Nov 9 2000",
  },
  {
    name: "박윤성",
    team: "키움 히어로즈",
    backNumber: "35",
    position: "RP",
    hand: "RHP",
    birth: "Feb 8 2004",
  },
  {
    name: "손힘찬",
    team: "키움 히어로즈",
    backNumber: "37",
    position: "RP",
    hand: "RHP",
    birth: "Jul 17 2002",
  },
  {
    name: "손현기",
    team: "키움 히어로즈",
    backNumber: "63",
    position: "RP",
    hand: "LHP",
    birth: "Oct 22 2005",
  },
  {
    name: "웰스 라클란",
    team: "키움 히어로즈",
    backNumber: "48",
    position: "RP",
    hand: "LHP",
    birth: "Feb 27 1997",
  },
  {
    name: "원종현",
    team: "키움 히어로즈",
    backNumber: "46",
    position: "RP",
    hand: "RHP",
    birth: "Jul 31 1987",
  },
  {
    name: "양지율",
    team: "키움 히어로즈",
    backNumber: "55",
    position: "RP",
    hand: "RHP",
    birth: "Dec 16 1998",
  },
  {
    name: "윤현",
    team: "키움 히어로즈",
    backNumber: "96",
    position: "SP/RP",
    hand: "RHP",
    birth: "Oct 20 2006",
  },
  {
    name: "윤석원",
    team: "키움 히어로즈",
    backNumber: "95",
    position: "RP",
    hand: "LHP",
    birth: "Jul 4 2003",
  },
  {
    name: "김동현",
    team: "키움 히어로즈",
    backNumber: "47",
    position: "C",
    hand: "RHH",
    birth: "Jul 15 2004",
  },
  {
    name: "김건희",
    team: "키움 히어로즈",
    backNumber: "12",
    position: "C",
    hand: "RHH",
    birth: "Nov 7 2004",
  },
  {
    name: "김재현",
    team: "키움 히어로즈",
    backNumber: "32",
    position: "C",
    hand: "RHH",
    birth: "Mar 18 1993",
  },
  {
    name: "박성빈",
    team: "키움 히어로즈",
    backNumber: "56",
    position: "C",
    hand: "RHH",
    birth: "Apr 21 2004",
  },
  {
    name: "최주환",
    team: "키움 히어로즈",
    backNumber: "53",
    position: "1B",
    hand: "LHH",
    birth: "Feb 28 1988",
  },
  {
    name: "어준서",
    team: "키움 히어로즈",
    backNumber: "92",
    position: "IF",
    hand: "LHH",
    birth: "Nov 27 2006",
  },
  {
    name: "권혁빈",
    team: "키움 히어로즈",
    backNumber: "71",
    position: "IF",
    hand: "RHH",
    birth: "Nov 4 2005",
  },
  {
    name: "전태현",
    team: "키움 히어로즈",
    backNumber: "97",
    position: "IF",
    hand: "LHH",
    birth: "Mar 2 2006",
  },
  {
    name: "강진성",
    team: "키움 히어로즈",
    backNumber: "27",
    position: "IF",
    hand: "RHH",
    birth: "Oct 19 1993",
  },
  {
    name: "김병휘",
    team: "키움 히어로즈",
    backNumber: "23",
    position: "SS",
    hand: "RHH",
    birth: "Feb 16 2001",
  },
  {
    name: "김태진",
    team: "키움 히어로즈",
    backNumber: "1",
    position: "2B",
    hand: "LHH",
    birth: "Oct 7 1995",
  },
  {
    name: "김웅빈",
    team: "키움 히어로즈",
    backNumber: "10",
    position: "IF",
    hand: "LHH",
    birth: "Feb 9 1996",
  },
  {
    name: "고영우",
    team: "키움 히어로즈",
    backNumber: "44",
    position: "3B",
    hand: "RHH",
    birth: "Jun 21 2001",
  },
  {
    name: "이재상",
    team: "키움 히어로즈",
    backNumber: "5",
    position: "IF",
    hand: "RHH",
    birth: "Apr 17 2005",
  },
  {
    name: "이주형",
    team: "키움 히어로즈",
    backNumber: "58",
    position: "IF",
    hand: "LHH",
    birth: "Jul 5 2002",
  },
  {
    name: "이승원",
    team: "키움 히어로즈",
    backNumber: "22",
    position: "SS",
    hand: "RHH",
    birth: "Jul 2 2004",
  },
  {
    name: "이원석",
    team: "키움 히어로즈",
    backNumber: "17",
    position: "IF",
    hand: "RHH",
    birth: "Oct 21 1986",
  },
  {
    name: "오선진",
    team: "키움 히어로즈",
    backNumber: "60",
    position: "SS",
    hand: "RHH",
    birth: "Jul 7 1989",
  },
  {
    name: "서유신",
    team: "키움 히어로즈",
    backNumber: "98",
    position: "IF",
    hand: "RHH",
    birth: "Aug 17 2000",
  },
  {
    name: "송지후",
    team: "키움 히어로즈",
    backNumber: "86",
    position: "IF",
    hand: "RHH",
    birth: "Jan 8 2005",
  },
  {
    name: "송성문",
    team: "키움 히어로즈",
    backNumber: "24",
    position: "3B",
    hand: "LHH",
    birth: "Aug 29 1996",
  },
  {
    name: "양현종",
    team: "키움 히어로즈",
    backNumber: "70",
    position: "IF",
    hand: "RHH",
    birth: "Aug 15 2006",
  },
  {
    name: "여동욱",
    team: "키움 히어로즈",
    backNumber: "93",
    position: "IF",
    hand: "RHH",
    birth: "Nov 10 2005",
  },
  {
    name: "변상권",
    team: "키움 히어로즈",
    backNumber: "9",
    position: "LF",
    hand: "LHH",
    birth: "Apr 4 1997",
  },
  {
    name: "루벤 카디네스",
    team: "키움 히어로즈",
    backNumber: "4",
    position: "RF",
    hand: "RHH",
    birth: "Oct 10 1997",
  },
  {
    name: "스톤 가렛",
    team: "키움 히어로즈",
    backNumber: "26",
    position: "OF",
    hand: "RHH",
    birth: "Nov 22 1995",
  },
  {
    name: "임지열",
    team: "키움 히어로즈",
    backNumber: "29",
    position: "LF",
    hand: "RHH",
    birth: "Aug 22 1995",
  },
  {
    name: "장재영",
    team: "키움 히어로즈",
    backNumber: "23",
    position: "RF",
    hand: "RHH",
    birth: "May 10 2002",
  },
  {
    name: "주성원",
    team: "키움 히어로즈",
    backNumber: "25",
    position: "RF",
    hand: "RHH",
    birth: "Aug 30 2000",
  },
  {
    name: "김동엽",
    team: "키움 히어로즈",
    backNumber: "38",
    position: "OF",
    hand: "RHH",
    birth: "Jul 24 1990",
  },
  {
    name: "이형준",
    team: "키움 히어로즈",
    backNumber: "36",
    position: "LF",
    hand: "RHH",
    birth: "Jun 7 1989",
  },
  {
    name: "이주형",
    team: "키움 히어로즈",
    backNumber: "2",
    position: "CF",
    hand: "LHH",
    birth: "Apr 2 2001",
  },
  {
    name: "이용규",
    team: "키움 히어로즈",
    backNumber: "15",
    position: "OF",
    hand: "LHH",
    birth: "Aug 26 1985",
  },
  {
    name: "임병욱",
    team: "키움 히어로즈",
    backNumber: "6",
    position: "CF",
    hand: "LHH",
    birth: "Sep 30 1995",
  },
  {
    name: "박주홍",
    team: "키움 히어로즈",
    backNumber: "57",
    position: "LF",
    hand: "LHH",
    birth: "Apr 16 2001",
  },
  {
    name: "박수종",
    team: "키움 히어로즈",
    backNumber: "14",
    position: "CF",
    hand: "RHH",
    birth: "Feb 25 1999",
  },
  {
    name: "야시엘 푸이그",
    team: "키움 히어로즈",
    backNumber: "66",
    position: "LF",
    hand: "RHH",
    birth: "Dec 7 1990",
  },
  {
    name: "원성준",
    team: "키움 히어로즈",
    backNumber: "33",
    position: "RF",
    hand: "LHH",
    birth: "Mar 31 2000",
  },
  {
    name: "배재성",
    team: "KT 위즈",
    backNumber: "19",
    position: "RP",
    hand: "RHP",
    birth: "Sep 29 1996",
  },
  {
    name: "최동환",
    team: "KT 위즈",
    backNumber: "16",
    position: "RP",
    hand: "RHP",
    birth: "Sep 19 1989",
  },
  {
    name: "최용준",
    team: "KT 위즈",
    backNumber: "92",
    position: "RP",
    hand: "RHP",
    birth: "Dec 19 2001",
  },
  {
    name: "윌리엄 쿠에바스",
    team: "KT 위즈",
    backNumber: "32",
    position: "SP",
    hand: "RHP",
    birth: "Oct 14 1990",
  },
  {
    name: "한차현",
    team: "KT 위즈",
    backNumber: "59",
    position: "RP",
    hand: "RHP",
    birth: "Nov 30 1998",
  },
  {
    name: "전용주",
    team: "KT 위즈",
    backNumber: "29",
    position: "RP",
    hand: "LHP",
    birth: "Feb 12 2000",
  },
  {
    name: "엔마누엘 데 헤이수스",
    team: "KT 위즈",
    backNumber: "65",
    position: "SP",
    hand: "LHP",
    birth: "Dec 10 1996",
  },
  {
    name: "조이현",
    team: "KT 위즈",
    backNumber: "54",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jun 27 1995",
  },
  {
    name: "주권",
    team: "KT 위즈",
    backNumber: "38",
    position: "RP",
    hand: "RHP",
    birth: "May 31 1995",
  },
  {
    name: "강건",
    team: "KT 위즈",
    backNumber: "99",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jul 12 2004",
  },
  {
    name: "김동현",
    team: "KT 위즈",
    backNumber: "40",
    position: "RP",
    hand: "RHP",
    birth: "Jan 21 2006",
  },
  {
    name: "김재원",
    team: "KT 위즈",
    backNumber: "43",
    position: "RP",
    hand: "RHP",
    birth: "Aug 21 2006",
  },
  {
    name: "김주완",
    team: "KT 위즈",
    backNumber: "98",
    position: "RP",
    hand: "LHP",
    birth: "Oct 7 1999",
  },
  {
    name: "김민수",
    team: "KT 위즈",
    backNumber: "26",
    position: "RP",
    hand: "RHP",
    birth: "Jul 24 1992",
  },
  {
    name: "고영표",
    team: "KT 위즈",
    backNumber: "1",
    position: "SP",
    hand: "RHP",
    birth: "Sep 16 1991",
  },
  {
    name: "이재호",
    team: "KT 위즈",
    backNumber: "17",
    position: "RP",
    hand: "RHP",
    birth: "Nov 23 1998",
  },
  {
    name: "이현민",
    team: "KT 위즈",
    backNumber: "49",
    position: "RP",
    hand: "RHP",
    birth: "Oct 13 2001",
  },
  {
    name: "이정현",
    team: "KT 위즈",
    backNumber: "21",
    position: "RP",
    hand: "RHP",
    birth: "Dec 5 1997",
  },
  {
    name: "이상동",
    team: "KT 위즈",
    backNumber: "37",
    position: "RP",
    hand: "RHP",
    birth: "Nov 24 1995",
  },
  {
    name: "이선우",
    team: "KT 위즈",
    backNumber: "61",
    position: "RP",
    hand: "RHP",
    birth: "Sep 19 2000",
  },
  {
    name: "이태규",
    team: "KT 위즈",
    backNumber: "45",
    position: "RP",
    hand: "RHP",
    birth: "Feb 21 2000",
  },
  {
    name: "몬 용익",
    team: "KT 위즈",
    backNumber: "18",
    position: "RP",
    hand: "RHP",
    birth: "Feb 4 1995",
  },
  {
    name: "오원세",
    team: "KT 위즈",
    backNumber: "47",
    position: "SP",
    hand: "LHP",
    birth: "Apr 23 2001",
  },
  {
    name: "박건우",
    team: "KT 위즈",
    backNumber: "46",
    position: "RP",
    hand: "RHP",
    birth: "Nov 28 2006",
  },
  {
    name: "박영현",
    team: "KT 위즈",
    backNumber: "60",
    position: "CP",
    hand: "RHP",
    birth: "Oct 11 2003",
  },
  {
    name: "성재헌",
    team: "KT 위즈",
    backNumber: "15",
    position: "RP",
    hand: "LHP",
    birth: "Dec 22 1997",
  },
  {
    name: "소형준",
    team: "KT 위즈",
    backNumber: "30",
    position: "SP",
    hand: "RHP",
    birth: "Sep 16 2001",
  },
  {
    name: "손동현",
    team: "KT 위즈",
    backNumber: "41",
    position: "RP",
    hand: "RHP",
    birth: "Jan 23 2001",
  },
  {
    name: "원상현",
    team: "KT 위즈",
    backNumber: "63",
    position: "RP",
    hand: "RHP",
    birth: "Oct 16 2004",
  },
  {
    name: "우규민",
    team: "KT 위즈",
    backNumber: "12",
    position: "RP",
    hand: "RHP",
    birth: "Jan 21 1985",
  },
  {
    name: "조대현",
    team: "KT 위즈",
    backNumber: "42",
    position: "C",
    hand: "RHH",
    birth: "Aug 6 1999",
  },
  {
    name: "장성우",
    team: "KT 위즈",
    backNumber: "22",
    position: "C",
    hand: "RHH",
    birth: "Jan 17 1990",
  },
  {
    name: "강백호",
    team: "KT 위즈",
    backNumber: "50",
    position: "C",
    hand: "LHH",
    birth: "Jul 29 1999",
  },
  {
    name: "강현우",
    team: "KT 위즈",
    backNumber: "55",
    position: "C",
    hand: "RHH",
    birth: "Apr 13 2001",
  },
  {
    name: "김준태",
    team: "KT 위즈",
    backNumber: "44",
    position: "C",
    hand: "LHH",
    birth: "Jul 31 1994",
  },
  {
    name: "김민석",
    team: "KT 위즈",
    backNumber: "97",
    position: "C",
    hand: "RHH",
    birth: "Jul 22 2005",
  },
  {
    name: "천성호",
    team: "KT 위즈",
    backNumber: "14",
    position: "LF",
    hand: "LHH",
    birth: "Oct 30 1997",
  },
  {
    name: "허가람",
    team: "KT 위즈",
    backNumber: "13",
    position: "3B",
    hand: "RHH",
    birth: "Aug 26 1990",
  },
  {
    name: "황재균",
    team: "KT 위즈",
    backNumber: "10",
    position: "3B",
    hand: "RHH",
    birth: "Jul 28 1987",
  },
  {
    name: "장준원",
    team: "KT 위즈",
    backNumber: "56",
    position: "SS",
    hand: "RHH",
    birth: "Nov 21 1995",
  },
  {
    name: "강민성",
    team: "KT 위즈",
    backNumber: "5",
    position: "IF",
    hand: "RHH",
    birth: "Dec 8 1999",
  },
  {
    name: "김상수",
    team: "KT 위즈",
    backNumber: "7",
    position: "2B",
    hand: "RHH",
    birth: "Mar 23 1990",
  },
  {
    name: "권동진",
    team: "KT 위즈",
    backNumber: "52",
    position: "IF",
    hand: "LHH",
    birth: "Sep 12 1998",
  },
  {
    name: "이호연",
    team: "KT 위즈",
    backNumber: "34",
    position: "2B",
    hand: "LHH",
    birth: "Jun 3 1995",
  },
  {
    name: "문상철",
    team: "KT 위즈",
    backNumber: "24",
    position: "1B",
    hand: "RHH",
    birth: "Apr 6 1991",
  },
  {
    name: "오재일",
    team: "KT 위즈",
    backNumber: "36",
    position: "IF",
    hand: "LHH",
    birth: "Oct 29 1986",
  },
  {
    name: "오서진",
    team: "KT 위즈",
    backNumber: "25",
    position: "IF",
    hand: "RHH",
    birth: "Feb 22 2006",
  },
  {
    name: "윤준혁",
    team: "KT 위즈",
    backNumber: "35",
    position: "3B",
    hand: "RHH",
    birth: "Jul 26 2001",
  },
  {
    name: "안현민",
    team: "KT 위즈",
    backNumber: "23",
    position: "LF",
    hand: "RHH",
    birth: "Aug 22 2003",
  },
  {
    name: "안치홍",
    team: "KT 위즈",
    backNumber: "8",
    position: "OF",
    hand: "LHH",
    birth: "May 29 1998",
  },
  {
    name: "배정대",
    team: "KT 위즈",
    backNumber: "27",
    position: "CF",
    hand: "RHH",
    birth: "Jun 12 1995",
  },
  {
    name: "최성민",
    team: "KT 위즈",
    backNumber: "31",
    position: "OF",
    hand: "LHH",
    birth: "Jul 5 2002",
  },
  {
    name: "장진혁",
    team: "KT 위즈",
    backNumber: "51",
    position: "CF",
    hand: "LHH",
    birth: "Sep 30 1993",
  },
  {
    name: "멜 로하스 주니어",
    team: "KT 위즈",
    backNumber: "3",
    position: "RF",
    hand: "SHH",
    birth: "May 24 1990",
  },
  {
    name: "김병준",
    team: "KT 위즈",
    backNumber: "57",
    position: "RF",
    hand: "LHH",
    birth: "Jul 3 2003",
  },
  {
    name: "김건형",
    team: "KT 위즈",
    backNumber: "0",
    position: "OF",
    hand: "LHH",
    birth: "Jul 12 1996",
  },
  {
    name: "김민혁",
    team: "KT 위즈",
    backNumber: "53",
    position: "LF",
    hand: "LHH",
    birth: "Nov 21 1995",
  },
  {
    name: "이정범",
    team: "KT 위즈",
    backNumber: "33",
    position: "OF",
    hand: "LHH",
    birth: "Dec 7 1994",
  },
  {
    name: "박민석",
    team: "KT 위즈",
    backNumber: "104",
    position: "OF",
    hand: "RHH",
    birth: "Jul 27 2006",
  },
  {
    name: "유준규",
    team: "KT 위즈",
    backNumber: "67",
    position: "OF",
    hand: "LHH",
    birth: "Aug 16 2002",
  },
  {
    name: "송민섭",
    team: "KT 위즈",
    backNumber: "28",
    position: "RF",
    hand: "RHH",
    birth: "Aug 2 1991",
  },
  {
    name: "앤드류 앤더슨",
    team: "SSG 랜더스",
    backNumber: "33",
    position: "SP",
    hand: "RHP",
    birth: "Mar 22 1994",
  },
  {
    name: "백승건",
    team: "SSG 랜더스",
    backNumber: "11",
    position: "RP",
    hand: "LHP",
    birth: "Oct 29 2000",
  },
  {
    name: "최현석",
    team: "SSG 랜더스",
    backNumber: "40",
    position: "RP",
    hand: "RHP",
    birth: "Oct 16 2003",
  },
  {
    name: "최민준",
    team: "SSG 랜더스",
    backNumber: "30",
    position: "RP",
    hand: "RHP",
    birth: "Jun 11 1999",
  },
  {
    name: "천범석",
    team: "SSG 랜더스",
    backNumber: "90",
    position: "RP",
    hand: "RHP",
    birth: "Mar 6 2006",
  },
  {
    name: "정동윤",
    team: "SSG 랜더스",
    backNumber: "51",
    position: "RP",
    hand: "RHP",
    birth: "Oct 22 1997",
  },
  {
    name: "한두솔",
    team: "SSG 랜더스",
    backNumber: "34",
    position: "RP",
    hand: "LHP",
    birth: "Jan 15 1997",
  },
  {
    name: "장지현",
    team: "SSG 랜더스",
    backNumber: "21",
    position: "RP",
    hand: "RHP",
    birth: "Dec 6 1998",
  },
  {
    name: "전영준",
    team: "SSG 랜더스",
    backNumber: "65",
    position: "SP/RP",
    hand: "RHP",
    birth: "Apr 16 2002",
  },
  {
    name: "조병현",
    team: "SSG 랜더스",
    backNumber: "19",
    position: "CP",
    hand: "RHP",
    birth: "May 8 2002",
  },
  {
    name: "김건우",
    team: "SSG 랜더스",
    backNumber: "39",
    position: "SP/RP",
    hand: "LHP",
    birth: "Jul 12 2002",
  },
  {
    name: "김광현",
    team: "SSG 랜더스",
    backNumber: "29",
    position: "SP",
    hand: "LHP",
    birth: "Jul 22 1988",
  },
  {
    name: "김민",
    team: "SSG 랜더스",
    backNumber: "41",
    position: "RP",
    hand: "RHP",
    birth: "Apr 14 1999",
  },
  {
    name: "김택형",
    team: "SSG 랜더스",
    backNumber: "43",
    position: "RP",
    hand: "LHP",
    birth: "Oct 10 1996",
  },
  {
    name: "이근욱",
    team: "SSG 랜더스",
    backNumber: "16",
    position: "RP",
    hand: "RHP",
    birth: "Feb 13 1995",
  },
  {
    name: "이로운",
    team: "SSG 랜더스",
    backNumber: "92",
    position: "RP",
    hand: "RHP",
    birth: "Sep 11 2004",
  },
  {
    name: "문승원",
    team: "SSG 랜더스",
    backNumber: "42",
    position: "SP",
    hand: "RHP",
    birth: "Nov 28 1989",
  },
  {
    name: "노경은",
    team: "SSG 랜더스",
    backNumber: "38",
    position: "RP",
    hand: "RHP",
    birth: "Mar 11 1984",
  },
  {
    name: "박종훈",
    team: "SSG 랜더스",
    backNumber: "50",
    position: "SP/RP",
    hand: "RHP",
    birth: "Aug 13 1991",
  },
  {
    name: "박기호",
    team: "SSG 랜더스",
    backNumber: "66",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jul 26 2005",
  },
  {
    name: "박성빈",
    team: "SSG 랜더스",
    backNumber: "00",
    position: "RP",
    hand: "RHP",
    birth: "Dec 29 2003",
  },
  {
    name: "박시후",
    team: "SSG 랜더스",
    backNumber: "57",
    position: "RP",
    hand: "LHP",
    birth: "May 10 2001",
  },
  {
    name: "서진용",
    team: "SSG 랜더스",
    backNumber: "22",
    position: "RP",
    hand: "RHP",
    birth: "Oct 2 1992",
  },
  {
    name: "신헌민",
    team: "SSG 랜더스",
    backNumber: "33",
    position: "RP",
    hand: "RHP",
    birth: "Jul 19 2002",
  },
  {
    name: "신지환",
    team: "SSG 랜더스",
    backNumber: "60",
    position: "RP",
    hand: "LHP",
    birth: "Apr 17 2006",
  },
  {
    name: "송영진",
    team: "SSG 랜더스",
    backNumber: "28",
    position: "SP",
    hand: "RHP",
    birth: "May 28 2004",
  },
  {
    name: "미치 화이트",
    team: "SSG 랜더스",
    backNumber: "55",
    position: "SP",
    hand: "RHP",
    birth: "Dec 28 1994",
  },
  {
    name: "최형우",
    team: "SSG 랜더스",
    backNumber: "20",
    position: "C",
    hand: "RHH",
    birth: "Apr 4 2002",
  },
  {
    name: "김규민",
    team: "SSG 랜더스",
    backNumber: "61",
    position: "C",
    hand: "LHH",
    birth: "Aug 23 2002",
  },
  {
    name: "김민식",
    team: "SSG 랜더스",
    backNumber: "24",
    position: "C",
    hand: "LHH",
    birth: "Jun 28 1989",
  },
  {
    name: "이재영",
    team: "SSG 랜더스",
    backNumber: "59",
    position: "C",
    hand: "RHH",
    birth: "Feb 27 1986",
  },
  {
    name: "이율예",
    team: "SSG 랜더스",
    backNumber: "32",
    position: "C",
    hand: "RHH",
    birth: "Nov 21 2006",
  },
  {
    name: "신범수",
    team: "SSG 랜더스",
    backNumber: "25",
    position: "C",
    hand: "LHH",
    birth: "Jan 25 1998",
  },
  {
    name: "안상현",
    team: "SSG 랜더스",
    backNumber: "10",
    position: "SS",
    hand: "RHH",
    birth: "Jan 27 1997",
  },
  {
    name: "최정",
    team: "SSG 랜더스",
    backNumber: "14",
    position: "3B",
    hand: "RHH",
    birth: "Feb 28 1987",
  },
  {
    name: "최준우",
    team: "SSG 랜더스",
    backNumber: "7",
    position: "IF",
    hand: "LHH",
    birth: "Mar 25 1999",
  },
  {
    name: "최윤석",
    team: "SSG 랜더스",
    backNumber: "94",
    position: "IF",
    hand: "RHH",
    birth: "Apr 25 2006",
  },
  {
    name: "홍대인",
    team: "SSG 랜더스",
    backNumber: "97",
    position: "IF",
    hand: "LHH",
    birth: "Nov 23 2001",
  },
  {
    name: "현원회",
    team: "SSG 랜더스",
    backNumber: "8",
    position: "IF",
    hand: "RHH",
    birth: "Jul 8 2001",
  },
  {
    name: "정준재",
    team: "SSG 랜더스",
    backNumber: "3",
    position: "2B",
    hand: "LHH",
    birth: "Jan 3 2003",
  },
  {
    name: "김찬형",
    team: "SSG 랜더스",
    backNumber: "5",
    position: "IF",
    hand: "RHH",
    birth: "Dec 29 1997",
  },
  {
    name: "김성민",
    team: "SSG 랜더스",
    backNumber: "56",
    position: "IF",
    hand: "RHH",
    birth: "Apr 30 2001",
  },
  {
    name: "김수윤",
    team: "SSG 랜더스",
    backNumber: "4",
    position: "IF",
    hand: "RHH",
    birth: "Jul 16 1998",
  },
  {
    name: "김성현",
    team: "SSG 랜더스",
    backNumber: "6",
    position: "3B",
    hand: "RHH",
    birth: "Mar 9 1987",
  },
  {
    name: "김태윤",
    team: "SSG 랜더스",
    backNumber: "36",
    position: "IF",
    hand: "LHH",
    birth: "Feb 28 2003",
  },
  {
    name: "고명준",
    team: "SSG 랜더스",
    backNumber: "18",
    position: "1B",
    hand: "RHH",
    birth: "Jul 8 2002",
  },
  {
    name: "박지환",
    team: "SSG 랜더스",
    backNumber: "1",
    position: "3B",
    hand: "RHH",
    birth: "Jul 12 2005",
  },
  {
    name: "박성한",
    team: "SSG 랜더스",
    backNumber: "2",
    position: "SS",
    hand: "LHH",
    birth: "Mar 30 1998",
  },
  {
    name: "서재응",
    team: "SSG 랜더스",
    backNumber: "52",
    position: "IF",
    hand: "RHH",
    birth: "Jan 20 1999",
  },
  {
    name: "채현우",
    team: "SSG 랜더스",
    backNumber: "15",
    position: "OF",
    hand: "RHH",
    birth: "Nov 21 1995",
  },
  {
    name: "최지훈",
    team: "SSG 랜더스",
    backNumber: "54",
    position: "CF",
    hand: "LHH",
    birth: "Jul 23 1997",
  },
  {
    name: "최민창",
    team: "SSG 랜더스",
    backNumber: "53",
    position: "OF",
    hand: "LHH",
    birth: "Apr 16 1996",
  },
  {
    name: "최상민",
    team: "SSG 랜더스",
    backNumber: "23",
    position: "RF",
    hand: "LHH",
    birth: "Aug 20 1999",
  },
  {
    name: "하재훈",
    team: "SSG 랜더스",
    backNumber: "13",
    position: "CF",
    hand: "RHH",
    birth: "Oct 29 1990",
  },
  {
    name: "한유섬",
    team: "SSG 랜더스",
    backNumber: "35",
    position: "RF",
    hand: "LHH",
    birth: "Aug 9 1989",
  },
  {
    name: "기예르모 헤레디아",
    team: "SSG 랜더스",
    backNumber: "27",
    position: "LF",
    hand: "RHH",
    birth: "Jan 31 1991",
  },
  {
    name: "정현승",
    team: "SSG 랜더스",
    backNumber: "17",
    position: "RF",
    hand: "LHH",
    birth: "Oct 24 2001",
  },
  {
    name: "김창평",
    team: "SSG 랜더스",
    backNumber: "64",
    position: "OF",
    hand: "LHH",
    birth: "Jun 14 2000",
  },
  {
    name: "김성욱",
    team: "SSG 랜더스",
    backNumber: "47",
    position: "CF",
    hand: "RHH",
    birth: "May 1 1993",
  },
  {
    name: "이정범",
    team: "SSG 랜더스",
    backNumber: "31",
    position: "OF",
    hand: "LHH",
    birth: "Apr 10 1998",
  },
  {
    name: "이승민",
    team: "SSG 랜더스",
    backNumber: "9",
    position: "OF",
    hand: "LHH",
    birth: "Jan 6 2005",
  },
  {
    name: "라이언 맥브룸",
    team: "SSG 랜더스",
    backNumber: "44",
    position: "OF",
    hand: "RHH",
    birth: "Apr 9 1992",
  },
  {
    name: "오태곤",
    team: "SSG 랜더스",
    backNumber: "37",
    position: "LF",
    hand: "RHH",
    birth: "Nov 18 1991",
  },
  {
    name: "박정빈",
    team: "SSG 랜더스",
    backNumber: "58",
    position: "OF",
    hand: "RHH",
    birth: "Jun 14 2002",
  },
  {
    name: "류효승",
    team: "SSG 랜더스",
    backNumber: "45",
    position: "OF",
    hand: "RHH",
    birth: "Jul 16 1996",
  },
  {
    name: "배찬승",
    team: "삼성 라이온즈",
    backNumber: "55",
    position: "RP",
    hand: "LHP",
    birth: "Jan 1 2006",
  },
  {
    name: "백정현",
    team: "삼성 라이온즈",
    backNumber: "29",
    position: "SP/RP",
    hand: "LHP",
    birth: "Jul 13 1987",
  },
  {
    name: "최충연",
    team: "삼성 라이온즈",
    backNumber: "51",
    position: "RP",
    hand: "RHP",
    birth: "Mar 5 1997",
  },
  {
    name: "최하늘",
    team: "삼성 라이온즈",
    backNumber: "37",
    position: "RP",
    hand: "RHP",
    birth: "Mar 26 1999",
  },
  {
    name: "최지원",
    team: "삼성 라이온즈",
    backNumber: "11",
    position: "RP",
    hand: "RHP",
    birth: "Mar 13 1998",
  },
  {
    name: "최성훈",
    team: "삼성 라이온즈",
    backNumber: "54",
    position: "RP",
    hand: "LHP",
    birth: "Oct 11 1989",
  },
  {
    name: "최원태",
    team: "삼성 라이온즈",
    backNumber: "3",
    position: "SP",
    hand: "RHP",
    birth: "Jan 7 1997",
  },
  {
    name: "가라비토 제르손",
    team: "삼성 라이온즈",
    backNumber: "60",
    position: "RP",
    hand: "RHP",
    birth: "Aug 19 1995",
  },
  {
    name: "권현우",
    team: "삼성 라이온즈",
    backNumber: "41",
    position: "RP",
    hand: "RHP",
    birth: "Mar 28 2006",
  },
  {
    name: "홍원표",
    team: "삼성 라이온즈",
    backNumber: "65",
    position: "RP",
    hand: "RHP",
    birth: "Mar 27 2001",
  },
  {
    name: "황동재",
    team: "삼성 라이온즈",
    backNumber: "61",
    position: "SP/RP",
    hand: "RHP",
    birth: "Nov 3 2001",
  },
  {
    name: "정민성",
    team: "삼성 라이온즈",
    backNumber: "49",
    position: "SP/RP",
    hand: "RHP",
    birth: "May 9 2005",
  },
  {
    name: "김대호",
    team: "삼성 라이온즈",
    backNumber: "44",
    position: "SP/RP",
    hand: "RHP",
    birth: "Oct 15 2001",
  },
  {
    name: "김대우",
    team: "삼성 라이온즈",
    backNumber: "17",
    position: "RP",
    hand: "RHP",
    birth: "Nov 21 1988",
  },
  {
    name: "김재윤",
    team: "삼성 라이온즈",
    backNumber: "62",
    position: "CP",
    hand: "RHP",
    birth: "Sep 16 1990",
  },
  {
    name: "김무신",
    team: "삼성 라이온즈",
    backNumber: "48",
    position: "RP",
    hand: "RHP",
    birth: "Dec 8 1999",
  },
  {
    name: "김태훈",
    team: "삼성 라이온즈",
    backNumber: "27",
    position: "RP",
    hand: "RHP",
    birth: "Mar 2 1992",
  },
  {
    name: "이호성",
    team: "삼성 라이온즈",
    backNumber: "1",
    position: "RP",
    hand: "RHP",
    birth: "Aug 14 2004",
  },
  {
    name: "이재희",
    team: "삼성 라이온즈",
    backNumber: "59",
    position: "RP",
    hand: "RHP",
    birth: "Oct 11 2001",
  },
  {
    name: "이재익",
    team: "삼성 라이온즈",
    backNumber: "26",
    position: "RP",
    hand: "LHP",
    birth: "Mar 18 1994",
  },
  {
    name: "이상민",
    team: "삼성 라이온즈",
    backNumber: "15",
    position: "RP",
    hand: "LHP",
    birth: "Nov 4 1990",
  },
  {
    name: "이승현",
    team: "삼성 라이온즈",
    backNumber: "20",
    position: "RP",
    hand: "RHP",
    birth: "Nov 20 1991",
  },
  {
    name: "이승현",
    team: "삼성 라이온즈",
    backNumber: "57",
    position: "SP",
    hand: "LHP",
    birth: "May 19 2002",
  },
  {
    name: "이승민",
    team: "삼성 라이온즈",
    backNumber: "28",
    position: "RP",
    hand: "LHP",
    birth: "Aug 26 2000",
  },
  {
    name: "임창민",
    team: "삼성 라이온즈",
    backNumber: "45",
    position: "RP",
    hand: "RHP",
    birth: "Aug 25 1985",
  },
  {
    name: "오승환",
    team: "삼성 라이온즈",
    backNumber: "21",
    position: "RP",
    hand: "RHP",
    birth: "Jul 15 1982",
  },
  {
    name: "송은범",
    team: "삼성 라이온즈",
    backNumber: "46",
    position: "RP",
    hand: "RHP",
    birth: "Mar 17 1984",
  },
  {
    name: "원태인",
    team: "삼성 라이온즈",
    backNumber: "18",
    position: "SP",
    hand: "RHP",
    birth: "Apr 6 2000",
  },
  {
    name: "양창섭",
    team: "삼성 라이온즈",
    backNumber: "42",
    position: "SP/RP",
    hand: "RHP",
    birth: "Sep 22 1999",
  },
  {
    name: "양현",
    team: "삼성 라이온즈",
    backNumber: "19",
    position: "RP",
    hand: "RHP",
    birth: "Aug 23 1992",
  },
  {
    name: "육선엽",
    team: "삼성 라이온즈",
    backNumber: "4",
    position: "RP",
    hand: "RHP",
    birth: "Jul 13 2005",
  },
  {
    name: "강민호",
    team: "삼성 라이온즈",
    backNumber: "47",
    position: "C",
    hand: "RHH",
    birth: "Aug 18 1985",
  },
  {
    name: "김도환",
    team: "삼성 라이온즈",
    backNumber: "24",
    position: "C",
    hand: "RHH",
    birth: "Apr 14 2000",
  },
  {
    name: "김재성",
    team: "삼성 라이온즈",
    backNumber: "2",
    position: "C",
    hand: "LHH",
    birth: "Oct 30 1996",
  },
  {
    name: "김민수",
    team: "삼성 라이온즈",
    backNumber: "12",
    position: "C",
    hand: "RHH",
    birth: "Mar 2 1991",
  },
  {
    name: "이병헌",
    team: "삼성 라이온즈",
    backNumber: "23",
    position: "C",
    hand: "RHH",
    birth: "Oct 26 1999",
  },
  {
    name: "안주형",
    team: "삼성 라이온즈",
    backNumber: "14",
    position: "2B",
    hand: "LHH",
    birth: "Aug 14 1993",
  },
  {
    name: "차승준",
    team: "삼성 라이온즈",
    backNumber: "35",
    position: "IF",
    hand: "LHH",
    birth: "Nov 20 2006",
  },
  {
    name: "루인 디아즈",
    team: "삼성 라이온즈",
    backNumber: "0",
    position: "1B",
    hand: "LHH",
    birth: "Nov 19 1996",
  },
  {
    name: "전병우",
    team: "삼성 라이온즈",
    backNumber: "34",
    position: "3B",
    hand: "RHH",
    birth: "Oct 24 1992",
  },
  {
    name: "강한울",
    team: "삼성 라이온즈",
    backNumber: "6",
    position: "IF",
    hand: "LHH",
    birth: "Sep 12 1991",
  },
  {
    name: "김호진",
    team: "삼성 라이온즈",
    backNumber: "16",
    position: "IF",
    hand: "RHH",
    birth: "Jul 16 2005",
  },
  {
    name: "김영웅",
    team: "삼성 라이온즈",
    backNumber: "30",
    position: "3B",
    hand: "LHH",
    birth: "Aug 24 2003",
  },
  {
    name: "공민규",
    team: "삼성 라이온즈",
    backNumber: "9",
    position: "IF",
    hand: "LHH",
    birth: "Sep 27 1999",
  },
  {
    name: "이창용",
    team: "삼성 라이온즈",
    backNumber: "50",
    position: "IF",
    hand: "RHH",
    birth: "Jun 3 1999",
  },
  {
    name: "이해승",
    team: "삼성 라이온즈",
    backNumber: "56",
    position: "IF",
    hand: "RHH",
    birth: "Aug 1 2000",
  },
  {
    name: "이재현",
    team: "삼성 라이온즈",
    backNumber: "7",
    position: "SS",
    hand: "RHH",
    birth: "Feb 4 2003",
  },
  {
    name: "박병호",
    team: "삼성 라이온즈",
    backNumber: "52",
    position: "1B",
    hand: "RHH",
    birth: "Jul 10 1986",
  },
  {
    name: "류지혁",
    team: "삼성 라이온즈",
    backNumber: "16",
    position: "2B",
    hand: "LHH",
    birth: "Jan 13 1994",
  },
  {
    name: "심재훈",
    team: "삼성 라이온즈",
    backNumber: "38",
    position: "IF",
    hand: "RHH",
    birth: "Mar 3 2006",
  },
  {
    name: "양도균",
    team: "삼성 라이온즈",
    backNumber: "68",
    position: "SS",
    hand: "RHH",
    birth: "Feb 6 2003",
  },
  {
    name: "함수호",
    team: "삼성 라이온즈",
    backNumber: "40",
    position: "OF",
    hand: "LHH",
    birth: "Mar 10 2006",
  },
  {
    name: "홍현빈",
    team: "삼성 라이온즈",
    backNumber: "63",
    position: "OF",
    hand: "LHH",
    birth: "Aug 29 1997",
  },
  {
    name: "김흥곤",
    team: "삼성 라이온즈",
    backNumber: "32",
    position: "LF",
    hand: "RHH",
    birth: "Nov 9 1988",
  },
  {
    name: "김재혁",
    team: "삼성 라이온즈",
    backNumber: "8",
    position: "CF",
    hand: "RHH",
    birth: "Dec 26 1999",
  },
  {
    name: "김지찬",
    team: "삼성 라이온즈",
    backNumber: "58",
    position: "CF",
    hand: "LHH",
    birth: "Mar 8 2001",
  },
  {
    name: "김성윤",
    team: "삼성 라이온즈",
    backNumber: "39",
    position: "CF",
    hand: "LHH",
    birth: "Feb 2 1999",
  },
  {
    name: "김태훈",
    team: "삼성 라이온즈",
    backNumber: "25",
    position: "OF",
    hand: "LHH",
    birth: "Mar 31 1996",
  },
  {
    name: "김태균",
    team: "삼성 라이온즈",
    backNumber: "64",
    position: "LF",
    hand: "RHH",
    birth: "Aug 10 1996",
  },
  {
    name: "구자욱",
    team: "삼성 라이온즈",
    backNumber: "5",
    position: "LF",
    hand: "LHH",
    birth: "Feb 12 1993",
  },
  {
    name: "이성규",
    team: "삼성 라이온즈",
    backNumber: "13",
    position: "1B",
    hand: "RHH",
    birth: "Aug 3 1993",
  },
  {
    name: "박승규",
    team: "삼성 라이온즈",
    backNumber: "66",
    position: "CF",
    hand: "RHH",
    birth: "Sep 2 2000",
  },
  {
    name: "윤정빈",
    team: "삼성 라이온즈",
    backNumber: "31",
    position: "RF",
    hand: "LHH",
    birth: "Jun 24 1999",
  },
  {
    name: "찰리 바네스",
    team: "롯데 자이언츠",
    backNumber: "28",
    position: "SP",
    hand: "LHP",
    birth: "Oct 1 1995",
  },
  {
    name: "최준용",
    team: "롯데 자이언츠",
    backNumber: "56",
    position: "RP",
    hand: "RHP",
    birth: "Oct 10 2001",
  },
  {
    name: "터커 데이비슨",
    team: "롯데 자이언츠",
    backNumber: "36",
    position: "SP",
    hand: "LHP",
    birth: "Mar 25 1996",
  },
  {
    name: "알렉 감보아",
    team: "롯데 자이언츠",
    backNumber: "32",
    position: "SP/RP",
    hand: "LHP",
    birth: "Jan 17 1997",
  },
  {
    name: "한현희",
    team: "롯데 자이언츠",
    backNumber: "1",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jun 25 1993",
  },
  {
    name: "홍민기",
    team: "롯데 자이언츠",
    backNumber: "38",
    position: "RP",
    hand: "LHP",
    birth: "Jul 20 2001",
  },
  {
    name: "현도훈",
    team: "롯데 자이언츠",
    backNumber: "17",
    position: "RP",
    hand: "RHP",
    birth: "Jan 13 1993",
  },
  {
    name: "정철원",
    team: "롯데 자이언츠",
    backNumber: "65",
    position: "RP",
    hand: "RHP",
    birth: "Mar 27 1999",
  },
  {
    name: "정현수",
    team: "롯데 자이언츠",
    backNumber: "57",
    position: "RP",
    hand: "LHP",
    birth: "May 10 2001",
  },
  {
    name: "정우준",
    team: "롯데 자이언츠",
    backNumber: "46",
    position: "RP",
    hand: "RHP",
    birth: "Mar 17 2000",
  },
  {
    name: "진해수",
    team: "롯데 자이언츠",
    backNumber: "31",
    position: "RP",
    hand: "LHP",
    birth: "Jun 26 1986",
  },
  {
    name: "진승현",
    team: "롯데 자이언츠",
    backNumber: "24",
    position: "RP",
    hand: "RHP",
    birth: "Sep 5 2003",
  },
  {
    name: "김도규",
    team: "롯데 자이언츠",
    backNumber: "124",
    position: "RP",
    hand: "RHP",
    birth: "Jul 11 1998",
  },
  {
    name: "김강현",
    team: "롯데 자이언츠",
    backNumber: "19",
    position: "RP",
    hand: "RHP",
    birth: "Feb 27 1995",
  },
  {
    name: "김진욱",
    team: "롯데 자이언츠",
    backNumber: "15",
    position: "SP/RP",
    hand: "LHP",
    birth: "Jul 5 2002",
  },
  {
    name: "김상수",
    team: "롯데 자이언츠",
    backNumber: "24",
    position: "RP",
    hand: "RHP",
    birth: "Jan 2 1988",
  },
  {
    name: "김태현",
    team: "롯데 자이언츠",
    backNumber: "66",
    position: "RP",
    hand: "LHP",
    birth: "Nov 16 2005",
  },
  {
    name: "김원중",
    team: "롯데 자이언츠",
    backNumber: "34",
    position: "CP",
    hand: "RHP",
    birth: "Jun 14 1993",
  },
  {
    name: "구승민",
    team: "롯데 자이언츠",
    backNumber: "22",
    position: "RP",
    hand: "RHP",
    birth: "Jun 12 1990",
  },
  {
    name: "이병준",
    team: "롯데 자이언츠",
    backNumber: "45",
    position: "RP",
    hand: "RHP",
    birth: "May 28 2002",
  },
  {
    name: "이민석",
    team: "롯데 자이언츠",
    backNumber: "37",
    position: "SP",
    hand: "RHP",
    birth: "Dec 10 2003",
  },
  {
    name: "나균안",
    team: "롯데 자이언츠",
    backNumber: "43",
    position: "SP",
    hand: "RHP",
    birth: "Mar 16 1998",
  },
  {
    name: "박진",
    team: "롯데 자이언츠",
    backNumber: "44",
    position: "SP/RP",
    hand: "RHP",
    birth: "Apr 2 1999",
  },
  {
    name: "박진형",
    team: "롯데 자이언츠",
    backNumber: "40",
    position: "RP",
    hand: "RHP",
    birth: "Jun 10 1994",
  },
  {
    name: "박준우",
    team: "롯데 자이언츠",
    backNumber: "58",
    position: "RP",
    hand: "RHP",
    birth: "May 27 2005",
  },
  {
    name: "박세현",
    team: "롯데 자이언츠",
    backNumber: "68",
    position: "RP",
    hand: "RHP",
    birth: "Jan 21 2006",
  },
  {
    name: "박시영",
    team: "롯데 자이언츠",
    backNumber: "41",
    position: "RP",
    hand: "LHP",
    birth: "Jun 27 1997",
  },
  {
    name: "박세웅",
    team: "롯데 자이언츠",
    backNumber: "21",
    position: "SP",
    hand: "RHP",
    birth: "Nov 30 1995",
  },
  {
    name: "박시영",
    team: "롯데 자이언츠",
    backNumber: "25",
    position: "RP",
    hand: "RHP",
    birth: "Mar 10 1989",
  },
  {
    name: "심재민",
    team: "롯데 자이언츠",
    backNumber: "23",
    position: "RP",
    hand: "LHP",
    birth: "Feb 18 1994",
  },
  {
    name: "신병률",
    team: "롯데 자이언츠",
    backNumber: "12",
    position: "RP",
    hand: "RHP",
    birth: "Jan 30 1996",
  },
  {
    name: "송재영",
    team: "롯데 자이언츠",
    backNumber: "59",
    position: "RP",
    hand: "LHP",
    birth: "Jun 20 2002",
  },
  {
    name: "윤성빈",
    team: "롯데 자이언츠",
    backNumber: "55",
    position: "SP/RP",
    hand: "RHP",
    birth: "Feb 26 1999",
  },
  {
    name: "백두산",
    team: "롯데 자이언츠",
    backNumber: "62",
    position: "C",
    hand: "RHH",
    birth: "May 20 2001",
  },
  {
    name: "정보근",
    team: "롯데 자이언츠",
    backNumber: "42",
    position: "C",
    hand: "RHH",
    birth: "Aug 31 1999",
  },
  {
    name: "강승구",
    team: "롯데 자이언츠",
    backNumber: "39",
    position: "C",
    hand: "RHH",
    birth: "Oct 19 2003",
  },
  {
    name: "박재엽",
    team: "롯데 자이언츠",
    backNumber: "63",
    position: "C",
    hand: "RHH",
    birth: "Jan 23 2006",
  },
  {
    name: "서동욱",
    team: "롯데 자이언츠",
    backNumber: "106",
    position: "C",
    hand: "RHH",
    birth: "Mar 24 2000",
  },
  {
    name: "손성빈",
    team: "롯데 자이언츠",
    backNumber: "28",
    position: "C",
    hand: "RHH",
    birth: "Jan 14 2002",
  },
  {
    name: "유강남",
    team: "롯데 자이언츠",
    backNumber: "27",
    position: "C",
    hand: "RHH",
    birth: "Jul 15 1992",
  },
  {
    name: "최항",
    team: "롯데 자이언츠",
    backNumber: "14",
    position: "IF",
    hand: "LHH",
    birth: "Jan 3 1994",
  },
  {
    name: "고승민",
    team: "롯데 자이언츠",
    backNumber: "2",
    position: "2B",
    hand: "LHH",
    birth: "Aug 11 2000",
  },
  {
    name: "한태양",
    team: "롯데 자이언츠",
    backNumber: "6",
    position: "IF",
    hand: "RHH",
    birth: "Sep 15 2003",
  },
  {
    name: "전민재",
    team: "롯데 자이언츠",
    backNumber: "13",
    position: "SS",
    hand: "RHH",
    birth: "Jun 30 1999",
  },
  {
    name: "정훈",
    team: "롯데 자이언츠",
    backNumber: "9",
    position: "1B",
    hand: "RHH",
    birth: "Jul 18 1987",
  },
  {
    name: "강성우",
    team: "롯데 자이언츠",
    backNumber: "9",
    position: "IF",
    hand: "RHH",
    birth: "Apr 12 2005",
  },
  {
    name: "김민성",
    team: "롯데 자이언츠",
    backNumber: "16",
    position: "3B",
    hand: "RHH",
    birth: "Dec 17 1988",
  },
  {
    name: "이호준",
    team: "롯데 자이언츠",
    backNumber: "30",
    position: "SS",
    hand: "LHH",
    birth: "Mar 20 2004",
  },
  {
    name: "이태경",
    team: "롯데 자이언츠",
    backNumber: "69",
    position: "IF",
    hand: "RHH",
    birth: "Nov 24 2002",
  },
  {
    name: "나승엽",
    team: "롯데 자이언츠",
    backNumber: "51",
    position: "1B",
    hand: "LHH",
    birth: "Feb 15 2002",
  },
  {
    name: "노진혁",
    team: "롯데 자이언츠",
    backNumber: "52",
    position: "IF",
    hand: "LHH",
    birth: "Jul 15 1989",
  },
  {
    name: "박찬형",
    team: "롯데 자이언츠",
    backNumber: "60",
    position: "IF",
    hand: "LHH",
    birth: "Oct 17 2002",
  },
  {
    name: "박승욱",
    team: "롯데 자이언츠",
    backNumber: "53",
    position: "2B",
    hand: "LHH",
    birth: "Dec 4 1992",
  },
  {
    name: "신윤호",
    team: "롯데 자이언츠",
    backNumber: "3",
    position: "RF",
    hand: "RHH",
    birth: "Jan 5 1996",
  },
  {
    name: "손호영",
    team: "롯데 자이언츠",
    backNumber: "33",
    position: "3B",
    hand: "RHH",
    birth: "Aug 23 1994",
  },
  {
    name: "조세진",
    team: "롯데 자이언츠",
    backNumber: "5",
    position: "OF",
    hand: "RHH",
    birth: "Nov 21 2003",
  },
  {
    name: "한승현",
    team: "롯데 자이언츠",
    backNumber: "35",
    position: "OF",
    hand: "RHH",
    birth: "Oct 29 2006",
  },
  {
    name: "황성빈",
    team: "롯데 자이언츠",
    backNumber: "0",
    position: "LF",
    hand: "LHH",
    birth: "Dec 19 1997",
  },
  {
    name: "장두성",
    team: "롯데 자이언츠",
    backNumber: "7",
    position: "CF",
    hand: "LHH",
    birth: "Sep 16 1999",
  },
  {
    name: "전준우",
    team: "롯데 자이언츠",
    backNumber: "8",
    position: "LF",
    hand: "RHH",
    birth: "Feb 25 1986",
  },
  {
    name: "김동혁",
    team: "롯데 자이언츠",
    backNumber: "50",
    position: "OF",
    hand: "LHH",
    birth: "Sep 15 2000",
  },
  {
    name: "김동현",
    team: "롯데 자이언츠",
    backNumber: "64",
    position: "OF",
    hand: "LHH",
    birth: "Dec 30 2004",
  },
  {
    name: "이인한",
    team: "롯데 자이언츠",
    backNumber: "54",
    position: "OF",
    hand: "RHH",
    birth: "Dec 24 1998",
  },
  {
    name: "빅터 레예스",
    team: "롯데 자이언츠",
    backNumber: "29",
    position: "RF",
    hand: "SHH",
    birth: "Oct 5 1994",
  },
  {
    name: "윤동희",
    team: "롯데 자이언츠",
    backNumber: "91",
    position: "CF",
    hand: "RHH",
    birth: "Sep 18 2003",
  },
  {
    name: "로건 앨런",
    team: "NC 다이노스",
    backNumber: "12",
    position: "SP",
    hand: "LHP",
    birth: "May 23 1997",
  },
  {
    name: "배재환",
    team: "NC 다이노스",
    backNumber: "61",
    position: "RP",
    hand: "RHP",
    birth: "Feb 24 1995",
  },
  {
    name: "조민석",
    team: "NC 다이노스",
    backNumber: "64",
    position: "RP",
    hand: "RHP",
    birth: "Dec 21 1998",
  },
  {
    name: "최성영",
    team: "NC 다이노스",
    backNumber: "26",
    position: "SP",
    hand: "LHP",
    birth: "Apr 28 1997",
  },
  {
    name: "최우석",
    team: "NC 다이노스",
    backNumber: "48",
    position: "RP",
    hand: "RHP",
    birth: "Mar 31 2005",
  },
  {
    name: "천사민",
    team: "NC 다이노스",
    backNumber: "57",
    position: "RP",
    hand: "RHP",
    birth: "Jul 6 1999",
  },
  {
    name: "한재선",
    team: "NC 다이노스",
    backNumber: "55",
    position: "RP",
    hand: "RHP",
    birth: "Nov 21 2001",
  },
  {
    name: "홍재문",
    team: "NC 다이노스",
    backNumber: "96",
    position: "RP",
    hand: "RHP",
    birth: "Jul 9 2004",
  },
  {
    name: "준루건",
    team: "NC 다이노스",
    backNumber: "47",
    position: "RP",
    hand: "RHP",
    birth: "Jun 9 2000",
  },
  {
    name: "김휘건",
    team: "NC 다이노스",
    backNumber: "19",
    position: "RP",
    hand: "RHP",
    birth: "Aug 27 2005",
  },
  {
    name: "김재열",
    team: "NC 다이노스",
    backNumber: "32",
    position: "RP",
    hand: "RHP",
    birth: "Jan 2 1996",
  },
  {
    name: "김진호",
    team: "NC 다이노스",
    backNumber: "54",
    position: "RP",
    hand: "RHP",
    birth: "Jun 7 1998",
  },
  {
    name: "김민규",
    team: "NC 다이노스",
    backNumber: "63",
    position: "RP",
    hand: "RHP",
    birth: "Sep 7 2001",
  },
  {
    name: "김녹원",
    team: "NC 다이노스",
    backNumber: "22",
    position: "SP/RP",
    hand: "RHP",
    birth: "May 17 2003",
  },
  {
    name: "김시훈",
    team: "NC 다이노스",
    backNumber: "21",
    position: "RP",
    hand: "RHP",
    birth: "Feb 24 1999",
  },
  {
    name: "김태경",
    team: "NC 다이노스",
    backNumber: "11",
    position: "SP/RP",
    hand: "RHP",
    birth: "Apr 7 2001",
  },
  {
    name: "김태훈",
    team: "NC 다이노스",
    backNumber: "95",
    position: "RP",
    hand: "RHP",
    birth: "Oct 26 2006",
  },
  {
    name: "김태현",
    team: "NC 다이노스",
    backNumber: "15",
    position: "RP",
    hand: "LHP",
    birth: "Mar 21 1998",
  },
  {
    name: "김영규",
    team: "NC 다이노스",
    backNumber: "17",
    position: "RP",
    hand: "LHP",
    birth: "Feb 10 2000",
  },
  {
    name: "구창모",
    team: "NC 다이노스",
    backNumber: "59",
    position: "RP",
    hand: "LHP",
    birth: "Feb 17 1997",
  },
  {
    name: "이재학",
    team: "NC 다이노스",
    backNumber: "51",
    position: "RP",
    hand: "RHP",
    birth: "Oct 4 1990",
  },
  {
    name: "이준혁",
    team: "NC 다이노스",
    backNumber: "40",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jun 30 2003",
  },
  {
    name: "이민",
    team: "NC 다이노스",
    backNumber: "97",
    position: "RP",
    hand: "RHP",
    birth: "Aug 8 2005",
  },
  {
    name: "이용찬",
    team: "NC 다이노스",
    backNumber: "45",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jan 2 1989",
  },
  {
    name: "임정호",
    team: "NC 다이노스",
    backNumber: "13",
    position: "RP",
    hand: "LHP",
    birth: "Apr 16 1990",
  },
  {
    name: "임상현",
    team: "NC 다이노스",
    backNumber: "28",
    position: "RP",
    hand: "RHP",
    birth: "Jul 16 2005",
  },
  {
    name: "목지훈",
    team: "NC 다이노스",
    backNumber: "20",
    position: "SP",
    hand: "RHP",
    birth: "May 11 2004",
  },
  {
    name: "박주현",
    team: "NC 다이노스",
    backNumber: "67",
    position: "RP",
    hand: "LHP",
    birth: "Aug 3 1999",
  },
  {
    name: "류진욱",
    team: "NC 다이노스",
    backNumber: "41",
    position: "CP",
    hand: "RHP",
    birth: "Oct 10 1996",
  },
  {
    name: "서의태",
    team: "NC 다이노스",
    backNumber: "58",
    position: "RP",
    hand: "LHP",
    birth: "Sep 5 1997",
  },
  {
    name: "신민혁",
    team: "NC 다이노스",
    backNumber: "18",
    position: "SP",
    hand: "RHP",
    birth: "Feb 4 1999",
  },
  {
    name: "신영우",
    team: "NC 다이노스",
    backNumber: "43",
    position: "SP/RP",
    hand: "RHP",
    birth: "Apr 21 2004",
  },
  {
    name: "소리현",
    team: "NC 다이노스",
    backNumber: "50",
    position: "RP",
    hand: "RHP",
    birth: "Feb 9 1999",
  },
  {
    name: "손주환",
    team: "NC 다이노스",
    backNumber: "46",
    position: "RP",
    hand: "RHP",
    birth: "Jan 5 2002",
  },
  {
    name: "라일리 톰슨",
    team: "NC 다이노스",
    backNumber: "3",
    position: "SP",
    hand: "RHP",
    birth: "Jul 9 1996",
  },
  {
    name: "원종해",
    team: "NC 다이노스",
    backNumber: "56",
    position: "RP",
    hand: "RHP",
    birth: "Apr 9 2005",
  },
  {
    name: "안중열",
    team: "NC 다이노스",
    backNumber: "1",
    position: "C",
    hand: "RHH",
    birth: "Sep 1 1995",
  },
  {
    name: "김형준",
    team: "NC 다이노스",
    backNumber: "25",
    position: "C",
    hand: "RHH",
    birth: "Nov 2 1999",
  },
  {
    name: "김정호",
    team: "NC 다이노스",
    backNumber: "42",
    position: "C",
    hand: "RHH",
    birth: "Jul 13 1998",
  },
  {
    name: "박세혁",
    team: "NC 다이노스",
    backNumber: "10",
    position: "C",
    hand: "LHH",
    birth: "Jan 9 1990",
  },
  {
    name: "신용석",
    team: "NC 다이노스",
    backNumber: "1",
    position: "C",
    hand: "RHH",
    birth: "Oct 11 2003",
  },
  {
    name: "최정우",
    team: "NC 다이노스",
    backNumber: "14",
    position: "CF",
    hand: "LHH",
    birth: "Jun 24 2000",
  },
  {
    name: "매튜 데이비슨",
    team: "NC 다이노스",
    backNumber: "24",
    position: "1B",
    hand: "RHH",
    birth: "Mar 26 1991",
  },
  {
    name: "도태훈",
    team: "NC 다이노스",
    backNumber: "16",
    position: "1B",
    hand: "LHH",
    birth: "Mar 18 1993",
  },
  {
    name: "한재환",
    team: "NC 다이노스",
    backNumber: "35",
    position: "1B",
    hand: "RHH",
    birth: "Oct 19 2001",
  },
  {
    name: "장창훈",
    team: "NC 다이노스",
    backNumber: "93",
    position: "IF",
    hand: "LHH",
    birth: "May 22 2000",
  },
  {
    name: "정현창",
    team: "NC 다이노스",
    backNumber: "52",
    position: "IF",
    hand: "LHH",
    birth: "Jul 14 2006",
  },
  {
    name: "김한별",
    team: "NC 다이노스",
    backNumber: "68",
    position: "SS",
    hand: "RHH",
    birth: "Jan 18 2001",
  },
  {
    name: "김주원",
    team: "NC 다이노스",
    backNumber: "7",
    position: "SS",
    hand: "SHH",
    birth: "Jul 30 2002",
  },
  {
    name: "김세훈",
    team: "NC 다이노스",
    backNumber: "9",
    position: "IF",
    hand: "RHH",
    birth: "Apr 4 2005",
  },
  {
    name: "김휘집",
    team: "NC 다이노스",
    backNumber: "44",
    position: "3B",
    hand: "RHH",
    birth: "Jan 1 2002",
  },
  {
    name: "오태양",
    team: "NC 다이노스",
    backNumber: "6",
    position: "IF",
    hand: "RHH",
    birth: "Apr 25 2002",
  },
  {
    name: "오영수",
    team: "NC 다이노스",
    backNumber: "34",
    position: "IF",
    hand: "LHH",
    birth: "Jan 30 2000",
  },
  {
    name: "박민우",
    team: "NC 다이노스",
    backNumber: "2",
    position: "2B",
    hand: "LHH",
    birth: "Feb 6 1993",
  },
  {
    name: "서호철",
    team: "NC 다이노스",
    backNumber: "5",
    position: "3B",
    hand: "RHH",
    birth: "Oct 16 1996",
  },
  {
    name: "천재환",
    team: "NC 다이노스",
    backNumber: "23",
    position: "RF",
    hand: "RHH",
    birth: "Apr 1 1994",
  },
  {
    name: "한석현",
    team: "NC 다이노스",
    backNumber: "33",
    position: "CF",
    hand: "LHH",
    birth: "May 17 1994",
  },
  {
    name: "김범준",
    team: "NC 다이노스",
    backNumber: "66",
    position: "OF",
    hand: "RHH",
    birth: "Apr 20 2000",
  },
  {
    name: "고승환",
    team: "NC 다이노스",
    backNumber: "60",
    position: "OF",
    hand: "LHH",
    birth: "Mar 15 2001",
  },
  {
    name: "권희동",
    team: "NC 다이노스",
    backNumber: "36",
    position: "LF",
    hand: "RHH",
    birth: "Dec 30 1990",
  },
  {
    name: "박한결",
    team: "NC 다이노스",
    backNumber: "3",
    position: "OF",
    hand: "RHH",
    birth: "Apr 26 2004",
  },
  {
    name: "박건우",
    team: "NC 다이노스",
    backNumber: "37",
    position: "RF",
    hand: "RHH",
    birth: "Sep 8 1990",
  },
  {
    name: "박시원",
    team: "NC 다이노스",
    backNumber: "53",
    position: "RF",
    hand: "LHH",
    birth: "May 30 2001",
  },
  {
    name: "박영빈",
    team: "NC 다이노스",
    backNumber: "39",
    position: "OF",
    hand: "LHH",
    birth: "Jul 16 1997",
  },
  {
    name: "송승환",
    team: "NC 다이노스",
    backNumber: "8",
    position: "OF",
    hand: "RHH",
    birth: "Oct 28 2000",
  },
  {
    name: "배재준",
    team: "LG 트윈스",
    backNumber: "25",
    position: "RP",
    hand: "RHP",
    birth: "Nov 24 1994",
  },
  {
    name: "백승현",
    team: "LG 트윈스",
    backNumber: "61",
    position: "RP",
    hand: "RHP",
    birth: "May 26 1995",
  },
  {
    name: "요니 치리노스",
    team: "LG 트윈스",
    backNumber: "46",
    position: "SP",
    hand: "RHP",
    birth: "Dec 26 1993",
  },
  {
    name: "최채흥",
    team: "LG 트윈스",
    backNumber: "56",
    position: "SP/RP",
    hand: "LHP",
    birth: "Jan 22 1995",
  },
  {
    name: "추세현",
    team: "LG 트윈스",
    backNumber: "63",
    position: "RP",
    hand: "RHP",
    birth: "Apr 19 2006",
  },
  {
    name: "함덕주",
    team: "LG 트윈스",
    backNumber: "11",
    position: "RP",
    hand: "LHP",
    birth: "Jan 13 1995",
  },
  {
    name: "허준혁",
    team: "LG 트윈스",
    backNumber: "58",
    position: "RP",
    hand: "RHP",
    birth: "Jul 2 1999",
  },
  {
    name: "허용주",
    team: "LG 트윈스",
    backNumber: "43",
    position: "RP",
    hand: "RHP",
    birth: "Jun 5 2003",
  },
  {
    name: "엘리서 에르난데스",
    team: "LG 트윈스",
    backNumber: "30",
    position: "SP",
    hand: "RHP",
    birth: "May 3 1995",
  },
  {
    name: "임찬규",
    team: "LG 트윈스",
    backNumber: "1",
    position: "SP",
    hand: "RHP",
    birth: "Nov 20 1992",
  },
  {
    name: "장현식",
    team: "LG 트윈스",
    backNumber: "50",
    position: "CP",
    hand: "RHP",
    birth: "Feb 24 1995",
  },
  {
    name: "진우영",
    team: "LG 트윈스",
    backNumber: "48",
    position: "RP",
    hand: "RHP",
    birth: "Feb 5 2001",
  },
  {
    name: "정지헌",
    team: "LG 트윈스",
    backNumber: "99",
    position: "RP",
    hand: "RHP",
    birth: "Jan 1 2003",
  },
  {
    name: "정우영",
    team: "LG 트윈스",
    backNumber: "18",
    position: "RP",
    hand: "RHP",
    birth: "Aug 19 1999",
  },
  {
    name: "김대현",
    team: "LG 트윈스",
    backNumber: "12",
    position: "RP",
    hand: "RHP",
    birth: "Mar 8 1997",
  },
  {
    name: "김진수",
    team: "LG 트윈스",
    backNumber: "45",
    position: "RP",
    hand: "RHP",
    birth: "Aug 31 1998",
  },
  {
    name: "김진성",
    team: "LG 트윈스",
    backNumber: "42",
    position: "RP",
    hand: "RHP",
    birth: "Mar 7 1985",
  },
  {
    name: "김종운",
    team: "LG 트윈스",
    backNumber: "49",
    position: "RP",
    hand: "RHP",
    birth: "Sep 11 2006",
  },
  {
    name: "김주온",
    team: "LG 트윈스",
    backNumber: "57",
    position: "SP/RP",
    hand: "RHP",
    birth: "Dec 8 1996",
  },
  {
    name: "김강률",
    team: "LG 트윈스",
    backNumber: "37",
    position: "RP",
    hand: "RHP",
    birth: "Aug 28 1988",
  },
  {
    name: "김영준",
    team: "LG 트윈스",
    backNumber: "35",
    position: "RP",
    hand: "RHP",
    birth: "Jan 12 1999",
  },
  {
    name: "김영우",
    team: "LG 트윈스",
    backNumber: "67",
    position: "RP",
    hand: "RHP",
    birth: "Jan 14 2005",
  },
  {
    name: "김유영",
    team: "LG 트윈스",
    backNumber: "0",
    position: "RP",
    hand: "LHP",
    birth: "May 2 1994",
  },
  {
    name: "이지강",
    team: "LG 트윈스",
    backNumber: "32",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jul 2 1999",
  },
  {
    name: "이종준",
    team: "LG 트윈스",
    backNumber: "40",
    position: "RP",
    hand: "RHP",
    birth: "Mar 9 2001",
  },
  {
    name: "이우찬",
    team: "LG 트윈스",
    backNumber: "21",
    position: "RP",
    hand: "LHP",
    birth: "Aug 4 1992",
  },
  {
    name: "임준형",
    team: "LG 트윈스",
    backNumber: "59",
    position: "RP",
    hand: "LHP",
    birth: "Nov 16 2000",
  },
  {
    name: "박명근",
    team: "LG 트윈스",
    backNumber: "39",
    position: "RP",
    hand: "RHP",
    birth: "Mar 27 2004",
  },
  {
    name: "심창민",
    team: "LG 트윈스",
    backNumber: "28",
    position: "RP",
    hand: "RHP",
    birth: "Feb 1 1993",
  },
  {
    name: "손주영",
    team: "LG 트윈스",
    backNumber: "29",
    position: "SP",
    hand: "LHP",
    birth: "Dec 2 1998",
  },
  {
    name: "송승기",
    team: "LG 트윈스",
    backNumber: "13",
    position: "SP",
    hand: "LHP",
    birth: "Apr 10 2002",
  },
  {
    name: "성동현",
    team: "LG 트윈스",
    backNumber: "34",
    position: "RP",
    hand: "RHP",
    birth: "May 18 1999",
  },
  {
    name: "우강훈",
    team: "LG 트윈스",
    backNumber: "20",
    position: "RP",
    hand: "RHP",
    birth: "Oct 3 2002",
  },
  {
    name: "코엔 윈",
    team: "LG 트윈스",
    backNumber: "38",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jan 25 1999",
  },
  {
    name: "이정용",
    team: "LG 트윈스",
    backNumber: "31",
    position: "RP",
    hand: "RHP",
    birth: "Mar 26 1996",
  },
  {
    name: "유영찬",
    team: "LG 트윈스",
    backNumber: "54",
    position: "RP",
    hand: "RHP",
    birth: "Mar 7 1997",
  },
  {
    name: "김성우",
    team: "LG 트윈스",
    backNumber: "44",
    position: "C",
    hand: "RHH",
    birth: "Nov 15 2003",
  },
  {
    name: "이한림",
    team: "LG 트윈스",
    backNumber: "00",
    position: "C",
    hand: "RHH",
    birth: "Nov 18 2006",
  },
  {
    name: "이주헌",
    team: "LG 트윈스",
    backNumber: "26",
    position: "C",
    hand: "RHH",
    birth: "Mar 4 2003",
  },
  {
    name: "박동원",
    team: "LG 트윈스",
    backNumber: "27",
    position: "C",
    hand: "RHH",
    birth: "Apr 7 1990",
  },
  {
    name: "오스틴 딘",
    team: "LG 트윈스",
    backNumber: "23",
    position: "1B",
    hand: "RHH",
    birth: "Oct 14 1993",
  },
  {
    name: "구본혁",
    team: "LG 트윈스",
    backNumber: "6",
    position: "2B",
    hand: "RHH",
    birth: "Jan 11 1997",
  },
  {
    name: "김범석",
    team: "LG 트윈스",
    backNumber: "55",
    position: "1B",
    hand: "RHH",
    birth: "May 21 2004",
  },
  {
    name: "김주성",
    team: "LG 트윈스",
    backNumber: "5",
    position: "IF",
    hand: "RHH",
    birth: "Jan 30 1998",
  },
  {
    name: "김민수",
    team: "LG 트윈스",
    backNumber: "16",
    position: "3B",
    hand: "RHH",
    birth: "Mar 18 1998",
  },
  {
    name: "김성진",
    team: "LG 트윈스",
    backNumber: "36",
    position: "IF",
    hand: "RHH",
    birth: "Mar 17 2000",
  },
  {
    name: "이태훈",
    team: "LG 트윈스",
    backNumber: "65",
    position: "IF",
    hand: "LHH",
    birth: "Aug 21 2006",
  },
  {
    name: "이영빈",
    team: "LG 트윈스",
    backNumber: "7",
    position: "1B",
    hand: "LHH",
    birth: "Jun 17 2002",
  },
  {
    name: "문보경",
    team: "LG 트윈스",
    backNumber: "2",
    position: "3B",
    hand: "LHH",
    birth: "Jul 19 2000",
  },
  {
    name: "문정빈",
    team: "LG 트윈스",
    backNumber: "53",
    position: "IF",
    hand: "RHH",
    birth: "Aug 15 2003",
  },
  {
    name: "오지환",
    team: "LG 트윈스",
    backNumber: "10",
    position: "SS",
    hand: "LHH",
    birth: "Mar 12 1990",
  },
  {
    name: "신민재",
    team: "LG 트윈스",
    backNumber: "4",
    position: "2B",
    hand: "LHH",
    birth: "Jan 21 1996",
  },
  {
    name: "손영준",
    team: "LG 트윈스",
    backNumber: "52",
    position: "IF",
    hand: "RHH",
    birth: "Feb 15 2000",
  },
  {
    name: "안익훈",
    team: "LG 트윈스",
    backNumber: "15",
    position: "LF",
    hand: "LHH",
    birth: "Feb 12 1996",
  },
  {
    name: "최승민",
    team: "LG 트윈스",
    backNumber: "62",
    position: "LF",
    hand: "LHH",
    birth: "Jul 1 1996",
  },
  {
    name: "최원영",
    team: "LG 트윈스",
    backNumber: "3",
    position: "RF",
    hand: "RHH",
    birth: "Jul 18 2003",
  },
  {
    name: "함창건",
    team: "LG 트윈스",
    backNumber: "24",
    position: "OF",
    hand: "LHH",
    birth: "Aug 18 2001",
  },
  {
    name: "홍창기",
    team: "LG 트윈스",
    backNumber: "51",
    position: "RF",
    hand: "LHH",
    birth: "Nov 21 1993",
  },
  {
    name: "김현종",
    team: "LG 트윈스",
    backNumber: "66",
    position: "OF",
    hand: "RHH",
    birth: "Aug 4 2004",
  },
  {
    name: "김현수",
    team: "LG 트윈스",
    backNumber: "22",
    position: "LF",
    hand: "LHH",
    birth: "Jan 12 1988",
  },
  {
    name: "문성주",
    team: "LG 트윈스",
    backNumber: "8",
    position: "LF",
    hand: "LHH",
    birth: "Feb 20 1997",
  },
  {
    name: "박관우",
    team: "LG 트윈스",
    backNumber: "64",
    position: "OF",
    hand: "LHH",
    birth: "Mar 22 2006",
  },
  {
    name: "박해민",
    team: "LG 트윈스",
    backNumber: "17",
    position: "CF",
    hand: "LHH",
    birth: "Feb 24 1990",
  },
  {
    name: "서영준",
    team: "LG 트윈스",
    backNumber: "60",
    position: "OF",
    hand: "RHH",
    birth: "Mar 18 2006",
  },
  {
    name: "송찬의",
    team: "LG 트윈스",
    backNumber: "14",
    position: "LF",
    hand: "RHH",
    birth: "Feb 20 1999",
  },
];
