type Athlete = {
  name: string;
  team: string;
  backNumber: `${number}`;
  position: string;
  hand: "RHP" | "LHP" | "RHH" | "LHH" | "SHH";
  birth: string;
};

export const KBO_ROSTERS: Athlete[] = [
  {
    name: "Choi Ji-kang",
    team: "doosan",
    backNumber: "42",
    position: "RP",
    hand: "RHP",
    birth: "Jul 23 2001",
  },
  {
    name: "Choi Jong-in",
    team: "doosan",
    backNumber: "40",
    position: "RP",
    hand: "RHP",
    birth: "May 1 2001",
  },
  {
    name: "Choi Jun-ho",
    team: "doosan",
    backNumber: "41",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jun 3 2004",
  },
  {
    name: "Choi Min-seok",
    team: "doosan",
    backNumber: "68",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jul 2 2006",
  },
  {
    name: "Choi Seung-yong",
    team: "doosan",
    backNumber: "28",
    position: "SP",
    hand: "LHP",
    birth: "May 11 2001",
  },
  {
    name: "Choi Won-joon",
    team: "doosan",
    backNumber: "61",
    position: "SP",
    hand: "RHP",
    birth: "Dec 21 1994",
  },
  {
    name: "Gwak Been",
    team: "doosan",
    backNumber: "47",
    position: "SP/RP",
    hand: "RHP",
    birth: "May 28 1999",
  },
  {
    name: "Hong Geon-hui",
    team: "doosan",
    backNumber: "17",
    position: "RP",
    hand: "RHP",
    birth: "Sep 29 1992",
  },
  {
    name: "Hong Min-gyu",
    team: "doosan",
    backNumber: "67",
    position: "SP/RP",
    hand: "RHP",
    birth: "Sep 11 2006",
  },
  {
    name: "Hwang Hee-cheon",
    team: "doosan",
    backNumber: "58",
    position: "RP",
    hand: "LHP",
    birth: "Nov 6 2006",
  },
  {
    name: "Cole Irvin",
    team: "doosan",
    backNumber: "57",
    position: "SP",
    hand: "LHP",
    birth: "Jan 31 1994",
  },
  {
    name: "Je Hwan-yu",
    team: "doosan",
    backNumber: "93",
    position: "RP",
    hand: "RHP",
    birth: "Sep 30 2000",
  },
  {
    name: "Jung Eun-jae",
    team: "doosan",
    backNumber: "102",
    position: "RP",
    hand: "RHP",
    birth: "Dec 31 1991",
  },
  {
    name: "Kim Ho-jun",
    team: "doosan",
    backNumber: "56",
    position: "RP",
    hand: "LHP",
    birth: "May 17 1998",
  },
  {
    name: "Kim Jeong-woo",
    team: "doosan",
    backNumber: "30",
    position: "RP",
    hand: "RHP",
    birth: "May 15 1999",
  },
  {
    name: "Kim Min-gyu",
    team: "doosan",
    backNumber: "19",
    position: "RP",
    hand: "RHP",
    birth: "May 7 1999",
  },
  {
    name: "Kim Mu-bin",
    team: "doosan",
    backNumber: "64",
    position: "RP",
    hand: "LHP",
    birth: "Apr 11 2005",
  },
  {
    name: "Kim Myeong-sin",
    team: "doosan",
    backNumber: "46",
    position: "RP",
    hand: "RHP",
    birth: "Nov 29 1993",
  },
  {
    name: "Kim Taek-yeon",
    team: "doosan",
    backNumber: "63",
    position: "CP",
    hand: "RHP",
    birth: "Jun 3 2005",
  },
  {
    name: "Kim Yu-seong",
    team: "doosan",
    backNumber: "20",
    position: "SP",
    hand: "RHP",
    birth: "Jan 1 2002",
  },
  {
    name: "Ko Hyo-jun",
    team: "doosan",
    backNumber: "35",
    position: "RP",
    hand: "LHP",
    birth: "Feb 8 1983",
  },
  {
    name: "Kwon Hwi",
    team: "doosan",
    backNumber: "18",
    position: "RP",
    hand: "RHP",
    birth: "Dec 7 2000",
  },
  {
    name: "Lee Byeong-heon",
    team: "doosan",
    backNumber: "29",
    position: "RP",
    hand: "LHP",
    birth: "Jun 4 2003",
  },
  {
    name: "Lee Kyo-hoon",
    team: "doosan",
    backNumber: "7",
    position: "RP",
    hand: "LHP",
    birth: "May 29 2000",
  },
  {
    name: "Lee Seung-jin",
    team: "doosan",
    backNumber: "55",
    position: "RP",
    hand: "RHP",
    birth: "Jan 7 1995",
  },
  {
    name: "Lee Young-ha",
    team: "doosan",
    backNumber: "50",
    position: "RP",
    hand: "RHP",
    birth: "Nov 1 1997",
  },
  {
    name: "Zach Logue",
    team: "doosan",
    backNumber: "39",
    position: "SP",
    hand: "LHP",
    birth: "Apr 23 1996",
  },
  {
    name: "Park Chi-guk",
    team: "doosan",
    backNumber: "1",
    position: "RP",
    hand: "RHP",
    birth: "Mar 10 1998",
  },
  {
    name: "Park Ji-ho",
    team: "doosan",
    backNumber: "4",
    position: "RP",
    hand: "LHP",
    birth: "Jul 2 2003",
  },
  {
    name: "Park Jung-soo",
    team: "doosan",
    backNumber: "12",
    position: "RP",
    hand: "RHP",
    birth: "Jan 29 1996",
  },
  {
    name: "Park Shin-zi",
    team: "doosan",
    backNumber: "49",
    position: "RP",
    hand: "RHP",
    birth: "Jul 16 1999",
  },
  {
    name: "Yang Jae-hun",
    team: "doosan",
    backNumber: "92",
    position: "RP",
    hand: "RHP",
    birth: "May 1 2003",
  },
  {
    name: "Yun Tae-ho",
    team: "doosan",
    backNumber: "65",
    position: "RP",
    hand: "RHP",
    birth: "Oct 10 2003",
  },
  {
    name: "Jang Seung-hyun",
    team: "doosan",
    backNumber: "22",
    position: "C",
    hand: "RHH",
    birth: "Mar 7 1994",
  },
  {
    name: "Kim Ki-yeon",
    team: "doosan",
    backNumber: "45",
    position: "C",
    hand: "RHH",
    birth: "Sep 7 1997",
  },
  {
    name: "Park Min-jun",
    team: "doosan",
    backNumber: "26",
    position: "C",
    hand: "RHH",
    birth: "Oct 21 2002",
  },
  {
    name: "Ryu Hyun-jun",
    team: "doosan",
    backNumber: "11",
    position: "C",
    hand: "RHH",
    birth: "Mar 25 2005",
  },
  {
    name: "Yang Eui-ji",
    team: "doosan",
    backNumber: "25",
    position: "C",
    hand: "RHH",
    birth: "Jun 5 1987",
  },
  {
    name: "Im Jong-sung",
    team: "doosan",
    backNumber: "3",
    position: "IF",
    hand: "RHH",
    birth: "Mar 3 2005",
  },
  {
    name: "Kang Seung-ho",
    team: "doosan",
    backNumber: "23",
    position: "2B",
    hand: "RHH",
    birth: "Feb 9 1994",
  },
  {
    name: "Kim Dong-jun",
    team: "doosan",
    backNumber: "48",
    position: "IF",
    hand: "LHH",
    birth: "Sep 4 2002",
  },
  {
    name: "Kim Jun-sang",
    team: "doosan",
    backNumber: "94",
    position: "IF",
    hand: "LHH",
    birth: "Aug 2 2004",
  },
  {
    name: "Kim Min-hyeok",
    team: "doosan",
    backNumber: "10",
    position: "IF",
    hand: "RHH",
    birth: "May 3 1996",
  },
  {
    name: "Lee Seon-woo",
    team: "doosan",
    backNumber: "24",
    position: "IF",
    hand: "LHH",
    birth: "Apr 4 2006",
  },
  {
    name: "Lee Yu-chan",
    team: "doosan",
    backNumber: "13",
    position: "2B",
    hand: "RHH",
    birth: "Aug 5 1998",
  },
  {
    name: "Oh Myeong-jin",
    team: "doosan",
    backNumber: "6",
    position: "2B",
    hand: "LHH",
    birth: "Sep 4 2001",
  },
  {
    name: "Park Gye-beom",
    team: "doosan",
    backNumber: "14",
    position: "2B",
    hand: "RHH",
    birth: "Jan 11 1996",
  },
  {
    name: "Park Ji-hoon",
    team: "doosan",
    backNumber: "37",
    position: "IF",
    hand: "RHH",
    birth: "Sep 7 2000",
  },
  {
    name: "Park Jun-soon",
    team: "doosan",
    backNumber: "52",
    position: "IF",
    hand: "RHH",
    birth: "Jul 13 2006",
  },
  {
    name: "Park Jun-young",
    team: "doosan",
    backNumber: "16",
    position: "SS",
    hand: "RHH",
    birth: "Aug 5 1997",
  },
  {
    name: "Yang Suk-hwan",
    team: "doosan",
    backNumber: "53",
    position: "1B",
    hand: "RHH",
    birth: "Jul 15 1991",
  },
  {
    name: "Yeo Tong-keon",
    team: "doosan",
    backNumber: "5",
    position: "2B",
    hand: "RHH",
    birth: "Aug 4 2005",
  },
  {
    name: "Jake Cave",
    team: "doosan",
    backNumber: "8",
    position: "RF",
    hand: "LHH",
    birth: "Dec 4 1992",
  },
  {
    name: "Choo Jae-hyun",
    team: "doosan",
    backNumber: "36",
    position: "OF",
    hand: "LHH",
    birth: "Feb 22 1999",
  },
  {
    name: "Jeon Da-min",
    team: "doosan",
    backNumber: "9",
    position: "OF",
    hand: "LHH",
    birth: "Aug 21 2001",
  },
  {
    name: "Jo Soo-haeng",
    team: "doosan",
    backNumber: "51",
    position: "RF",
    hand: "LHH",
    birth: "Aug 30 1993",
  },
  {
    name: "Jung Soo-bin",
    team: "doosan",
    backNumber: "31",
    position: "CF",
    hand: "LHH",
    birth: "Oct 7 1990",
  },
  {
    name: "Kang Hyun-gu",
    team: "doosan",
    backNumber: "60",
    position: "OF",
    hand: "RHH",
    birth: "Jun 16 2002",
  },
  {
    name: "Kim Dae-han",
    team: "doosan",
    backNumber: "27",
    position: "LF",
    hand: "RHH",
    birth: "Dec 6 2000",
  },
  {
    name: "Kim In-tae",
    team: "doosan",
    backNumber: "33",
    position: "LF",
    hand: "LHH",
    birth: "Jul 3 1994",
  },
  {
    name: "Kim Jae-hwan",
    team: "doosan",
    backNumber: "32",
    position: "LF",
    hand: "LHH",
    birth: "Sep 22 1988",
  },
  {
    name: "Kim Min-suk",
    team: "doosan",
    backNumber: "2",
    position: "LF",
    hand: "LHH",
    birth: "May 9 2004",
  },
  {
    name: "Bae Dong-hyun",
    team: "hanwha",
    backNumber: "61",
    position: "RP",
    hand: "RHP",
    birth: "Mar 16 1998",
  },
  {
    name: "Bae Min-seo",
    team: "hanwha",
    backNumber: "45",
    position: "RP",
    hand: "RHP",
    birth: "Nov 18 1999",
  },
  {
    name: "Cho Dong-uk",
    team: "hanwha",
    backNumber: "68",
    position: "SP/RP",
    hand: "LHP",
    birth: "Nov 2 2004",
  },
  {
    name: "Gwon Min-gyu",
    team: "hanwha",
    backNumber: "64",
    position: "RP",
    hand: "LHP",
    birth: "May 13 2006",
  },
  {
    name: "Han Seung-hyuk",
    team: "hanwha",
    backNumber: "26",
    position: "RP",
    hand: "RHP",
    birth: "Jan 3 1993",
  },
  {
    name: "Hwang Jun-seo",
    team: "hanwha",
    backNumber: "29",
    position: "SP/RP",
    hand: "LHP",
    birth: "Aug 22 2005",
  },
  {
    name: "Jang Ji-su",
    team: "hanwha",
    backNumber: "40",
    position: "RP",
    hand: "RHP",
    birth: "May 25 2000",
  },
  {
    name: "Jang Min-je",
    team: "hanwha",
    backNumber: "36",
    position: "RP",
    hand: "RHP",
    birth: "Mar 19 1990",
  },
  {
    name: "Jang Si-hwan",
    team: "hanwha",
    backNumber: "28",
    position: "RP",
    hand: "RHP",
    birth: "Nov 1 1987",
  },
  {
    name: "Jeong Woo-joo",
    team: "hanwha",
    backNumber: "43",
    position: "RP",
    hand: "RHP",
    birth: "Nov 7 2006",
  },
  {
    name: "Joo Hyun-sang",
    team: "hanwha",
    backNumber: "66",
    position: "RP",
    hand: "RHP",
    birth: "Aug 10 1992",
  },
  {
    name: "Kim Beom-su",
    team: "hanwha",
    backNumber: "47",
    position: "RP",
    hand: "LHP",
    birth: "Oct 3 1995",
  },
  {
    name: "Kim Do-been",
    team: "hanwha",
    backNumber: "62",
    position: "RP",
    hand: "RHP",
    birth: "Jan 5 2001",
  },
  {
    name: "Kim Jong-soo",
    team: "hanwha",
    backNumber: "38",
    position: "RP",
    hand: "RHP",
    birth: "Jun 3 1994",
  },
  {
    name: "Kim Ki-jung",
    team: "hanwha",
    backNumber: "15",
    position: "RP",
    hand: "LHP",
    birth: "Nov 16 2002",
  },
  {
    name: "Kim Kyu-yeon",
    team: "hanwha",
    backNumber: "60",
    position: "RP",
    hand: "RHP",
    birth: "Aug 23 2002",
  },
  {
    name: "Kim Min-woo",
    team: "hanwha",
    backNumber: "53",
    position: "RP",
    hand: "RHP",
    birth: "Jul 25 1995",
  },
  {
    name: "Kim Seo-hyeon",
    team: "hanwha",
    backNumber: "44",
    position: "CP",
    hand: "RHP",
    birth: "May 31 2004",
  },
  {
    name: "Kim Seung-il",
    team: "hanwha",
    backNumber: "14",
    position: "RP",
    hand: "RHP",
    birth: "Jul 7 2001",
  },
  {
    name: "Lee Min-woo",
    team: "hanwha",
    backNumber: "27",
    position: "RP",
    hand: "RHP",
    birth: "Feb 9 1993",
  },
  {
    name: "Lee Sang-kyu",
    team: "hanwha",
    backNumber: "18",
    position: "RP",
    hand: "RHP",
    birth: "Oct 20 1996",
  },
  {
    name: "Lee Tae-yang",
    team: "hanwha",
    backNumber: "46",
    position: "RP",
    hand: "RHP",
    birth: "Jul 3 1990",
  },
  {
    name: "Moon Dong-ju",
    team: "hanwha",
    backNumber: "1",
    position: "SP",
    hand: "RHP",
    birth: "Dec 23 2003",
  },
  {
    name: "Park Sang-won",
    team: "hanwha",
    backNumber: "58",
    position: "RP",
    hand: "RHP",
    birth: "Sep 9 1994",
  },
  {
    name: "Cody Ponce",
    team: "hanwha",
    backNumber: "30",
    position: "SP",
    hand: "RHP",
    birth: "Apr 25 1994",
  },
  {
    name: "Ryu Hyun-jin",
    team: "hanwha",
    backNumber: "99",
    position: "SP",
    hand: "LHP",
    birth: "Mar 25 1987",
  },
  {
    name: "Sung Ji-hun",
    team: "hanwha",
    backNumber: "57",
    position: "RP",
    hand: "LHP",
    birth: "Jan 29 2000",
  },
  {
    name: "Um Sang-back",
    team: "hanwha",
    backNumber: "11",
    position: "SP",
    hand: "RHP",
    birth: "Oct 4 1996",
  },
  {
    name: "Ryan Weiss",
    team: "hanwha",
    backNumber: "55",
    position: "SP",
    hand: "RHP",
    birth: "Dec 10 1996",
  },
  {
    name: "Won Jong-hyeok",
    team: "hanwha",
    backNumber: "48",
    position: "RP",
    hand: "RHP",
    birth: "Aug 27 2005",
  },
  {
    name: "Yun Dae-kyung",
    team: "hanwha",
    backNumber: "5",
    position: "RP",
    hand: "RHP",
    birth: "Apr 9 1994",
  },
  {
    name: "Chang Kyu-hyun",
    team: "hanwha",
    backNumber: "32",
    position: "C",
    hand: "LHH",
    birth: "Jun 28 2002",
  },
  {
    name: "Choi Jae-hoon",
    team: "hanwha",
    backNumber: "13",
    position: "C",
    hand: "RHH",
    birth: "Aug 27 1989",
  },
  {
    name: "Han Ji-youn",
    team: "hanwha",
    backNumber: "67",
    position: "C",
    hand: "RHH",
    birth: "Apr 10 2006",
  },
  {
    name: "Heo In-seo",
    team: "hanwha",
    backNumber: "59",
    position: "C",
    hand: "RHH",
    birth: "Jul 11 2003",
  },
  {
    name: "Lee Jae-won",
    team: "hanwha",
    backNumber: "20",
    position: "C",
    hand: "RHH",
    birth: "Feb 24 1988",
  },
  {
    name: "Park Sang-un",
    team: "hanwha",
    backNumber: "42",
    position: "C",
    hand: "RHH",
    birth: "Mar 3 1997",
  },
  {
    name: "An Chi-hong",
    team: "hanwha",
    backNumber: "3",
    position: "2B",
    hand: "RHH",
    birth: "Jul 2 1990",
  },
  {
    name: "Bae Seung-su",
    team: "hanwha",
    backNumber: "98",
    position: "IF",
    hand: "RHH",
    birth: "May 15 2006",
  },
  {
    name: "Chae Eun-seong",
    team: "hanwha",
    backNumber: "22",
    position: "1B",
    hand: "RHH",
    birth: "Feb 6 1990",
  },
  {
    name: "Ha Ju-suk",
    team: "hanwha",
    backNumber: "16",
    position: "SS",
    hand: "LHH",
    birth: "Feb 25 1994",
  },
  {
    name: "Hwang Young-mook",
    team: "hanwha",
    backNumber: "95",
    position: "2B",
    hand: "LHH",
    birth: "Oct 16 1999",
  },
  {
    name: "Jung Min-kyu",
    team: "hanwha",
    backNumber: "65",
    position: "IF",
    hand: "RHH",
    birth: "Jan 10 2003",
  },
  {
    name: "Kim In-hwan",
    team: "hanwha",
    backNumber: "37",
    position: "LF",
    hand: "LHH",
    birth: "Jan 28 1994",
  },
  {
    name: "Kwon Kwang-min",
    team: "hanwha",
    backNumber: "17",
    position: "LF",
    hand: "LHH",
    birth: "Dec 12 1997",
  },
  {
    name: "Lee Do-yun",
    team: "hanwha",
    backNumber: "7",
    position: "2B",
    hand: "LHH",
    birth: "Oct 7 1996",
  },
  {
    name: "Lee Seung-hyeon",
    team: "hanwha",
    backNumber: "60",
    position: "IF",
    hand: "LHH",
    birth: "Jul 23 2002",
  },
  {
    name: "Moon Hyun-bin",
    team: "hanwha",
    backNumber: "51",
    position: "3B",
    hand: "LHH",
    birth: "Apr 20 2004",
  },
  {
    name: "Roh Si-hwan",
    team: "hanwha",
    backNumber: "8",
    position: "3B",
    hand: "RHH",
    birth: "Dec 3 2000",
  },
  {
    name: "Sim Woo-jun",
    team: "hanwha",
    backNumber: "2",
    position: "SS",
    hand: "RHH",
    birth: "Apr 28 1995",
  },
  {
    name: "Choi In-ho",
    team: "hanwha",
    backNumber: "41",
    position: "RF",
    hand: "LHH",
    birth: "Jan 30 2000",
  },
  {
    name: "Choi Jun-seo",
    team: "hanwha",
    backNumber: "94",
    position: "OF",
    hand: "LHH",
    birth: "Jun 29 2000",
  },
  {
    name: "Estevan Florial",
    team: "hanwha",
    backNumber: "34",
    position: "OF",
    hand: "LHH",
    birth: "Nov 25 1997",
  },
  {
    name: "Kim Tae-yean",
    team: "hanwha",
    backNumber: "25",
    position: "RF",
    hand: "RHH",
    birth: "Jun 10 1997",
  },
  {
    name: "Lee Jin-young",
    team: "hanwha",
    backNumber: "10",
    position: "CF",
    hand: "RHH",
    birth: "Jul 21 1997",
  },
  {
    name: "Lee Min-jae",
    team: "hanwha",
    backNumber: "57",
    position: "OF",
    hand: "LHH",
    birth: "Mar 7 2004",
  },
  {
    name: "Lee Sang-hyuck",
    team: "hanwha",
    backNumber: "9",
    position: "OF",
    hand: "LHH",
    birth: "Sep 14 2001",
  },
  {
    name: "Lee Won-seok",
    team: "hanwha",
    backNumber: "50",
    position: "LF",
    hand: "RHH",
    birth: "Mar 31 1999",
  },
  {
    name: "Liberato Luis",
    team: "hanwha",
    backNumber: "0",
    position: "OF",
    hand: "LHH",
    birth: "Dec 18 1995",
  },
  {
    name: "Lim Jong-chan",
    team: "hanwha",
    backNumber: "24",
    position: "RF",
    hand: "LHH",
    birth: "Sep 28 2001",
  },
  {
    name: "Yoo Ro-gyeol",
    team: "hanwha",
    backNumber: "33",
    position: "RF",
    hand: "RHH",
    birth: "May 30 2000",
  },
  {
    name: "Cho Sang-woo",
    team: "kia",
    backNumber: "11",
    position: "RP",
    hand: "RHP",
    birth: "Sep 4 1994",
  },
  {
    name: "Choi Ji-min",
    team: "kia",
    backNumber: "39",
    position: "RP",
    hand: "LHP",
    birth: "Sep 10 2003",
  },
  {
    name: "Hong Won-bin",
    team: "kia",
    backNumber: "30",
    position: "RP",
    hand: "RHP",
    birth: "Oct 16 2000",
  },
  {
    name: "Hwang Dong-ha",
    team: "kia",
    backNumber: "41",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jul 30 2002",
  },
  {
    name: "Im Gi-yeong",
    team: "kia",
    backNumber: "17",
    position: "RP",
    hand: "RHP",
    birth: "Apr 16 1993",
  },
  {
    name: "Jang Jae-hyeok",
    team: "kia",
    backNumber: "38",
    position: "RP",
    hand: "RHP",
    birth: "Aug 2 2001",
  },
  {
    name: "Jeon Sang-hyun",
    team: "kia",
    backNumber: "51",
    position: "RP",
    hand: "RHP",
    birth: "Apr 18 1996",
  },
  {
    name: "Jung Hai-young",
    team: "kia",
    backNumber: "62",
    position: "CP",
    hand: "RHP",
    birth: "Aug 23 2001",
  },
  {
    name: "Kim Dae-yu",
    team: "kia",
    backNumber: "69",
    position: "RP",
    hand: "LHP",
    birth: "May 8 1991",
  },
  {
    name: "Kim Do-hyeon",
    team: "kia",
    backNumber: "60",
    position: "SP",
    hand: "RHP",
    birth: "Sep 15 2000",
  },
  {
    name: "Kim Hyeon-su",
    team: "kia",
    backNumber: "32",
    position: "RP",
    hand: "RHP",
    birth: "Jul 10 2000",
  },
  {
    name: "Kim Jeong-yeop",
    team: "kia",
    backNumber: "46",
    position: "RP",
    hand: "RHP",
    birth: "Apr 18 2006",
  },
  {
    name: "Kim Keon-kuk",
    team: "kia",
    backNumber: "43",
    position: "RP",
    hand: "RHP",
    birth: "Feb 2 1988",
  },
  {
    name: "Kim Ki-hoon",
    team: "kia",
    backNumber: "53",
    position: "RP",
    hand: "LHP",
    birth: "Jan 3 2000",
  },
  {
    name: "Kim Min-jae",
    team: "kia",
    backNumber: "30",
    position: "RP",
    hand: "RHP",
    birth: "Jul 8 2003",
  },
  {
    name: "Kim Min-ju",
    team: "kia",
    backNumber: "49",
    position: "RP",
    hand: "RHP",
    birth: "Sep 8 2002",
  },
  {
    name: "Kim Sa-yun",
    team: "kia",
    backNumber: "21",
    position: "RP",
    hand: "LHP",
    birth: "Jun 8 1994",
  },
  {
    name: "Kim Seung-hyeon",
    team: "kia",
    backNumber: "24",
    position: "RP",
    hand: "RHP",
    birth: "Jul 9 1992",
  },
  {
    name: "Kim Tae-hyeong",
    team: "kia",
    backNumber: "10",
    position: "RP",
    hand: "RHP",
    birth: "Dec 15 2006",
  },
  {
    name: "Kwak Do-gyu",
    team: "kia",
    backNumber: "0",
    position: "RP",
    hand: "LHP",
    birth: "Apr 12 2004",
  },
  {
    name: "Lee Eui-lee",
    team: "kia",
    backNumber: "48",
    position: "RP",
    hand: "LHP",
    birth: "Jun 16 2002",
  },
  {
    name: "Lee Ho-min",
    team: "kia",
    backNumber: "63",
    position: "RP",
    hand: "RHP",
    birth: "Aug 26 2006",
  },
  {
    name: "Lee Hyeong-beom",
    team: "kia",
    backNumber: "28",
    position: "RP",
    hand: "RHP",
    birth: "Feb 27 1994",
  },
  {
    name: "Lee Jun-young",
    team: "kia",
    backNumber: "20",
    position: "RP",
    hand: "LHP",
    birth: "Aug 10 1992",
  },
  {
    name: "James Naile",
    team: "kia",
    backNumber: "40",
    position: "SP",
    hand: "RHP",
    birth: "Feb 8 1993",
  },
  {
    name: "Adam Oller",
    team: "kia",
    backNumber: "33",
    position: "SP",
    hand: "RHP",
    birth: "Oct 17 1994",
  },
  {
    name: "Park Jun-pyo",
    team: "kia",
    backNumber: "31",
    position: "RP",
    hand: "RHP",
    birth: "Jun 26 1992",
  },
  {
    name: "Sung Yeong-tak",
    team: "kia",
    backNumber: "65",
    position: "RP",
    hand: "RHP",
    birth: "Jul 28 2004",
  },
  {
    name: "Yang Hyeon-jong",
    team: "kia",
    backNumber: "54",
    position: "SP",
    hand: "LHP",
    birth: "Mar 1 1988",
  },
  {
    name: "Yang Su-ho",
    team: "kia",
    backNumber: "59",
    position: "RP",
    hand: "RHP",
    birth: "Sep 9 2006",
  },
  {
    name: "Yoo Seung-cheol",
    team: "kia",
    backNumber: "50",
    position: "RP",
    hand: "RHP",
    birth: "Mar 2 1998",
  },
  {
    name: "Yoon Joong-hyun",
    team: "kia",
    backNumber: "19",
    position: "RP",
    hand: "RHP",
    birth: "Apr 25 1995",
  },
  {
    name: "Yoon Young-cheol",
    team: "kia",
    backNumber: "13",
    position: "SP",
    hand: "LHP",
    birth: "Apr 20 2004",
  },
  {
    name: "You Ji-sung",
    team: "kia",
    backNumber: "4",
    position: "RP",
    hand: "LHP",
    birth: "Nov 15 2000",
  },
  {
    name: "Han Jun-su",
    team: "kia",
    backNumber: "55",
    position: "C",
    hand: "LHH",
    birth: "Feb 13 1999",
  },
  {
    name: "Han Seung-taek",
    team: "kia",
    backNumber: "26",
    position: "C",
    hand: "RHH",
    birth: "Jun 21 1994",
  },
  {
    name: "Joo Hyo-sang",
    team: "kia",
    backNumber: "22",
    position: "C",
    hand: "LHH",
    birth: "Nov 11 1997",
  },
  {
    name: "Kim Tae-gun",
    team: "kia",
    backNumber: "42",
    position: "C",
    hand: "RHH",
    birth: "Dec 30 1989",
  },
  {
    name: "Lee Sang-jun",
    team: "kia",
    backNumber: "44",
    position: "C",
    hand: "RHH",
    birth: "Dec 13 2005",
  },
  {
    name: "Byun Woo-hyuk",
    team: "kia",
    backNumber: "29",
    position: "1B",
    hand: "RHH",
    birth: "Mar 18 2000",
  },
  {
    name: "Choi Jeong-yong",
    team: "kia",
    backNumber: "23",
    position: "2B",
    hand: "LHH",
    birth: "Oct 24 1996",
  },
  {
    name: "Hong Jong-pyo",
    team: "kia",
    backNumber: "6",
    position: "2B",
    hand: "LHH",
    birth: "May 2 2000",
  },
  {
    name: "Hwang Dae-in",
    team: "kia",
    backNumber: "52",
    position: "IF",
    hand: "RHH",
    birth: "Feb 10 1996",
  },
  {
    name: "Jung Hae-won",
    team: "kia",
    backNumber: "64",
    position: "IF",
    hand: "RHH",
    birth: "May 21 2004",
  },
  {
    name: "Kim Do-yeong",
    team: "kia",
    backNumber: "5",
    position: "3B",
    hand: "RHH",
    birth: "Oct 2 2003",
  },
  {
    name: "Kim Doo-hyun",
    team: "kia",
    backNumber: "2",
    position: "IF",
    hand: "RHH",
    birth: "Apr 25 2003",
  },
  {
    name: "Kim Kyu-sung",
    team: "kia",
    backNumber: "14",
    position: "SS",
    hand: "LHH",
    birth: "Mar 8 1997",
  },
  {
    name: "Kim Sun-bin",
    team: "kia",
    backNumber: "3",
    position: "2B",
    hand: "RHH",
    birth: "Dec 18 1989",
  },
  {
    name: "Oh Sun-woo",
    team: "kia",
    backNumber: "56",
    position: "IF",
    hand: "LHH",
    birth: "Dec 13 1996",
  },
  {
    name: "Park Chan-ho",
    team: "kia",
    backNumber: "1",
    position: "SS",
    hand: "RHH",
    birth: "Jun 5 1995",
  },
  {
    name: "Park Min",
    team: "kia",
    backNumber: "2",
    position: "IF",
    hand: "RHH",
    birth: "Jun 5 2001",
  },
  {
    name: "Seo Geon-chang",
    team: "kia",
    backNumber: "58",
    position: "2B",
    hand: "LHH",
    birth: "Aug 22 1989",
  },
  {
    name: "Patrick Wisdom",
    team: "kia",
    backNumber: "45",
    position: "IF",
    hand: "RHH",
    birth: "Aug 27 1991",
  },
  {
    name: "Yoon Do-hyun",
    team: "kia",
    backNumber: "9",
    position: "2B",
    hand: "RHH",
    birth: "May 7 2003",
  },
  {
    name: "Choi Hyoung-woo",
    team: "kia",
    backNumber: "34",
    position: "LF",
    hand: "LHH",
    birth: "Dec 16 1983",
  },
  {
    name: "Choi Won-jun",
    team: "kia",
    backNumber: "16",
    position: "RF",
    hand: "LHH",
    birth: "Mar 23 1997",
  },
  {
    name: "Kim Ho-ryung",
    team: "kia",
    backNumber: "27",
    position: "CF",
    hand: "RHH",
    birth: "Apr 30 1992",
  },
  {
    name: "Kim Seok-hwan",
    team: "kia",
    backNumber: "35",
    position: "OF",
    hand: "LHH",
    birth: "Feb 28 1999",
  },
  {
    name: "Ko Jong-wook",
    team: "kia",
    backNumber: "57",
    position: "OF",
    hand: "LHH",
    birth: "Jan 11 1989",
  },
  {
    name: "Lee Chang-jin",
    team: "kia",
    backNumber: "8",
    position: "OF",
    hand: "RHH",
    birth: "Mar 4 1991",
  },
  {
    name: "Lee Woo-sung",
    team: "kia",
    backNumber: "25",
    position: "LF",
    hand: "RHH",
    birth: "Jul 17 1994",
  },
  {
    name: "Na Sung-bum",
    team: "kia",
    backNumber: "47",
    position: "RF",
    hand: "LHH",
    birth: "Oct 3 1989",
  },
  {
    name: "Park Jae-hyun",
    team: "kia",
    backNumber: "36",
    position: "OF",
    hand: "LHH",
    birth: "Dec 8 2006",
  },
  {
    name: "Park Jung-woo",
    team: "kia",
    backNumber: "15",
    position: "LF",
    hand: "LHH",
    birth: "Feb 1 1998",
  },
  {
    name: "Raul Alcántara",
    team: "kiwoom",
    backNumber: "54",
    position: "SP/RP",
    hand: "RHP",
    birth: "Dec 4 1992",
  },
  {
    name: "Cho Young-gun",
    team: "kiwoom",
    backNumber: "20",
    position: "SP",
    hand: "RHP",
    birth: "Feb 4 1999",
  },
  {
    name: "Chung Se-young",
    team: "kiwoom",
    backNumber: "77",
    position: "RP",
    hand: "LHP",
    birth: "Sep 23 2006",
  },
  {
    name: "Ha Yeong-min",
    team: "kiwoom",
    backNumber: "50",
    position: "SP",
    hand: "RHP",
    birth: "May 7 1995",
  },
  {
    name: "Jang Pill-joon",
    team: "kiwoom",
    backNumber: "18",
    position: "RP",
    hand: "RHP",
    birth: "Apr 8 1988",
  },
  {
    name: "Jhun Jun-pyo",
    team: "kiwoom",
    backNumber: "62",
    position: "SP/RP",
    hand: "RHP",
    birth: "May 7 2005",
  },
  {
    name: "Ju Seung-woo",
    team: "kiwoom",
    backNumber: "30",
    position: "CP",
    hand: "RHP",
    birth: "Jan 30 2000",
  },
  {
    name: "Jung Hyun-woo",
    team: "kiwoom",
    backNumber: "13",
    position: "SP/RP",
    hand: "LHP",
    birth: "Apr 13 2006",
  },
  {
    name: "Kim Dong-kyu",
    team: "kiwoom",
    backNumber: "99",
    position: "RP",
    hand: "RHP",
    birth: "Jul 9 2004",
  },
  {
    name: "Kim In-beom",
    team: "kiwoom",
    backNumber: "67",
    position: "RP",
    hand: "RHP",
    birth: "Jan 12 2000",
  },
  {
    name: "Kim Seo-jun",
    team: "kiwoom",
    backNumber: "59",
    position: "RP",
    hand: "RHP",
    birth: "Dec 22 2006",
  },
  {
    name: "Kim Seon-gi",
    team: "kiwoom",
    backNumber: "49",
    position: "SP",
    hand: "RHP",
    birth: "Sep 1 1991",
  },
  {
    name: "Kim Seong-min",
    team: "kiwoom",
    backNumber: "8",
    position: "RP",
    hand: "LHP",
    birth: "Apr 26 1994",
  },
  {
    name: "Kim Yeon-ju",
    team: "kiwoom",
    backNumber: "68",
    position: "SP/RP",
    hand: "RHP",
    birth: "Feb 27 2004",
  },
  {
    name: "Kim Yun-ha",
    team: "kiwoom",
    backNumber: "19",
    position: "SP",
    hand: "RHP",
    birth: "Mar 7 2005",
  },
  {
    name: "Lee Jong-min",
    team: "kiwoom",
    backNumber: "45",
    position: "RP",
    hand: "LHP",
    birth: "Jun 4 2001",
  },
  {
    name: "Lee Jun-woo",
    team: "kiwoom",
    backNumber: "21",
    position: "RP",
    hand: "RHP",
    birth: "Mar 2 2001",
  },
  {
    name: "Lee Kang-jun",
    team: "kiwoom",
    backNumber: "11",
    position: "RP",
    hand: "RHP",
    birth: "Dec 14 2001",
  },
  {
    name: "Lim Jin-muk",
    team: "kiwoom",
    backNumber: "82",
    position: "RP",
    hand: "RHP",
    birth: "Apr 23 2006",
  },
  {
    name: "Oh Seok-joo",
    team: "kiwoom",
    backNumber: "31",
    position: "RP",
    hand: "RHP",
    birth: "Apr 14 1998",
  },
  {
    name: "Park Beom-jun",
    team: "kiwoom",
    backNumber: "45",
    position: "RP",
    hand: "RHP",
    birth: "May 28 2004",
  },
  {
    name: "Park Jeong-hun",
    team: "kiwoom",
    backNumber: "94",
    position: "RP",
    hand: "LHP",
    birth: "Mar 23 2006",
  },
  {
    name: "Park Ju-seong",
    team: "kiwoom",
    backNumber: "0",
    position: "RP",
    hand: "RHP",
    birth: "Nov 9 2000",
  },
  {
    name: "Park Yun-sung",
    team: "kiwoom",
    backNumber: "35",
    position: "RP",
    hand: "RHP",
    birth: "Feb 8 2004",
  },
  {
    name: "Kenny Rosenberg",
    team: "kiwoom",
    backNumber: "22",
    position: "SP",
    hand: "LHP",
    birth: "Jul 9 1995",
  },
  {
    name: "Son Him-chan",
    team: "kiwoom",
    backNumber: "37",
    position: "RP",
    hand: "RHP",
    birth: "Jul 17 2002",
  },
  {
    name: "Son Hyeon-gi",
    team: "kiwoom",
    backNumber: "63",
    position: "RP",
    hand: "LHP",
    birth: "Oct 22 2005",
  },
  {
    name: "Wells Lachlan",
    team: "kiwoom",
    backNumber: "48",
    position: "RP",
    hand: "LHP",
    birth: "Feb 27 1997",
  },
  {
    name: "Won Jong-hyan",
    team: "kiwoom",
    backNumber: "46",
    position: "RP",
    hand: "RHP",
    birth: "Jul 31 1987",
  },
  {
    name: "Yang Ji-yul",
    team: "kiwoom",
    backNumber: "55",
    position: "RP",
    hand: "RHP",
    birth: "Dec 16 1998",
  },
  {
    name: "Yoon Hyun",
    team: "kiwoom",
    backNumber: "96",
    position: "SP/RP",
    hand: "RHP",
    birth: "Oct 20 2006",
  },
  {
    name: "Yun Seok-won",
    team: "kiwoom",
    backNumber: "95",
    position: "RP",
    hand: "LHP",
    birth: "Jul 4 2003",
  },
  {
    name: "Kim Dong-heon",
    team: "kiwoom",
    backNumber: "47",
    position: "C",
    hand: "RHH",
    birth: "Jul 15 2004",
  },
  {
    name: "Kim Gun-hee",
    team: "kiwoom",
    backNumber: "12",
    position: "C",
    hand: "RHH",
    birth: "Nov 7 2004",
  },
  {
    name: "Kim Jae-hyun",
    team: "kiwoom",
    backNumber: "32",
    position: "C",
    hand: "RHH",
    birth: "Mar 18 1993",
  },
  {
    name: "Park Seong-bhin",
    team: "kiwoom",
    backNumber: "56",
    position: "C",
    hand: "RHH",
    birth: "Apr 21 2004",
  },
  {
    name: "Choi Joo-hwan",
    team: "kiwoom",
    backNumber: "53",
    position: "1B",
    hand: "LHH",
    birth: "Feb 28 1988",
  },
  {
    name: "Eo Joon-seo",
    team: "kiwoom",
    backNumber: "92",
    position: "IF",
    hand: "LHH",
    birth: "Nov 27 2006",
  },
  {
    name: "Gwon Hyuk-bin",
    team: "kiwoom",
    backNumber: "71",
    position: "IF",
    hand: "RHH",
    birth: "Nov 4 2005",
  },
  {
    name: "Jeon Tae-hyun",
    team: "kiwoom",
    backNumber: "97",
    position: "IF",
    hand: "LHH",
    birth: "Mar 2 2006",
  },
  {
    name: "Kang Jin-sung",
    team: "kiwoom",
    backNumber: "27",
    position: "IF",
    hand: "RHH",
    birth: "Oct 19 1993",
  },
  {
    name: "Kim Byeong-hwi",
    team: "kiwoom",
    backNumber: "23",
    position: "SS",
    hand: "RHH",
    birth: "Feb 16 2001",
  },
  {
    name: "Kim Tae-jin",
    team: "kiwoom",
    backNumber: "1",
    position: "2B",
    hand: "LHH",
    birth: "Oct 7 1995",
  },
  {
    name: "Kim Woong-bin",
    team: "kiwoom",
    backNumber: "10",
    position: "IF",
    hand: "LHH",
    birth: "Feb 9 1996",
  },
  {
    name: "Ko Young-woo",
    team: "kiwoom",
    backNumber: "44",
    position: "3B",
    hand: "RHH",
    birth: "Jun 21 2001",
  },
  {
    name: "Lee Jae-sang",
    team: "kiwoom",
    backNumber: "5",
    position: "IF",
    hand: "RHH",
    birth: "Apr 17 2005",
  },
  {
    name: "Lee Ju-hyeong",
    team: "kiwoom",
    backNumber: "58",
    position: "IF",
    hand: "LHH",
    birth: "Jul 5 2002",
  },
  {
    name: "Lee Seung-won",
    team: "kiwoom",
    backNumber: "22",
    position: "SS",
    hand: "RHH",
    birth: "Jul 2 2004",
  },
  {
    name: "Lee Won-seok",
    team: "kiwoom",
    backNumber: "17",
    position: "IF",
    hand: "RHH",
    birth: "Oct 21 1986",
  },
  {
    name: "Oh Sun-jin",
    team: "kiwoom",
    backNumber: "60",
    position: "SS",
    hand: "RHH",
    birth: "Jul 7 1989",
  },
  {
    name: "Seo Yoo-sin",
    team: "kiwoom",
    backNumber: "98",
    position: "IF",
    hand: "RHH",
    birth: "Aug 17 2000",
  },
  {
    name: "Song Ji-hoo",
    team: "kiwoom",
    backNumber: "86",
    position: "IF",
    hand: "RHH",
    birth: "Jan 8 2005",
  },
  {
    name: "Song Sung-mun",
    team: "kiwoom",
    backNumber: "24",
    position: "3B",
    hand: "LHH",
    birth: "Aug 29 1996",
  },
  {
    name: "Yang Hyun-jong",
    team: "kiwoom",
    backNumber: "70",
    position: "IF",
    hand: "RHH",
    birth: "Aug 15 2006",
  },
  {
    name: "Yeo Dong-uk",
    team: "kiwoom",
    backNumber: "93",
    position: "IF",
    hand: "RHH",
    birth: "Nov 10 2005",
  },
  {
    name: "Byeon Sang-kwon",
    team: "kiwoom",
    backNumber: "9",
    position: "LF",
    hand: "LHH",
    birth: "Apr 4 1997",
  },
  {
    name: "Ruben Cardenas",
    team: "kiwoom",
    backNumber: "4",
    position: "RF",
    hand: "RHH",
    birth: "Oct 10 1997",
  },
  {
    name: "Garrett Stone",
    team: "kiwoom",
    backNumber: "26",
    position: "OF",
    hand: "RHH",
    birth: "Nov 22 1995",
  },
  {
    name: "Im Ji-yeol",
    team: "kiwoom",
    backNumber: "29",
    position: "LF",
    hand: "RHH",
    birth: "Aug 22 1995",
  },
  {
    name: "Jang Jae-young",
    team: "kiwoom",
    backNumber: "23",
    position: "RF",
    hand: "RHH",
    birth: "May 10 2002",
  },
  {
    name: "Ju Seong-won",
    team: "kiwoom",
    backNumber: "25",
    position: "RF",
    hand: "RHH",
    birth: "Aug 30 2000",
  },
  {
    name: "Kim Dong-yub",
    team: "kiwoom",
    backNumber: "38",
    position: "OF",
    hand: "RHH",
    birth: "Jul 24 1990",
  },
  {
    name: "Lee Hyung-jong",
    team: "kiwoom",
    backNumber: "36",
    position: "LF",
    hand: "RHH",
    birth: "Jun 7 1989",
  },
  {
    name: "Lee Ju-hyoung",
    team: "kiwoom",
    backNumber: "2",
    position: "CF",
    hand: "LHH",
    birth: "Apr 2 2001",
  },
  {
    name: "Lee Yong-kyu",
    team: "kiwoom",
    backNumber: "15",
    position: "OF",
    hand: "LHH",
    birth: "Aug 26 1985",
  },
  {
    name: "Lim Byeong-wuk",
    team: "kiwoom",
    backNumber: "6",
    position: "CF",
    hand: "LHH",
    birth: "Sep 30 1995",
  },
  {
    name: "Park Ju-hong",
    team: "kiwoom",
    backNumber: "57",
    position: "LF",
    hand: "LHH",
    birth: "Apr 16 2001",
  },
  {
    name: "Park Su-jong",
    team: "kiwoom",
    backNumber: "14",
    position: "CF",
    hand: "RHH",
    birth: "Feb 25 1999",
  },
  {
    name: "Yasiel Puig",
    team: "kiwoom",
    backNumber: "66",
    position: "LF",
    hand: "RHH",
    birth: "Dec 7 1990",
  },
  {
    name: "Won Sung-jun",
    team: "kiwoom",
    backNumber: "33",
    position: "RF",
    hand: "LHH",
    birth: "Mar 31 2000",
  },
  {
    name: "Bae Je-seong",
    team: "kt",
    backNumber: "19",
    position: "RP",
    hand: "RHP",
    birth: "Sep 29 1996",
  },
  {
    name: "Choi Dong-hwan",
    team: "kt",
    backNumber: "16",
    position: "RP",
    hand: "RHP",
    birth: "Sep 19 1989",
  },
  {
    name: "Choi Yong-jun",
    team: "kt",
    backNumber: "92",
    position: "RP",
    hand: "RHP",
    birth: "Dec 19 2001",
  },
  {
    name: "William Cuevas",
    team: "kt",
    backNumber: "32",
    position: "SP",
    hand: "RHP",
    birth: "Oct 14 1990",
  },
  {
    name: "Han Cha-hyeon",
    team: "kt",
    backNumber: "59",
    position: "RP",
    hand: "RHP",
    birth: "Nov 30 1998",
  },
  {
    name: "Jeon Yong-ju",
    team: "kt",
    backNumber: "29",
    position: "RP",
    hand: "LHP",
    birth: "Feb 12 2000",
  },
  {
    name: "Enmanuel De Jesus",
    team: "kt",
    backNumber: "65",
    position: "SP",
    hand: "LHP",
    birth: "Dec 10 1996",
  },
  {
    name: "Jo Yi-hyeon",
    team: "kt",
    backNumber: "54",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jun 27 1995",
  },
  {
    name: "Ju Kwon",
    team: "kt",
    backNumber: "38",
    position: "RP",
    hand: "RHP",
    birth: "May 31 1995",
  },
  {
    name: "Kang Geon",
    team: "kt",
    backNumber: "99",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jul 12 2004",
  },
  {
    name: "Kim Dong-hyun",
    team: "kt",
    backNumber: "40",
    position: "RP",
    hand: "RHP",
    birth: "Jan 21 2006",
  },
  {
    name: "Kim Jae-won",
    team: "kt",
    backNumber: "43",
    position: "RP",
    hand: "RHP",
    birth: "Aug 21 2006",
  },
  {
    name: "Kim Ju-wan",
    team: "kt",
    backNumber: "98",
    position: "RP",
    hand: "LHP",
    birth: "Oct 7 1999",
  },
  {
    name: "Kim Min-su",
    team: "kt",
    backNumber: "26",
    position: "RP",
    hand: "RHP",
    birth: "Jul 24 1992",
  },
  {
    name: "Ko Young-pyo",
    team: "kt",
    backNumber: "1",
    position: "SP",
    hand: "RHP",
    birth: "Sep 16 1991",
  },
  {
    name: "Lee Chae-ho",
    team: "kt",
    backNumber: "17",
    position: "RP",
    hand: "RHP",
    birth: "Nov 23 1998",
  },
  {
    name: "Lee Hyun-min",
    team: "kt",
    backNumber: "49",
    position: "RP",
    hand: "RHP",
    birth: "Oct 13 2001",
  },
  {
    name: "Lee Jung-hyun",
    team: "kt",
    backNumber: "21",
    position: "RP",
    hand: "RHP",
    birth: "Dec 5 1997",
  },
  {
    name: "Lee Sang-dong",
    team: "kt",
    backNumber: "37",
    position: "RP",
    hand: "RHP",
    birth: "Nov 24 1995",
  },
  {
    name: "Lee Sun-woo",
    team: "kt",
    backNumber: "61",
    position: "RP",
    hand: "RHP",
    birth: "Sep 19 2000",
  },
  {
    name: "Lee Tae-gyu",
    team: "kt",
    backNumber: "45",
    position: "RP",
    hand: "RHP",
    birth: "Feb 21 2000",
  },
  {
    name: "Mon Yong-ik",
    team: "kt",
    backNumber: "18",
    position: "RP",
    hand: "RHP",
    birth: "Feb 4 1995",
  },
  {
    name: "Oh Won-seok",
    team: "kt",
    backNumber: "47",
    position: "SP",
    hand: "LHP",
    birth: "Apr 23 2001",
  },
  {
    name: "Park Geon-woo",
    team: "kt",
    backNumber: "46",
    position: "RP",
    hand: "RHP",
    birth: "Nov 28 2006",
  },
  {
    name: "Park Yeong-hyun",
    team: "kt",
    backNumber: "60",
    position: "CP",
    hand: "RHP",
    birth: "Oct 11 2003",
  },
  {
    name: "Seong Jae-heon",
    team: "kt",
    backNumber: "15",
    position: "RP",
    hand: "LHP",
    birth: "Dec 22 1997",
  },
  {
    name: "So Hyeong-jun",
    team: "kt",
    backNumber: "30",
    position: "SP",
    hand: "RHP",
    birth: "Sep 16 2001",
  },
  {
    name: "Son Dong-hyun",
    team: "kt",
    backNumber: "41",
    position: "RP",
    hand: "RHP",
    birth: "Jan 23 2001",
  },
  {
    name: "Weon Sang-hyun",
    team: "kt",
    backNumber: "63",
    position: "RP",
    hand: "RHP",
    birth: "Oct 16 2004",
  },
  {
    name: "Woo Kyu-min",
    team: "kt",
    backNumber: "12",
    position: "RP",
    hand: "RHP",
    birth: "Jan 21 1985",
  },
  {
    name: "Yook Chung-myoung",
    team: "kt",
    backNumber: "64",
    position: "RP",
    hand: "RHP",
    birth: "Jul 18 2005",
  },
  {
    name: "Cho Dae-hyun",
    team: "kt",
    backNumber: "42",
    position: "C",
    hand: "RHH",
    birth: "Aug 6 1999",
  },
  {
    name: "Jang Sung-woo",
    team: "kt",
    backNumber: "22",
    position: "C",
    hand: "RHH",
    birth: "Jan 17 1990",
  },
  {
    name: "Kang Baek-ho",
    team: "kt",
    backNumber: "50",
    position: "C",
    hand: "LHH",
    birth: "Jul 29 1999",
  },
  {
    name: "Kang Hyeon-woo",
    team: "kt",
    backNumber: "55",
    position: "C",
    hand: "RHH",
    birth: "Apr 13 2001",
  },
  {
    name: "Kim Jun-tae",
    team: "kt",
    backNumber: "44",
    position: "C",
    hand: "LHH",
    birth: "Jul 31 1994",
  },
  {
    name: "Kim Min-seok",
    team: "kt",
    backNumber: "97",
    position: "C",
    hand: "RHH",
    birth: "Jul 22 2005",
  },
  {
    name: "Cheon Seong-ho",
    team: "kt",
    backNumber: "14",
    position: "LF",
    hand: "LHH",
    birth: "Oct 30 1997",
  },
  {
    name: "Heo Kyoung-min",
    team: "kt",
    backNumber: "13",
    position: "3B",
    hand: "RHH",
    birth: "Aug 26 1990",
  },
  {
    name: "Hwang Jae-gyun",
    team: "kt",
    backNumber: "10",
    position: "3B",
    hand: "RHH",
    birth: "Jul 28 1987",
  },
  {
    name: "Jang Jun-won",
    team: "kt",
    backNumber: "56",
    position: "SS",
    hand: "RHH",
    birth: "Nov 21 1995",
  },
  {
    name: "Kang Min-sung",
    team: "kt",
    backNumber: "5",
    position: "IF",
    hand: "RHH",
    birth: "Dec 8 1999",
  },
  {
    name: "Kim Sang-su",
    team: "kt",
    backNumber: "7",
    position: "2B",
    hand: "RHH",
    birth: "Mar 23 1990",
  },
  {
    name: "Kwon Dong-jin",
    team: "kt",
    backNumber: "52",
    position: "IF",
    hand: "LHH",
    birth: "Sep 12 1998",
  },
  {
    name: "Lee Ho-yeon",
    team: "kt",
    backNumber: "34",
    position: "2B",
    hand: "LHH",
    birth: "Jun 3 1995",
  },
  {
    name: "Moon Sang-chul",
    team: "kt",
    backNumber: "24",
    position: "1B",
    hand: "RHH",
    birth: "Apr 6 1991",
  },
  {
    name: "Oh Jae-il",
    team: "kt",
    backNumber: "36",
    position: "IF",
    hand: "LHH",
    birth: "Oct 29 1986",
  },
  {
    name: "Oh Seo-jin",
    team: "kt",
    backNumber: "25",
    position: "IF",
    hand: "RHH",
    birth: "Feb 22 2006",
  },
  {
    name: "Oh Yoon-suk",
    team: "kt",
    backNumber: "4",
    position: "2B",
    hand: "RHH",
    birth: "Feb 24 1992",
  },
  {
    name: "Park Min-seok",
    team: "kt",
    backNumber: "2",
    position: "IF",
    hand: "RHH",
    birth: "Apr 13 2000",
  },
  {
    name: "Yun Jun-hyeok",
    team: "kt",
    backNumber: "35",
    position: "3B",
    hand: "RHH",
    birth: "Jul 26 2001",
  },
  {
    name: "Ahn Hyun-min",
    team: "kt",
    backNumber: "23",
    position: "LF",
    hand: "RHH",
    birth: "Aug 22 2003",
  },
  {
    name: "An Chi-young",
    team: "kt",
    backNumber: "8",
    position: "OF",
    hand: "LHH",
    birth: "May 29 1998",
  },
  {
    name: "Bae Jeong-dae",
    team: "kt",
    backNumber: "27",
    position: "CF",
    hand: "RHH",
    birth: "Jun 12 1995",
  },
  {
    name: "Choi Seong-min",
    team: "kt",
    backNumber: "31",
    position: "OF",
    hand: "LHH",
    birth: "Jul 5 2002",
  },
  {
    name: "Jang Jin-hyuk",
    team: "kt",
    backNumber: "51",
    position: "CF",
    hand: "LHH",
    birth: "Sep 30 1993",
  },
  {
    name: "Mel Rojas Jr.",
    team: "kt",
    backNumber: "3",
    position: "RF",
    hand: "SHH",
    birth: "May 24 1990",
  },
  {
    name: "Kim Byeong-jun",
    team: "kt",
    backNumber: "57",
    position: "RF",
    hand: "LHH",
    birth: "Jul 3 2003",
  },
  {
    name: "Kim Geon-hyoung",
    team: "kt",
    backNumber: "0",
    position: "OF",
    hand: "LHH",
    birth: "Jul 12 1996",
  },
  {
    name: "Kim Min-hyuck",
    team: "kt",
    backNumber: "53",
    position: "LF",
    hand: "LHH",
    birth: "Nov 21 1995",
  },
  {
    name: "Lee Jeong-hun",
    team: "kt",
    backNumber: "33",
    position: "OF",
    hand: "LHH",
    birth: "Dec 7 1994",
  },
  {
    name: "Park Min-seok",
    team: "kt",
    backNumber: "104",
    position: "OF",
    hand: "RHH",
    birth: "Jul 27 2006",
  },
  {
    name: "Ryu Jun-kyu",
    team: "kt",
    backNumber: "67",
    position: "OF",
    hand: "LHH",
    birth: "Aug 16 2002",
  },
  {
    name: "Song Min-sub",
    team: "kt",
    backNumber: "28",
    position: "RF",
    hand: "RHH",
    birth: "Aug 2 1991",
  },
  {
    name: "Andrew Anderson",
    team: "ssg",
    backNumber: "33",
    position: "SP",
    hand: "RHP",
    birth: "Mar 22 1994",
  },
  {
    name: "Baek Seung-geon",
    team: "ssg",
    backNumber: "11",
    position: "RP",
    hand: "LHP",
    birth: "Oct 29 2000",
  },
  {
    name: "Choi Hyun-seok",
    team: "ssg",
    backNumber: "40",
    position: "RP",
    hand: "RHP",
    birth: "Oct 16 2003",
  },
  {
    name: "Choi Min-jun",
    team: "ssg",
    backNumber: "30",
    position: "RP",
    hand: "RHP",
    birth: "Jun 11 1999",
  },
  {
    name: "Chun Bum-suk",
    team: "ssg",
    backNumber: "90",
    position: "RP",
    hand: "RHP",
    birth: "Mar 6 2006",
  },
  {
    name: "Chung Dong-yoon",
    team: "ssg",
    backNumber: "51",
    position: "RP",
    hand: "RHP",
    birth: "Oct 22 1997",
  },
  {
    name: "Han Doo-sol",
    team: "ssg",
    backNumber: "34",
    position: "RP",
    hand: "LHP",
    birth: "Jan 15 1997",
  },
  {
    name: "Jang Ji-hun",
    team: "ssg",
    backNumber: "21",
    position: "RP",
    hand: "RHP",
    birth: "Dec 6 1998",
  },
  {
    name: "Jeon Young-jun",
    team: "ssg",
    backNumber: "65",
    position: "SP/RP",
    hand: "RHP",
    birth: "Apr 16 2002",
  },
  {
    name: "Jo Byeong-hyeon",
    team: "ssg",
    backNumber: "19",
    position: "CP",
    hand: "RHP",
    birth: "May 8 2002",
  },
  {
    name: "Kim Keon-woo",
    team: "ssg",
    backNumber: "39",
    position: "SP/RP",
    hand: "LHP",
    birth: "Jul 12 2002",
  },
  {
    name: "Kim Kwang-hyun",
    team: "ssg",
    backNumber: "29",
    position: "SP",
    hand: "LHP",
    birth: "Jul 22 1988",
  },
  {
    name: "Kim Min",
    team: "ssg",
    backNumber: "41",
    position: "RP",
    hand: "RHP",
    birth: "Apr 14 1999",
  },
  {
    name: "Kim Taek-hyeong",
    team: "ssg",
    backNumber: "43",
    position: "RP",
    hand: "LHP",
    birth: "Oct 10 1996",
  },
  {
    name: "Lee Geun-wook",
    team: "ssg",
    backNumber: "16",
    position: "RP",
    hand: "RHP",
    birth: "Feb 13 1995",
  },
  {
    name: "Lee Ro-un",
    team: "ssg",
    backNumber: "92",
    position: "RP",
    hand: "RHP",
    birth: "Sep 11 2004",
  },
  {
    name: "Moon Seung-won",
    team: "ssg",
    backNumber: "42",
    position: "SP",
    hand: "RHP",
    birth: "Nov 28 1989",
  },
  {
    name: "Noh Kyung-eun",
    team: "ssg",
    backNumber: "38",
    position: "RP",
    hand: "RHP",
    birth: "Mar 11 1984",
  },
  {
    name: "Park Jong-hun",
    team: "ssg",
    backNumber: "50",
    position: "SP/RP",
    hand: "RHP",
    birth: "Aug 13 1991",
  },
  {
    name: "Park Ki-ho",
    team: "ssg",
    backNumber: "66",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jul 26 2005",
  },
  {
    name: "Park Seong-bin",
    team: "ssg",
    backNumber: "00",
    position: "RP",
    hand: "RHP",
    birth: "Dec 29 2003",
  },
  {
    name: "Park Si-hoo",
    team: "ssg",
    backNumber: "57",
    position: "RP",
    hand: "LHP",
    birth: "May 10 2001",
  },
  {
    name: "Seo Jin-yong",
    team: "ssg",
    backNumber: "22",
    position: "RP",
    hand: "RHP",
    birth: "Oct 2 1992",
  },
  {
    name: "Shin Heon-min",
    team: "ssg",
    backNumber: "33",
    position: "RP",
    hand: "RHP",
    birth: "Jul 19 2002",
  },
  {
    name: "Shin Ji-hwan",
    team: "ssg",
    backNumber: "60",
    position: "RP",
    hand: "LHP",
    birth: "Apr 17 2006",
  },
  {
    name: "Song Young-jin",
    team: "ssg",
    backNumber: "28",
    position: "SP",
    hand: "RHP",
    birth: "May 28 2004",
  },
  {
    name: "Mitch White",
    team: "ssg",
    backNumber: "55",
    position: "SP",
    hand: "RHP",
    birth: "Dec 28 1994",
  },
  {
    name: "Cho Hyeong-woo",
    team: "ssg",
    backNumber: "20",
    position: "C",
    hand: "RHH",
    birth: "Apr 4 2002",
  },
  {
    name: "Kim Kyu-min",
    team: "ssg",
    backNumber: "61",
    position: "C",
    hand: "LHH",
    birth: "Aug 23 2002",
  },
  {
    name: "Kim Min-sik",
    team: "ssg",
    backNumber: "24",
    position: "C",
    hand: "LHH",
    birth: "Jun 28 1989",
  },
  {
    name: "Lee Ji-young",
    team: "ssg",
    backNumber: "59",
    position: "C",
    hand: "RHH",
    birth: "Feb 27 1986",
  },
  {
    name: "Lee Yul-ye",
    team: "ssg",
    backNumber: "32",
    position: "C",
    hand: "RHH",
    birth: "Nov 21 2006",
  },
  {
    name: "Shin Beom-soo",
    team: "ssg",
    backNumber: "25",
    position: "C",
    hand: "LHH",
    birth: "Jan 25 1998",
  },
  {
    name: "An Sang-hyun",
    team: "ssg",
    backNumber: "10",
    position: "SS",
    hand: "RHH",
    birth: "Jan 27 1997",
  },
  {
    name: "Choi Jeong",
    team: "ssg",
    backNumber: "14",
    position: "3B",
    hand: "RHH",
    birth: "Feb 28 1987",
  },
  {
    name: "Choi Jun-woo",
    team: "ssg",
    backNumber: "7",
    position: "IF",
    hand: "LHH",
    birth: "Mar 25 1999",
  },
  {
    name: "Choi Yun-seok",
    team: "ssg",
    backNumber: "94",
    position: "IF",
    hand: "RHH",
    birth: "Apr 25 2006",
  },
  {
    name: "Hong Dae-in",
    team: "ssg",
    backNumber: "97",
    position: "IF",
    hand: "LHH",
    birth: "Nov 23 2001",
  },
  {
    name: "Hyun Won-hoe",
    team: "ssg",
    backNumber: "8",
    position: "IF",
    hand: "RHH",
    birth: "Jul 8 2001",
  },
  {
    name: "Jeong Jun-jae",
    team: "ssg",
    backNumber: "3",
    position: "2B",
    hand: "LHH",
    birth: "Jan 3 2003",
  },
  {
    name: "Kim Chan-hyung",
    team: "ssg",
    backNumber: "5",
    position: "IF",
    hand: "RHH",
    birth: "Dec 29 1997",
  },
  {
    name: "Kim Seong-min",
    team: "ssg",
    backNumber: "56",
    position: "IF",
    hand: "RHH",
    birth: "Apr 30 2001",
  },
  {
    name: "Kim Su-yun",
    team: "ssg",
    backNumber: "4",
    position: "IF",
    hand: "RHH",
    birth: "Jul 16 1998",
  },
  {
    name: "Kim Sung-hyun",
    team: "ssg",
    backNumber: "6",
    position: "3B",
    hand: "RHH",
    birth: "Mar 9 1987",
  },
  {
    name: "Kim Tae-yun",
    team: "ssg",
    backNumber: "36",
    position: "IF",
    hand: "LHH",
    birth: "Feb 28 2003",
  },
  {
    name: "Ko Myeong-jun",
    team: "ssg",
    backNumber: "18",
    position: "1B",
    hand: "RHH",
    birth: "Jul 8 2002",
  },
  {
    name: "Park Ji-hwan",
    team: "ssg",
    backNumber: "1",
    position: "3B",
    hand: "RHH",
    birth: "Jul 12 2005",
  },
  {
    name: "Park Seong-han",
    team: "ssg",
    backNumber: "2",
    position: "SS",
    hand: "LHH",
    birth: "Mar 30 1998",
  },
  {
    name: "Seok Jeung-woo",
    team: "ssg",
    backNumber: "52",
    position: "IF",
    hand: "RHH",
    birth: "Jan 20 1999",
  },
  {
    name: "Chae Hyun-woo",
    team: "ssg",
    backNumber: "15",
    position: "OF",
    hand: "RHH",
    birth: "Nov 21 1995",
  },
  {
    name: "Choi Ji-hoon",
    team: "ssg",
    backNumber: "54",
    position: "CF",
    hand: "LHH",
    birth: "Jul 23 1997",
  },
  {
    name: "Choi Min-chang",
    team: "ssg",
    backNumber: "53",
    position: "OF",
    hand: "LHH",
    birth: "Apr 16 1996",
  },
  {
    name: "Choi Sang-min",
    team: "ssg",
    backNumber: "23",
    position: "RF",
    hand: "LHH",
    birth: "Aug 20 1999",
  },
  {
    name: "Ha Jae-hoon",
    team: "ssg",
    backNumber: "13",
    position: "CF",
    hand: "RHH",
    birth: "Oct 29 1990",
  },
  {
    name: "Han Yoo-seom",
    team: "ssg",
    backNumber: "35",
    position: "RF",
    hand: "LHH",
    birth: "Aug 9 1989",
  },
  {
    name: "Guillermo Heredia",
    team: "ssg",
    backNumber: "27",
    position: "LF",
    hand: "RHH",
    birth: "Jan 31 1991",
  },
  {
    name: "Jung Hyeon-seung",
    team: "ssg",
    backNumber: "17",
    position: "RF",
    hand: "LHH",
    birth: "Oct 24 2001",
  },
  {
    name: "Kim Chang-pyeong",
    team: "ssg",
    backNumber: "64",
    position: "OF",
    hand: "LHH",
    birth: "Jun 14 2000",
  },
  {
    name: "Kim Seong-uk",
    team: "ssg",
    backNumber: "47",
    position: "CF",
    hand: "RHH",
    birth: "May 1 1993",
  },
  {
    name: "Lee Jeong-beom",
    team: "ssg",
    backNumber: "31",
    position: "OF",
    hand: "LHH",
    birth: "Apr 10 1998",
  },
  {
    name: "Lee Seung-min",
    team: "ssg",
    backNumber: "9",
    position: "OF",
    hand: "LHH",
    birth: "Jan 6 2005",
  },
  {
    name: "Ryan McBroom",
    team: "ssg",
    backNumber: "44",
    position: "OF",
    hand: "RHH",
    birth: "Apr 9 1992",
  },
  {
    name: "Oh Tae-gon",
    team: "ssg",
    backNumber: "37",
    position: "LF",
    hand: "RHH",
    birth: "Nov 18 1991",
  },
  {
    name: "Park Jung-bin",
    team: "ssg",
    backNumber: "58",
    position: "OF",
    hand: "RHH",
    birth: "Jun 14 2002",
  },
  {
    name: "Ryu Hyo-seung",
    team: "ssg",
    backNumber: "45",
    position: "OF",
    hand: "RHH",
    birth: "Jul 16 1996",
  },
  {
    name: "Bae Chan-seung",
    team: "samsung",
    backNumber: "55",
    position: "RP",
    hand: "LHP",
    birth: "Jan 1 2006",
  },
  {
    name: "Baek Jung-hyun",
    team: "samsung",
    backNumber: "29",
    position: "SP/RP",
    hand: "LHP",
    birth: "Jul 13 1987",
  },
  {
    name: "Choi Chung-yeon",
    team: "samsung",
    backNumber: "51",
    position: "RP",
    hand: "RHP",
    birth: "Mar 5 1997",
  },
  {
    name: "Choi Ha-neul",
    team: "samsung",
    backNumber: "37",
    position: "RP",
    hand: "RHP",
    birth: "Mar 26 1999",
  },
  {
    name: "Choi Ji-gwang",
    team: "samsung",
    backNumber: "11",
    position: "RP",
    hand: "RHP",
    birth: "Mar 13 1998",
  },
  {
    name: "Choi Sung-hoon",
    team: "samsung",
    backNumber: "54",
    position: "RP",
    hand: "LHP",
    birth: "Oct 11 1989",
  },
  {
    name: "Choi Won-tae",
    team: "samsung",
    backNumber: "3",
    position: "SP",
    hand: "RHP",
    birth: "Jan 7 1997",
  },
  {
    name: "Garabito Gerson",
    team: "samsung",
    backNumber: "60",
    position: "RP",
    hand: "RHP",
    birth: "Aug 19 1995",
  },
  {
    name: "Gwon Hyun-woo",
    team: "samsung",
    backNumber: "41",
    position: "RP",
    hand: "RHP",
    birth: "Mar 28 2006",
  },
  {
    name: "Hong Won-pyo",
    team: "samsung",
    backNumber: "65",
    position: "RP",
    hand: "RHP",
    birth: "Mar 27 2001",
  },
  {
    name: "Hwang Dong-jae",
    team: "samsung",
    backNumber: "61",
    position: "SP/RP",
    hand: "RHP",
    birth: "Nov 3 2001",
  },
  {
    name: "Jeong Min-seong",
    team: "samsung",
    backNumber: "49",
    position: "SP/RP",
    hand: "RHP",
    birth: "May 9 2005",
  },
  {
    name: "Ariel Jurado",
    team: "samsung",
    backNumber: "75",
    position: "SP",
    hand: "RHP",
    birth: "Jan 30 1996",
  },
  {
    name: "Kim Dae-ho",
    team: "samsung",
    backNumber: "44",
    position: "SP/RP",
    hand: "RHP",
    birth: "Oct 15 2001",
  },
  {
    name: "Kim Dae-woo",
    team: "samsung",
    backNumber: "17",
    position: "RP",
    hand: "RHP",
    birth: "Nov 21 1988",
  },
  {
    name: "Kim Jae-yoon",
    team: "samsung",
    backNumber: "62",
    position: "CP",
    hand: "RHP",
    birth: "Sep 16 1990",
  },
  {
    name: "Kim Mu-sin",
    team: "samsung",
    backNumber: "48",
    position: "RP",
    hand: "RHP",
    birth: "Dec 8 1999",
  },
  {
    name: "Kim Tae-hoon",
    team: "samsung",
    backNumber: "27",
    position: "RP",
    hand: "RHP",
    birth: "Mar 2 1992",
  },
  {
    name: "Lee Ho-sung",
    team: "samsung",
    backNumber: "1",
    position: "RP",
    hand: "RHP",
    birth: "Aug 14 2004",
  },
  {
    name: "Lee Jae-hee",
    team: "samsung",
    backNumber: "59",
    position: "RP",
    hand: "RHP",
    birth: "Oct 11 2001",
  },
  {
    name: "Lee Jae-ik",
    team: "samsung",
    backNumber: "26",
    position: "RP",
    hand: "LHP",
    birth: "Mar 18 1994",
  },
  {
    name: "Lee Sang-min",
    team: "samsung",
    backNumber: "15",
    position: "RP",
    hand: "LHP",
    birth: "Nov 4 1990",
  },
  {
    name: "Lee Seung-hyun",
    team: "samsung",
    backNumber: "20",
    position: "RP",
    hand: "RHP",
    birth: "Nov 20 1991",
  },
  {
    name: "Lee Seung-hyun",
    team: "samsung",
    backNumber: "57",
    position: "SP",
    hand: "LHP",
    birth: "May 19 2002",
  },
  {
    name: "Lee Seung-min",
    team: "samsung",
    backNumber: "28",
    position: "RP",
    hand: "LHP",
    birth: "Aug 26 2000",
  },
  {
    name: "Lim Chang-min",
    team: "samsung",
    backNumber: "45",
    position: "RP",
    hand: "RHP",
    birth: "Aug 25 1985",
  },
  {
    name: "Oh Seung-hwan",
    team: "samsung",
    backNumber: "21",
    position: "RP",
    hand: "RHP",
    birth: "Jul 15 1982",
  },
  {
    name: "Denyi Reyes",
    team: "samsung",
    backNumber: "43",
    position: "SP",
    hand: "RHP",
    birth: "Nov 2 1996",
  },
  {
    name: "Song Eun-beom",
    team: "samsung",
    backNumber: "46",
    position: "RP",
    hand: "RHP",
    birth: "Mar 17 1984",
  },
  {
    name: "Won Tae-in",
    team: "samsung",
    backNumber: "18",
    position: "SP",
    hand: "RHP",
    birth: "Apr 6 2000",
  },
  {
    name: "Yang Chang-seop",
    team: "samsung",
    backNumber: "42",
    position: "SP/RP",
    hand: "RHP",
    birth: "Sep 22 1999",
  },
  {
    name: "Yang Hyun",
    team: "samsung",
    backNumber: "19",
    position: "RP",
    hand: "RHP",
    birth: "Aug 23 1992",
  },
  {
    name: "Yook Sun-yeop",
    team: "samsung",
    backNumber: "4",
    position: "RP",
    hand: "RHP",
    birth: "Jul 13 2005",
  },
  {
    name: "Kang Min-ho",
    team: "samsung",
    backNumber: "47",
    position: "C",
    hand: "RHH",
    birth: "Aug 18 1985",
  },
  {
    name: "Kim Do-hwan",
    team: "samsung",
    backNumber: "24",
    position: "C",
    hand: "RHH",
    birth: "Apr 14 2000",
  },
  {
    name: "Kim Jae-seong",
    team: "samsung",
    backNumber: "2",
    position: "C",
    hand: "LHH",
    birth: "Oct 30 1996",
  },
  {
    name: "Kim Min-su",
    team: "samsung",
    backNumber: "12",
    position: "C",
    hand: "RHH",
    birth: "Mar 2 1991",
  },
  {
    name: "Lee Byung-heon",
    team: "samsung",
    backNumber: "23",
    position: "C",
    hand: "RHH",
    birth: "Oct 26 1999",
  },
  {
    name: "An Ju-hyeong",
    team: "samsung",
    backNumber: "14",
    position: "2B",
    hand: "LHH",
    birth: "Aug 14 1993",
  },
  {
    name: "Cha Seung-jun",
    team: "samsung",
    backNumber: "35",
    position: "IF",
    hand: "LHH",
    birth: "Nov 20 2006",
  },
  {
    name: "Lewin Díaz",
    team: "samsung",
    backNumber: "0",
    position: "1B",
    hand: "LHH",
    birth: "Nov 19 1996",
  },
  {
    name: "Jeon Byeong-woo",
    team: "samsung",
    backNumber: "34",
    position: "3B",
    hand: "RHH",
    birth: "Oct 24 1992",
  },
  {
    name: "Kang Han-wool",
    team: "samsung",
    backNumber: "6",
    position: "IF",
    hand: "LHH",
    birth: "Sep 12 1991",
  },
  {
    name: "Kim Ho-jin",
    team: "samsung",
    backNumber: "16",
    position: "IF",
    hand: "RHH",
    birth: "Jul 16 2005",
  },
  {
    name: "Kim Young-woong",
    team: "samsung",
    backNumber: "30",
    position: "3B",
    hand: "LHH",
    birth: "Aug 24 2003",
  },
  {
    name: "Kong Min-gyu",
    team: "samsung",
    backNumber: "9",
    position: "IF",
    hand: "LHH",
    birth: "Sep 27 1999",
  },
  {
    name: "Lee Chang-yong",
    team: "samsung",
    backNumber: "50",
    position: "IF",
    hand: "RHH",
    birth: "Jun 3 1999",
  },
  {
    name: "Lee Hae-seung",
    team: "samsung",
    backNumber: "56",
    position: "IF",
    hand: "RHH",
    birth: "Aug 1 2000",
  },
  {
    name: "Lee Jae-hyeon",
    team: "samsung",
    backNumber: "7",
    position: "SS",
    hand: "RHH",
    birth: "Feb 4 2003",
  },
  {
    name: "Park Byung-ho",
    team: "samsung",
    backNumber: "52",
    position: "1B",
    hand: "RHH",
    birth: "Jul 10 1986",
  },
  {
    name: "Ryu Ji-hyuk",
    team: "samsung",
    backNumber: "16",
    position: "2B",
    hand: "LHH",
    birth: "Jan 13 1994",
  },
  {
    name: "Sim Jae-hoon",
    team: "samsung",
    backNumber: "38",
    position: "IF",
    hand: "RHH",
    birth: "Mar 3 2006",
  },
  {
    name: "Yang Do-geun",
    team: "samsung",
    backNumber: "68",
    position: "SS",
    hand: "RHH",
    birth: "Feb 6 2003",
  },
  {
    name: "Yang Woo-hyun",
    team: "samsung",
    backNumber: "53",
    position: "IF",
    hand: "LHH",
    birth: "Apr 13 2000",
  },
  {
    name: "Ham Soo-ho",
    team: "samsung",
    backNumber: "40",
    position: "OF",
    hand: "LHH",
    birth: "Mar 10 2006",
  },
  {
    name: "Hong Hyun-bin",
    team: "samsung",
    backNumber: "63",
    position: "OF",
    hand: "LHH",
    birth: "Aug 29 1997",
  },
  {
    name: "Kim Hun-gon",
    team: "samsung",
    backNumber: "32",
    position: "LF",
    hand: "RHH",
    birth: "Nov 9 1988",
  },
  {
    name: "Kim Jae-hyuk",
    team: "samsung",
    backNumber: "8",
    position: "CF",
    hand: "RHH",
    birth: "Dec 26 1999",
  },
  {
    name: "Kim Ji-chan",
    team: "samsung",
    backNumber: "58",
    position: "CF",
    hand: "LHH",
    birth: "Mar 8 2001",
  },
  {
    name: "Kim Seong-yoon",
    team: "samsung",
    backNumber: "39",
    position: "CF",
    hand: "LHH",
    birth: "Feb 2 1999",
  },
  {
    name: "Kim Tae-hoon",
    team: "samsung",
    backNumber: "25",
    position: "OF",
    hand: "LHH",
    birth: "Mar 31 1996",
  },
  {
    name: "Kim Tae-keun",
    team: "samsung",
    backNumber: "64",
    position: "LF",
    hand: "RHH",
    birth: "Aug 10 1996",
  },
  {
    name: "Koo Ja-wook",
    team: "samsung",
    backNumber: "5",
    position: "LF",
    hand: "LHH",
    birth: "Feb 12 1993",
  },
  {
    name: "Lee Sung-gyu",
    team: "samsung",
    backNumber: "13",
    position: "1B",
    hand: "RHH",
    birth: "Aug 3 1993",
  },
  {
    name: "Park Seung-kyu",
    team: "samsung",
    backNumber: "66",
    position: "CF",
    hand: "RHH",
    birth: "Sep 2 2000",
  },
  {
    name: "Yoon Jeong-bin",
    team: "samsung",
    backNumber: "31",
    position: "RF",
    hand: "LHH",
    birth: "Jun 24 1999",
  },
  {
    name: "Charlie Barnes",
    team: "lotte",
    backNumber: "28",
    position: "SP",
    hand: "LHP",
    birth: "Oct 1 1995",
  },
  {
    name: "Choi Jun-yong",
    team: "lotte",
    backNumber: "56",
    position: "RP",
    hand: "RHP",
    birth: "Oct 10 2001",
  },
  {
    name: "Tucker Davidson",
    team: "lotte",
    backNumber: "36",
    position: "SP",
    hand: "LHP",
    birth: "Mar 25 1996",
  },
  {
    name: "Alec Gamboa",
    team: "lotte",
    backNumber: "32",
    position: "SP/RP",
    hand: "LHP",
    birth: "Jan 17 1997",
  },
  {
    name: "Han Hyun-hee",
    team: "lotte",
    backNumber: "1",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jun 25 1993",
  },
  {
    name: "Hong Min-ki",
    team: "lotte",
    backNumber: "38",
    position: "RP",
    hand: "LHP",
    birth: "Jul 20 2001",
  },
  {
    name: "Hyeon Do-hoon",
    team: "lotte",
    backNumber: "17",
    position: "RP",
    hand: "RHP",
    birth: "Jan 13 1993",
  },
  {
    name: "Jeong Cheol-won",
    team: "lotte",
    backNumber: "65",
    position: "RP",
    hand: "RHP",
    birth: "Mar 27 1999",
  },
  {
    name: "Jeong Hyeon-su",
    team: "lotte",
    backNumber: "57",
    position: "RP",
    hand: "LHP",
    birth: "May 10 2001",
  },
  {
    name: "Jeong Woo-jun",
    team: "lotte",
    backNumber: "46",
    position: "RP",
    hand: "RHP",
    birth: "Mar 17 2000",
  },
  {
    name: "Jin Hae-soo",
    team: "lotte",
    backNumber: "31",
    position: "RP",
    hand: "LHP",
    birth: "Jun 26 1986",
  },
  {
    name: "Jin Seung-hyun",
    team: "lotte",
    backNumber: "24",
    position: "RP",
    hand: "RHP",
    birth: "Sep 5 2003",
  },
  {
    name: "Kim Do-gyu",
    team: "lotte",
    backNumber: "124",
    position: "RP",
    hand: "RHP",
    birth: "Jul 11 1998",
  },
  {
    name: "Kim Gang-hyun",
    team: "lotte",
    backNumber: "19",
    position: "RP",
    hand: "RHP",
    birth: "Feb 27 1995",
  },
  {
    name: "Kim Jin-uk",
    team: "lotte",
    backNumber: "15",
    position: "SP/RP",
    hand: "LHP",
    birth: "Jul 5 2002",
  },
  {
    name: "Kim Sang-su",
    team: "lotte",
    backNumber: "24",
    position: "RP",
    hand: "RHP",
    birth: "Jan 2 1988",
  },
  {
    name: "Kim Tae-hyun",
    team: "lotte",
    backNumber: "66",
    position: "RP",
    hand: "LHP",
    birth: "Nov 16 2005",
  },
  {
    name: "Kim Won-jung",
    team: "lotte",
    backNumber: "34",
    position: "CP",
    hand: "RHP",
    birth: "Jun 14 1993",
  },
  {
    name: "Koo Seung-min",
    team: "lotte",
    backNumber: "22",
    position: "RP",
    hand: "RHP",
    birth: "Jun 12 1990",
  },
  {
    name: "Lee Byung-jun",
    team: "lotte",
    backNumber: "45",
    position: "RP",
    hand: "RHP",
    birth: "May 28 2002",
  },
  {
    name: "Lee Min-seok",
    team: "lotte",
    backNumber: "37",
    position: "SP",
    hand: "RHP",
    birth: "Dec 10 2003",
  },
  {
    name: "Na Gyun-an",
    team: "lotte",
    backNumber: "43",
    position: "SP",
    hand: "RHP",
    birth: "Mar 16 1998",
  },
  {
    name: "Park Jin",
    team: "lotte",
    backNumber: "44",
    position: "SP/RP",
    hand: "RHP",
    birth: "Apr 2 1999",
  },
  {
    name: "Park Jin-hyung",
    team: "lotte",
    backNumber: "40",
    position: "RP",
    hand: "RHP",
    birth: "Jun 10 1994",
  },
  {
    name: "Park Joon-woo",
    team: "lotte",
    backNumber: "58",
    position: "RP",
    hand: "RHP",
    birth: "May 27 2005",
  },
  {
    name: "Park Se-hyun",
    team: "lotte",
    backNumber: "68",
    position: "RP",
    hand: "RHP",
    birth: "Jan 21 2006",
  },
  {
    name: "Park Se-jin",
    team: "lotte",
    backNumber: "41",
    position: "RP",
    hand: "LHP",
    birth: "Jun 27 1997",
  },
  {
    name: "Park Se-woong",
    team: "lotte",
    backNumber: "21",
    position: "SP",
    hand: "RHP",
    birth: "Nov 30 1995",
  },
  {
    name: "Park Si-young",
    team: "lotte",
    backNumber: "25",
    position: "RP",
    hand: "RHP",
    birth: "Mar 10 1989",
  },
  {
    name: "Shim Jae-min",
    team: "lotte",
    backNumber: "23",
    position: "RP",
    hand: "LHP",
    birth: "Feb 18 1994",
  },
  {
    name: "Shin Byung-ryul",
    team: "lotte",
    backNumber: "12",
    position: "RP",
    hand: "RHP",
    birth: "Jan 30 1996",
  },
  {
    name: "Song Jae-young",
    team: "lotte",
    backNumber: "59",
    position: "RP",
    hand: "LHP",
    birth: "Jun 20 2002",
  },
  {
    name: "Yoon Seong-pin",
    team: "lotte",
    backNumber: "55",
    position: "SP/RP",
    hand: "RHP",
    birth: "Feb 26 1999",
  },
  {
    name: "Baek Du-san",
    team: "lotte",
    backNumber: "62",
    position: "C",
    hand: "RHH",
    birth: "May 20 2001",
  },
  {
    name: "Jeong Bo-keun",
    team: "lotte",
    backNumber: "42",
    position: "C",
    hand: "RHH",
    birth: "Aug 31 1999",
  },
  {
    name: "Kang Seung-gu",
    team: "lotte",
    backNumber: "39",
    position: "C",
    hand: "RHH",
    birth: "Oct 19 2003",
  },
  {
    name: "Park Jae-yeop",
    team: "lotte",
    backNumber: "63",
    position: "C",
    hand: "RHH",
    birth: "Jan 23 2006",
  },
  {
    name: "Seo Dong-uk",
    team: "lotte",
    backNumber: "106",
    position: "C",
    hand: "RHH",
    birth: "Mar 24 2000",
  },
  {
    name: "Son Seong-bin",
    team: "lotte",
    backNumber: "28",
    position: "C",
    hand: "RHH",
    birth: "Jan 14 2002",
  },
  {
    name: "Yoo Kang-nam",
    team: "lotte",
    backNumber: "27",
    position: "C",
    hand: "RHH",
    birth: "Jul 15 1992",
  },
  {
    name: "Choi Hang",
    team: "lotte",
    backNumber: "14",
    position: "IF",
    hand: "LHH",
    birth: "Jan 3 1994",
  },
  {
    name: "Go Seung-min",
    team: "lotte",
    backNumber: "2",
    position: "2B",
    hand: "LHH",
    birth: "Aug 11 2000",
  },
  {
    name: "Han Tae-yang",
    team: "lotte",
    backNumber: "6",
    position: "IF",
    hand: "RHH",
    birth: "Sep 15 2003",
  },
  {
    name: "Jeon Min-jae",
    team: "lotte",
    backNumber: "13",
    position: "SS",
    hand: "RHH",
    birth: "Jun 30 1999",
  },
  {
    name: "Jung Hoon",
    team: "lotte",
    backNumber: "9",
    position: "1B",
    hand: "RHH",
    birth: "Jul 18 1987",
  },
  {
    name: "Kang Seong-woo",
    team: "lotte",
    backNumber: "9",
    position: "IF",
    hand: "RHH",
    birth: "Apr 12 2005",
  },
  {
    name: "Kim Min-sung",
    team: "lotte",
    backNumber: "16",
    position: "3B",
    hand: "RHH",
    birth: "Dec 17 1988",
  },
  {
    name: "Lee Ho-jun",
    team: "lotte",
    backNumber: "30",
    position: "SS",
    hand: "LHH",
    birth: "Mar 20 2004",
  },
  {
    name: "Lee Tae-kyeong",
    team: "lotte",
    backNumber: "69",
    position: "IF",
    hand: "RHH",
    birth: "Nov 24 2002",
  },
  {
    name: "Na Seung-yeup",
    team: "lotte",
    backNumber: "51",
    position: "1B",
    hand: "LHH",
    birth: "Feb 15 2002",
  },
  {
    name: "No Jin-hyuk",
    team: "lotte",
    backNumber: "52",
    position: "IF",
    hand: "LHH",
    birth: "Jul 15 1989",
  },
  {
    name: "Park Chan-hyung",
    team: "lotte",
    backNumber: "60",
    position: "IF",
    hand: "LHH",
    birth: "Oct 17 2002",
  },
  {
    name: "Park Seung-wook",
    team: "lotte",
    backNumber: "53",
    position: "2B",
    hand: "LHH",
    birth: "Dec 4 1992",
  },
  {
    name: "Shin Yoon-hoo",
    team: "lotte",
    backNumber: "3",
    position: "RF",
    hand: "RHH",
    birth: "Jan 5 1996",
  },
  {
    name: "Son Ho-young",
    team: "lotte",
    backNumber: "33",
    position: "3B",
    hand: "RHH",
    birth: "Aug 23 1994",
  },
  {
    name: "Cho Se-jin",
    team: "lotte",
    backNumber: "5",
    position: "OF",
    hand: "RHH",
    birth: "Nov 21 2003",
  },
  {
    name: "Han Seung-hyun",
    team: "lotte",
    backNumber: "35",
    position: "OF",
    hand: "RHH",
    birth: "Oct 29 2006",
  },
  {
    name: "Hwang Seong-bin",
    team: "lotte",
    backNumber: "0",
    position: "LF",
    hand: "LHH",
    birth: "Dec 19 1997",
  },
  {
    name: "Jang Du-seong",
    team: "lotte",
    backNumber: "7",
    position: "CF",
    hand: "LHH",
    birth: "Sep 16 1999",
  },
  {
    name: "Jeon Jun-woo",
    team: "lotte",
    backNumber: "8",
    position: "LF",
    hand: "RHH",
    birth: "Feb 25 1986",
  },
  {
    name: "Kim Dong-hyeok",
    team: "lotte",
    backNumber: "50",
    position: "OF",
    hand: "LHH",
    birth: "Sep 15 2000",
  },
  {
    name: "Kim Dong-hyun",
    team: "lotte",
    backNumber: "64",
    position: "OF",
    hand: "LHH",
    birth: "Dec 30 2004",
  },
  {
    name: "Lee In-han",
    team: "lotte",
    backNumber: "54",
    position: "OF",
    hand: "RHH",
    birth: "Dec 24 1998",
  },
  {
    name: "Víctor Reyes",
    team: "lotte",
    backNumber: "29",
    position: "RF",
    hand: "SHH",
    birth: "Oct 5 1994",
  },
  {
    name: "Yoon Dong-hee",
    team: "lotte",
    backNumber: "91",
    position: "CF",
    hand: "RHH",
    birth: "Sep 18 2003",
  },
  {
    name: "Logan Allen",
    team: "nc",
    backNumber: "12",
    position: "SP",
    hand: "LHP",
    birth: "May 23 1997",
  },
  {
    name: "Bae Jae-whan",
    team: "nc",
    backNumber: "61",
    position: "RP",
    hand: "RHP",
    birth: "Feb 24 1995",
  },
  {
    name: "Cho Min-suk",
    team: "nc",
    backNumber: "64",
    position: "RP",
    hand: "RHP",
    birth: "Dec 21 1998",
  },
  {
    name: "Choi Sung-young",
    team: "nc",
    backNumber: "26",
    position: "SP",
    hand: "LHP",
    birth: "Apr 28 1997",
  },
  {
    name: "Choi Woo-seok",
    team: "nc",
    backNumber: "48",
    position: "RP",
    hand: "RHP",
    birth: "Mar 31 2005",
  },
  {
    name: "Chun Sa-min",
    team: "nc",
    backNumber: "57",
    position: "RP",
    hand: "RHP",
    birth: "Jul 6 1999",
  },
  {
    name: "Han Jae-seung",
    team: "nc",
    backNumber: "55",
    position: "RP",
    hand: "RHP",
    birth: "Nov 21 2001",
  },
  {
    name: "Hong Jae-moon",
    team: "nc",
    backNumber: "96",
    position: "RP",
    hand: "RHP",
    birth: "Jul 9 2004",
  },
  {
    name: "Jun Ru-geon",
    team: "nc",
    backNumber: "47",
    position: "RP",
    hand: "RHP",
    birth: "Jun 9 2000",
  },
  {
    name: "Kim Hwi-geon",
    team: "nc",
    backNumber: "19",
    position: "RP",
    hand: "RHP",
    birth: "Aug 27 2005",
  },
  {
    name: "Kim Jae-yeol",
    team: "nc",
    backNumber: "32",
    position: "RP",
    hand: "RHP",
    birth: "Jan 2 1996",
  },
  {
    name: "Kim Jin-ho",
    team: "nc",
    backNumber: "54",
    position: "RP",
    hand: "RHP",
    birth: "Jun 7 1998",
  },
  {
    name: "Kim Min-gyu",
    team: "nc",
    backNumber: "63",
    position: "RP",
    hand: "RHP",
    birth: "Sep 7 2001",
  },
  {
    name: "Kim Nok-won",
    team: "nc",
    backNumber: "22",
    position: "SP/RP",
    hand: "RHP",
    birth: "May 17 2003",
  },
  {
    name: "Kim Si-hoon",
    team: "nc",
    backNumber: "21",
    position: "RP",
    hand: "RHP",
    birth: "Feb 24 1999",
  },
  {
    name: "Kim Tae-gyeong",
    team: "nc",
    backNumber: "11",
    position: "SP/RP",
    hand: "RHP",
    birth: "Apr 7 2001",
  },
  {
    name: "Kim Tae-hoon",
    team: "nc",
    backNumber: "95",
    position: "RP",
    hand: "RHP",
    birth: "Oct 26 2006",
  },
  {
    name: "Kim Tae-hyun",
    team: "nc",
    backNumber: "15",
    position: "RP",
    hand: "LHP",
    birth: "Mar 21 1998",
  },
  {
    name: "Kim Young-kyu",
    team: "nc",
    backNumber: "17",
    position: "RP",
    hand: "LHP",
    birth: "Feb 10 2000",
  },
  {
    name: "Koo Chang-mo",
    team: "nc",
    backNumber: "59",
    position: "RP",
    hand: "LHP",
    birth: "Feb 17 1997",
  },
  {
    name: "Lee Jae-hak",
    team: "nc",
    backNumber: "51",
    position: "RP",
    hand: "RHP",
    birth: "Oct 4 1990",
  },
  {
    name: "Lee Jun-hyeok",
    team: "nc",
    backNumber: "40",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jun 30 2003",
  },
  {
    name: "Lee Se-min",
    team: "nc",
    backNumber: "97",
    position: "RP",
    hand: "RHP",
    birth: "Aug 8 2005",
  },
  {
    name: "Lee Yong-chan",
    team: "nc",
    backNumber: "45",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jan 2 1989",
  },
  {
    name: "Lim Jung-ho",
    team: "nc",
    backNumber: "13",
    position: "RP",
    hand: "LHP",
    birth: "Apr 16 1990",
  },
  {
    name: "Lim Sang-hyeon",
    team: "nc",
    backNumber: "28",
    position: "RP",
    hand: "RHP",
    birth: "Jul 16 2005",
  },
  {
    name: "Mok Ji-hoon",
    team: "nc",
    backNumber: "20",
    position: "SP",
    hand: "RHP",
    birth: "May 11 2004",
  },
  {
    name: "Park Ju-hyeon",
    team: "nc",
    backNumber: "67",
    position: "RP",
    hand: "LHP",
    birth: "Aug 3 1999",
  },
  {
    name: "Ryu Jin-wook",
    team: "nc",
    backNumber: "41",
    position: "CP",
    hand: "RHP",
    birth: "Oct 10 1996",
  },
  {
    name: "Seo Eui-tae",
    team: "nc",
    backNumber: "58",
    position: "RP",
    hand: "LHP",
    birth: "Sep 5 1997",
  },
  {
    name: "Shin Min-hyeok",
    team: "nc",
    backNumber: "18",
    position: "SP",
    hand: "RHP",
    birth: "Feb 4 1999",
  },
  {
    name: "Shin Yeong-woo",
    team: "nc",
    backNumber: "43",
    position: "SP/RP",
    hand: "RHP",
    birth: "Apr 21 2004",
  },
  {
    name: "So Rhee-hyun",
    team: "nc",
    backNumber: "50",
    position: "RP",
    hand: "RHP",
    birth: "Feb 9 1999",
  },
  {
    name: "Son Ju-hwan",
    team: "nc",
    backNumber: "46",
    position: "RP",
    hand: "RHP",
    birth: "Jan 5 2002",
  },
  {
    name: "Riley Thompson",
    team: "nc",
    backNumber: "3",
    position: "SP",
    hand: "RHP",
    birth: "Jul 9 1996",
  },
  {
    name: "Won Jong-hae",
    team: "nc",
    backNumber: "56",
    position: "RP",
    hand: "RHP",
    birth: "Apr 9 2005",
  },
  {
    name: "An Joong-yeol",
    team: "nc",
    backNumber: "1",
    position: "C",
    hand: "RHH",
    birth: "Sep 1 1995",
  },
  {
    name: "Kim Hyung-jun",
    team: "nc",
    backNumber: "25",
    position: "C",
    hand: "RHH",
    birth: "Nov 2 1999",
  },
  {
    name: "Kim Jeong-ho",
    team: "nc",
    backNumber: "42",
    position: "C",
    hand: "RHH",
    birth: "Jul 13 1998",
  },
  {
    name: "Park Sei-hyok",
    team: "nc",
    backNumber: "10",
    position: "C",
    hand: "LHH",
    birth: "Jan 9 1990",
  },
  {
    name: "Shin Yong-seok",
    team: "nc",
    backNumber: "1",
    position: "C",
    hand: "RHH",
    birth: "Oct 11 2003",
  },
  {
    name: "Choi Jeong-won",
    team: "nc",
    backNumber: "14",
    position: "CF",
    hand: "LHH",
    birth: "Jun 24 2000",
  },
  {
    name: "Matthew Davidson",
    team: "nc",
    backNumber: "24",
    position: "1B",
    hand: "RHH",
    birth: "Mar 26 1991",
  },
  {
    name: "Do Tae-hun",
    team: "nc",
    backNumber: "16",
    position: "1B",
    hand: "LHH",
    birth: "Mar 18 1993",
  },
  {
    name: "Han Jae-hwan",
    team: "nc",
    backNumber: "35",
    position: "1B",
    hand: "RHH",
    birth: "Oct 19 2001",
  },
  {
    name: "Jang Chang-hoon",
    team: "nc",
    backNumber: "93",
    position: "IF",
    hand: "LHH",
    birth: "May 22 2000",
  },
  {
    name: "Jeong Hyun-chang",
    team: "nc",
    backNumber: "52",
    position: "IF",
    hand: "LHH",
    birth: "Jul 14 2006",
  },
  {
    name: "Kim Han-byul",
    team: "nc",
    backNumber: "68",
    position: "SS",
    hand: "RHH",
    birth: "Jan 18 2001",
  },
  {
    name: "Kim Ju-won",
    team: "nc",
    backNumber: "7",
    position: "SS",
    hand: "SHH",
    birth: "Jul 30 2002",
  },
  {
    name: "Kim Se-hun",
    team: "nc",
    backNumber: "9",
    position: "IF",
    hand: "RHH",
    birth: "Apr 4 2005",
  },
  {
    name: "Kim Whee-jip",
    team: "nc",
    backNumber: "44",
    position: "3B",
    hand: "RHH",
    birth: "Jan 1 2002",
  },
  {
    name: "Oh Tae-yang",
    team: "nc",
    backNumber: "6",
    position: "IF",
    hand: "RHH",
    birth: "Apr 25 2002",
  },
  {
    name: "Oh Young-soo",
    team: "nc",
    backNumber: "34",
    position: "IF",
    hand: "LHH",
    birth: "Jan 30 2000",
  },
  {
    name: "Park Min-woo",
    team: "nc",
    backNumber: "2",
    position: "2B",
    hand: "LHH",
    birth: "Feb 6 1993",
  },
  {
    name: "Seo Ho-cheol",
    team: "nc",
    backNumber: "5",
    position: "3B",
    hand: "RHH",
    birth: "Oct 16 1996",
  },
  {
    name: "Cheon Jae-hwan",
    team: "nc",
    backNumber: "23",
    position: "RF",
    hand: "RHH",
    birth: "Apr 1 1994",
  },
  {
    name: "Han Suk-hyun",
    team: "nc",
    backNumber: "33",
    position: "CF",
    hand: "LHH",
    birth: "May 17 1994",
  },
  {
    name: "Kim Beom-jun",
    team: "nc",
    backNumber: "66",
    position: "OF",
    hand: "RHH",
    birth: "Apr 20 2000",
  },
  {
    name: "Ko Seung-wan",
    team: "nc",
    backNumber: "60",
    position: "OF",
    hand: "LHH",
    birth: "Mar 15 2001",
  },
  {
    name: "Kwon Hui-dong",
    team: "nc",
    backNumber: "36",
    position: "LF",
    hand: "RHH",
    birth: "Dec 30 1990",
  },
  {
    name: "Park Han-gyeol",
    team: "nc",
    backNumber: "3",
    position: "OF",
    hand: "RHH",
    birth: "Apr 26 2004",
  },
  {
    name: "Park Kun-woo",
    team: "nc",
    backNumber: "37",
    position: "RF",
    hand: "RHH",
    birth: "Sep 8 1990",
  },
  {
    name: "Park Si-won",
    team: "nc",
    backNumber: "53",
    position: "RF",
    hand: "LHH",
    birth: "May 30 2001",
  },
  {
    name: "Park Young-bin",
    team: "nc",
    backNumber: "39",
    position: "OF",
    hand: "LHH",
    birth: "Jul 16 1997",
  },
  {
    name: "Son Ah-seop",
    team: "nc",
    backNumber: "31",
    position: "RF",
    hand: "LHH",
    birth: "Mar 18 1988",
  },
  {
    name: "Song Seung-hwan",
    team: "nc",
    backNumber: "8",
    position: "OF",
    hand: "RHH",
    birth: "Oct 28 2000",
  },
  {
    name: "Bae Jae-june",
    team: "lg",
    backNumber: "25",
    position: "RP",
    hand: "RHP",
    birth: "Nov 24 1994",
  },
  {
    name: "Baek Seung-hyeon",
    team: "lg",
    backNumber: "61",
    position: "RP",
    hand: "RHP",
    birth: "May 26 1995",
  },
  {
    name: "Yonny Chirinos",
    team: "lg",
    backNumber: "46",
    position: "SP",
    hand: "RHP",
    birth: "Dec 26 1993",
  },
  {
    name: "Choi Chae-heung",
    team: "lg",
    backNumber: "56",
    position: "SP/RP",
    hand: "LHP",
    birth: "Jan 22 1995",
  },
  {
    name: "Chu Se-hyeon",
    team: "lg",
    backNumber: "63",
    position: "RP",
    hand: "RHP",
    birth: "Apr 19 2006",
  },
  {
    name: "Ham Deok-ju",
    team: "lg",
    backNumber: "11",
    position: "RP",
    hand: "LHP",
    birth: "Jan 13 1995",
  },
  {
    name: "Heo Jun-hyuk",
    team: "lg",
    backNumber: "58",
    position: "RP",
    hand: "RHP",
    birth: "Jul 2 1999",
  },
  {
    name: "Heo Yong-joo",
    team: "lg",
    backNumber: "43",
    position: "RP",
    hand: "RHP",
    birth: "Jun 5 2003",
  },
  {
    name: "Elieser Hernandez",
    team: "lg",
    backNumber: "30",
    position: "SP",
    hand: "RHP",
    birth: "May 3 1995",
  },
  {
    name: "Im Chan-kyu",
    team: "lg",
    backNumber: "1",
    position: "SP",
    hand: "RHP",
    birth: "Nov 20 1992",
  },
  {
    name: "Jang Hyun-sik",
    team: "lg",
    backNumber: "50",
    position: "CP",
    hand: "RHP",
    birth: "Feb 24 1995",
  },
  {
    name: "Jin Woo-young",
    team: "lg",
    backNumber: "48",
    position: "RP",
    hand: "RHP",
    birth: "Feb 5 2001",
  },
  {
    name: "Jung Ji-heon",
    team: "lg",
    backNumber: "99",
    position: "RP",
    hand: "RHP",
    birth: "Jan 1 2003",
  },
  {
    name: "Jung Woo-young",
    team: "lg",
    backNumber: "18",
    position: "RP",
    hand: "RHP",
    birth: "Aug 19 1999",
  },
  {
    name: "Kim Dae-hyun",
    team: "lg",
    backNumber: "12",
    position: "RP",
    hand: "RHP",
    birth: "Mar 8 1997",
  },
  {
    name: "Kim Jin-su",
    team: "lg",
    backNumber: "45",
    position: "RP",
    hand: "RHP",
    birth: "Aug 31 1998",
  },
  {
    name: "Kim Jin-sung",
    team: "lg",
    backNumber: "42",
    position: "RP",
    hand: "RHP",
    birth: "Mar 7 1985",
  },
  {
    name: "Kim Jong-wun",
    team: "lg",
    backNumber: "49",
    position: "RP",
    hand: "RHP",
    birth: "Sep 11 2006",
  },
  {
    name: "Kim Joo-on",
    team: "lg",
    backNumber: "57",
    position: "SP/RP",
    hand: "RHP",
    birth: "Dec 8 1996",
  },
  {
    name: "Kim Kang-ryul",
    team: "lg",
    backNumber: "37",
    position: "RP",
    hand: "RHP",
    birth: "Aug 28 1988",
  },
  {
    name: "Kim Young-jun",
    team: "lg",
    backNumber: "35",
    position: "RP",
    hand: "RHP",
    birth: "Jan 12 1999",
  },
  {
    name: "Kim Young-woo",
    team: "lg",
    backNumber: "67",
    position: "RP",
    hand: "RHP",
    birth: "Jan 14 2005",
  },
  {
    name: "Kim Yu-yeong",
    team: "lg",
    backNumber: "0",
    position: "RP",
    hand: "LHP",
    birth: "May 2 1994",
  },
  {
    name: "Lee Ji-gang",
    team: "lg",
    backNumber: "32",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jul 2 1999",
  },
  {
    name: "Lee Jong-jun",
    team: "lg",
    backNumber: "40",
    position: "RP",
    hand: "RHP",
    birth: "Mar 9 2001",
  },
  {
    name: "Lee Woo-chan",
    team: "lg",
    backNumber: "21",
    position: "RP",
    hand: "LHP",
    birth: "Aug 4 1992",
  },
  {
    name: "Lim Jun-hyong",
    team: "lg",
    backNumber: "59",
    position: "RP",
    hand: "LHP",
    birth: "Nov 16 2000",
  },
  {
    name: "Park Myung-geun",
    team: "lg",
    backNumber: "39",
    position: "RP",
    hand: "RHP",
    birth: "Mar 27 2004",
  },
  {
    name: "Sim Chang-min",
    team: "lg",
    backNumber: "28",
    position: "RP",
    hand: "RHP",
    birth: "Feb 1 1993",
  },
  {
    name: "Son Ju-young",
    team: "lg",
    backNumber: "29",
    position: "SP",
    hand: "LHP",
    birth: "Dec 2 1998",
  },
  {
    name: "Song Seung-ki",
    team: "lg",
    backNumber: "13",
    position: "SP",
    hand: "LHP",
    birth: "Apr 10 2002",
  },
  {
    name: "Sung Dong-hyun",
    team: "lg",
    backNumber: "34",
    position: "RP",
    hand: "RHP",
    birth: "May 18 1999",
  },
  {
    name: "Woo Kang-hoon",
    team: "lg",
    backNumber: "20",
    position: "RP",
    hand: "RHP",
    birth: "Oct 3 2002",
  },
  {
    name: "Coen Wynne",
    team: "lg",
    backNumber: "38",
    position: "SP/RP",
    hand: "RHP",
    birth: "Jan 25 1999",
  },
  {
    name: "Yi Jung-yong",
    team: "lg",
    backNumber: "31",
    position: "RP",
    hand: "RHP",
    birth: "Mar 26 1996",
  },
  {
    name: "You Young-chan",
    team: "lg",
    backNumber: "54",
    position: "RP",
    hand: "RHP",
    birth: "Mar 7 1997",
  },
  {
    name: "Kim Sung-woo",
    team: "lg",
    backNumber: "44",
    position: "C",
    hand: "RHH",
    birth: "Nov 15 2003",
  },
  {
    name: "Lee Han-lim",
    team: "lg",
    backNumber: "00",
    position: "C",
    hand: "RHH",
    birth: "Nov 18 2006",
  },
  {
    name: "Lee Ju-heon",
    team: "lg",
    backNumber: "26",
    position: "C",
    hand: "RHH",
    birth: "Mar 4 2003",
  },
  {
    name: "Park Dong-won",
    team: "lg",
    backNumber: "27",
    position: "C",
    hand: "RHH",
    birth: "Apr 7 1990",
  },
  {
    name: "Austin Dean",
    team: "lg",
    backNumber: "23",
    position: "1B",
    hand: "RHH",
    birth: "Oct 14 1993",
  },
  {
    name: "Gu Bon-hyeok",
    team: "lg",
    backNumber: "6",
    position: "2B",
    hand: "RHH",
    birth: "Jan 11 1997",
  },
  {
    name: "Kim Beom-seok",
    team: "lg",
    backNumber: "55",
    position: "1B",
    hand: "RHH",
    birth: "May 21 2004",
  },
  {
    name: "Kim Ju-sung",
    team: "lg",
    backNumber: "5",
    position: "IF",
    hand: "RHH",
    birth: "Jan 30 1998",
  },
  {
    name: "Kim Min-su",
    team: "lg",
    backNumber: "16",
    position: "3B",
    hand: "RHH",
    birth: "Mar 18 1998",
  },
  {
    name: "Kim Sung-jin",
    team: "lg",
    backNumber: "36",
    position: "IF",
    hand: "RHH",
    birth: "Mar 17 2000",
  },
  {
    name: "Lee Tae-hoon",
    team: "lg",
    backNumber: "65",
    position: "IF",
    hand: "LHH",
    birth: "Aug 21 2006",
  },
  {
    name: "Lee Young-bin",
    team: "lg",
    backNumber: "7",
    position: "1B",
    hand: "LHH",
    birth: "Jun 17 2002",
  },
  {
    name: "Moon Bo-gyeong",
    team: "lg",
    backNumber: "2",
    position: "3B",
    hand: "LHH",
    birth: "Jul 19 2000",
  },
  {
    name: "Moon Jeong-bin",
    team: "lg",
    backNumber: "53",
    position: "IF",
    hand: "RHH",
    birth: "Aug 15 2003",
  },
  {
    name: "Oh Ji-hwan",
    team: "lg",
    backNumber: "10",
    position: "SS",
    hand: "LHH",
    birth: "Mar 12 1990",
  },
  {
    name: "Shin Min-jae",
    team: "lg",
    backNumber: "4",
    position: "2B",
    hand: "LHH",
    birth: "Jan 21 1996",
  },
  {
    name: "Son Yung-jun",
    team: "lg",
    backNumber: "52",
    position: "IF",
    hand: "RHH",
    birth: "Feb 15 2000",
  },
  {
    name: "An Ik-hun",
    team: "lg",
    backNumber: "15",
    position: "LF",
    hand: "LHH",
    birth: "Feb 12 1996",
  },
  {
    name: "Choi Seung-min",
    team: "lg",
    backNumber: "62",
    position: "LF",
    hand: "LHH",
    birth: "Jul 1 1996",
  },
  {
    name: "Choi Won-yeong",
    team: "lg",
    backNumber: "3",
    position: "RF",
    hand: "RHH",
    birth: "Jul 18 2003",
  },
  {
    name: "Ham Chang-geon",
    team: "lg",
    backNumber: "24",
    position: "OF",
    hand: "LHH",
    birth: "Aug 18 2001",
  },
  {
    name: "Hong Chang-ki",
    team: "lg",
    backNumber: "51",
    position: "RF",
    hand: "LHH",
    birth: "Nov 21 1993",
  },
  {
    name: "Kim Hyun-jong",
    team: "lg",
    backNumber: "66",
    position: "OF",
    hand: "RHH",
    birth: "Aug 4 2004",
  },
  {
    name: "Kim Hyun-soo",
    team: "lg",
    backNumber: "22",
    position: "LF",
    hand: "LHH",
    birth: "Jan 12 1988",
  },
  {
    name: "Moon Sung-ju",
    team: "lg",
    backNumber: "8",
    position: "LF",
    hand: "LHH",
    birth: "Feb 20 1997",
  },
  {
    name: "Park Gwan-woo",
    team: "lg",
    backNumber: "64",
    position: "OF",
    hand: "LHH",
    birth: "Mar 22 2006",
  },
  {
    name: "Park Hae-min",
    team: "lg",
    backNumber: "17",
    position: "CF",
    hand: "LHH",
    birth: "Feb 24 1990",
  },
  {
    name: "Seo Young-jun",
    team: "lg",
    backNumber: "60",
    position: "OF",
    hand: "RHH",
    birth: "Mar 18 2006",
  },
  {
    name: "Song Chan-eui",
    team: "lg",
    backNumber: "14",
    position: "LF",
    hand: "RHH",
    birth: "Feb 20 1999",
  },
];
